/* curriculum.js — the drill library.
 * Claude edits this file in response to feedback in feedback.js.
 * Loaded as a plain script (not fetched) so it works on file:// and https alike.
 */
window.CURRICULUM = {
  version: 1,
  updated: '2026-07-28',
  startDefault: '2026-07-28',   // Monday

  disciplines: {
    groove:   {label:'Groove',   hue:'#D9974A', blurb:'Rhythm, rests, swing, pattern length.'},
    sound:    {label:'Sound',    hue:'#6B8AAD', blurb:'Engines, filter, envelopes — timbre as craft.'},
    melody:   {label:'Melody',   hue:'#68A98C', blurb:'Motif, contour, development.'},
    movement: {label:'Movement', hue:'#9B7EC0', blurb:'Modulation: matrix, cycling envelope, LFO.'},
    ear:      {label:'Ear',      hue:'#C77D8A', blurb:'Copy what you love. Badly is fine.'},
    assemble: {label:'Assemble', hue:'#8A94A6', blurb:'Turn the week into something.'},
  },

  // weekday index 1=Mon … 6=Sat. Sunday is deliberately empty.
  rotation: {1:'groove', 2:'sound', 3:'melody', 4:'movement', 5:'ear', 6:'assemble'},

  months: [
    {n:1, name:'Play',      weeks:[1,2,3,4],
     constraint:'MicroFreak only. No computer. Record to your phone.',
     checkpoint:'60 seconds that sounds intentional rather than exploratory.'},
    {n:2, name:'Move',      weeks:[5,6,7,8],
     constraint:'Every patch uses at least two matrix cells.',
     checkpoint:'A 2-minute piece where nothing repeats identically.',
     status:'built after Month 1 feedback'},
    {n:3, name:'Structure', weeks:[9,10,11,12],
     constraint:'Ableton returns. Loops become sections.',
     checkpoint:'A 3-minute arrangement with a real breakdown.',
     status:'built after Month 2 feedback'},
    {n:4, name:'Finish',    weeks:[13,14,15,16],
     constraint:'No new ideas. Only completion.',
     checkpoint:'One finished track.',
     status:'built after Month 3 feedback'},
  ],

  drills: [
    /* ---------------- WEEK 1 ---------------- */
    {id:'w1-groove', week:1, d:'groove', title:'Rests are the rhythm',
     goal:'Learn that a pattern is defined by its gaps, not its hits.',
     steps:['Build a 16-step sequence using only ONE low note.',
            'Make three versions that differ only in where rests and ties fall.',
            'Play each at the same tempo. Pick the one that makes you nod.'],
     listen:'The version you like almost certainly has fewer notes than you expected.',
     capture:'60s of the best version.',
     why:'Arturia’s own manual: a 32-step sequence with rests and ties beats a 16-step with every slot filled.'},

    {id:'w1-sound', week:1, d:'sound', title:'One engine you have never used',
     goal:'Break the habit of living in one or two oscillator types.',
     steps:['Pick an oscillator Type you have genuinely never used.',
            'Ten minutes. Find three usable sounds using only Wave, Timbre, Shape and the filter.',
            'Do not touch the matrix or the envelopes yet.'],
     listen:'Notice that Wave/Timbre/Shape do something completely different here than in your usual engine.',
     capture:'20 seconds of each of the three sounds.',
     why:'The three macro knobs are re-wired by every engine. That is the single most misunderstood thing about this synth.'},

    {id:'w1-melody', week:1, d:'melody', title:'Hoketus — one pitch only',
     goal:'Separate "melody" from "pitch".',
     steps:['16-step sequence. Every step the SAME note.',
            'Vary only rhythm: place rests and ties by ear until it stops sounding stuck.',
            'Then record one modulation lane — a Timbre sweep — into the sequence.'],
     listen:'The moment it stops sounding like a held note and starts sounding like a phrase.',
     capture:'60s.',
     why:'An ancient technique the manual names directly. Forces timbre to carry the tune.',
     melody:'If you can make ONE pitch interesting, a real melody becomes much easier — you stop leaning on note choice to do all the work.'},

    {id:'w1-movement', week:1, d:'movement', title:'Cycling Envelope into Timbre',
     goal:'Meet the feature that makes this synth unusual.',
     steps:['Matrix: select Cycling Env → Timbre. Press the encoder, dial a moderate amount.',
            'Set Cycling Env Mode to LOOP. Hold set low.',
            'Hold one note for a full minute. While it runs, move Rise and Fall.'],
     listen:'You are redrawing the shape of the modulation while you hear it. A normal LFO cannot do this.',
     capture:'60s of one held note evolving.',
     why:'A looping envelope is an LFO whose shape you drew. This is the backbone of evolving electronic parts.'},

    {id:'w1-ear', week:1, d:'ear', title:'Steal a rhythm',
     goal:'Start training transcription with the easiest target.',
     steps:['Pick 8 seconds of a track you love.',
            'Work out the BASSLINE RHYTHM only. Ignore pitch entirely if it is hard.',
            'Rebuild that rhythm on the sequencer with any single note.'],
     listen:'Where the bass sits relative to the kick. That relationship is most of the genre.',
     capture:'The rebuilt rhythm, 30s.',
     why:'Rhythm is the most transferable thing you can steal, and nobody can hear that you stole it.'},

    {id:'w1-assemble', week:1, d:'assemble', title:'Two captures, one minute',
     goal:'Practise finishing, at the smallest possible scale.',
     steps:['Listen back to this week’s five captures.',
            'Pick the two that go together. Layer them into 60–90 seconds.',
            'Do not polish. Do not add a third thing.'],
     listen:'Whether the pair actually needs anything else. Usually not.',
     capture:'The 90s assembly.',
     why:'Finishing is a separate skill from making, and it only improves with reps.'},

    /* ---------------- WEEK 2 ---------------- */
    {id:'w2-groove', week:2, d:'groove', title:'Get off the downbeat',
     goal:'Stop writing everything on beats 1 and 3.',
     steps:['Build a 16-step pattern with NOTHING on step 1.',
            'Put your strongest accent on an offbeat 16th.',
            'Then turn on the arpeggiator swing and find the amount that feels human, not broken.'],
     listen:'The pattern should still feel anchored even with an empty downbeat. If it feels lost, move one hit.',
     capture:'60s.',
     why:'House and techno live on the offbeat. Learning to imply the downbeat without playing it is the whole trick.'},

    {id:'w2-sound', week:2, d:'sound', title:'The filter as the instrument',
     goal:'Get three characters from one oscillator setting.',
     steps:['Pick ONE engine and freeze Wave/Timbre/Shape. Do not touch them again.',
            'Using only Cutoff, Resonance and Envelope Filter Amount, build: a dark bass, a bright pluck, a hollow whisper.',
            'For the whisper, switch the filter to band-pass.'],
     listen:'How much of "what instrument is this" is decided after the oscillator.',
     capture:'20s of each.',
     why:'The analogue filter is the only analogue part of the path. It is doing more of the work than you think.'},

    {id:'w2-melody', week:2, d:'melody', title:'One idea, four ways',
     goal:'Learn development — the difference between a loop and a composition.',
     steps:['Write a THREE-note motif. Three notes. No more.',
            'State it four times: as written; inverted (upside-down contour); at half speed; then just its first two notes.',
            'Play them in a row as one 8-bar phrase.'],
     listen:'It should sound like one idea being explored, not four ideas.',
     capture:'The 8-bar phrase.',
     why:'This is what separates composed music from a loop, in every genre.',
     melody:'Inversion, augmentation and fragmentation are the three cheapest ways to get more music out of an idea you already like.'},

    {id:'w2-movement', week:2, d:'movement', title:'Pressure into the matrix',
     goal:'Make the keyboard expressive instead of binary.',
     steps:['Set Utility > Preset > Press mode > Aftertouch.',
            'Matrix: Press → Cutoff, moderate positive amount.',
            'Play one phrase three times: gently, normally, leaning hard.'],
     listen:'The same notes carrying three different intensities with no knob-turning.',
     capture:'The three passes back to back.',
     why:'The keys do not move, so people play this synth like a computer. Pressure is the fix.'},

    {id:'w2-ear', week:2, d:'ear', title:'Contour, not pitches',
     goal:'Train shape-hearing before interval-hearing.',
     steps:['Take a melody you love. Do NOT try to find exact notes.',
            'Draw its shape in the air: up, up, down, big jump down, slow climb.',
            'Play any notes that follow that shape on the MicroFreak.'],
     listen:'How much of the melody’s identity survives with completely wrong pitches.',
     capture:'Your shape version, 30s.',
     why:'Contour is what listeners actually remember. Exact intervals come later and come easier.'},

    {id:'w2-assemble', week:2, d:'assemble', title:'Add the week’s groove to last week’s best',
     goal:'Make captures compound instead of pile up.',
     steps:['Take your favourite capture from Week 1.',
            'Put this week’s groove underneath it.',
            'Cut anything that fights. Keep it under two minutes.'],
     listen:'Whether the older idea still holds up. Be honest.',
     capture:'The combined take.',
     why:'Your library only has value if you go back into it.'},

    /* ---------------- WEEK 3 ---------------- */
    {id:'w3-groove', week:3, d:'groove', title:'A pattern that is not 16 steps',
     goal:'Feel polyrhythm from the inside.',
     steps:['Set the sequence length to 12 steps (Utility > Preset > Seq Length).',
            'Write a pattern you like. Let it run against a straight 4/4 pulse in your head.',
            'Listen for where it comes back into alignment. Then try 7 steps.'],
     listen:'The pattern phases — it drifts against the bar and re-lands. That drift is free variation.',
     capture:'60s of the 12-step version.',
     why:'The manual’s clave trick, generalised: uneven lengths generate variation you never programmed.'},

    {id:'w3-sound', week:3, d:'sound', title:'Same settings, different engine',
     goal:'Build an internal map of what the engines are FOR.',
     steps:['Set Wave, Timbre, Shape all to roughly 12 o’clock. Note the positions.',
            'Now step through six engines without touching those knobs.',
            'Write one word for each engine describing what it is good at.'],
     listen:'Some engines are unusable at these settings. That is information, not failure.',
     capture:'10s of each of the six.',
     why:'You cannot reach for the right engine on purpose until you know what each is for.'},

    {id:'w3-melody', week:3, d:'melody', title:'Call and response',
     goal:'Write in phrases instead of loops.',
     steps:['Write a 2-bar phrase that ends unresolved — it should feel like a question.',
            'Write a 2-bar answer that resolves it, reusing at least one rhythm from the question.',
            'Play the pair. Then play question, question, answer.'],
     listen:'The answer should feel inevitable, not new.',
     capture:'The 8-bar version.',
     why:'Almost all memorable melodies are a question and an answer, in every genre.',
     melody:'If the answer sounds unrelated, you changed too much. Keep the rhythm, change the pitches.'},

    {id:'w3-movement', week:3, d:'movement', title:'Modulate the modulator',
     goal:'Build your first modulation chain.',
     steps:['Matrix: LFO → Cycling Env Rise (a slow sine works well).',
            'Matrix: Cycling Env → Filter Cutoff.',
            'Hold a note. The shape of the filter movement now changes over time by itself.'],
     listen:'A modulation that never quite repeats, from two simple sources.',
     capture:'90s of one held chord.',
     why:'The manual is explicit that this is where it gets good: put the envelope’s own stages under control.'},

    {id:'w3-ear', week:3, d:'ear', title:'Just the roots',
     goal:'Start hearing harmony without theory.',
     steps:['Pick a track with an obvious chord change.',
            'Find only the LOWEST note of each chord by hunting on the keyboard.',
            'Write the sequence of roots down. Ignore whether they are major or minor.'],
     listen:'How few distinct roots most electronic tracks use. Often four.',
     capture:'The root sequence played as long notes.',
     why:'Roots are 80% of a progression’s identity and by far the easiest part to hear.'},

    {id:'w3-assemble', week:3, d:'assemble', title:'Question, answer, and a groove',
     goal:'Combine disciplines rather than stacking captures.',
     steps:['Take this week’s call-and-response melody.',
            'Put the 12-step groove under it. Let the phasing do the variation.',
            'Two minutes maximum.'],
     listen:'The polyrhythm should make the melody feel different on each repeat.',
     capture:'The 2-minute piece.',
     why:'This is the first time the week’s drills are designed to fit together.'},

    /* ---------------- WEEK 4 ---------------- */
    {id:'w4-groove', week:4, d:'groove', title:'Long and sparse',
     goal:'Use the full 64 steps without filling them.',
     steps:['Set sequence length to 32. Double the tempo.',
            'Fill no more than a third of the steps.',
            'Use ties to make some notes long and some very short.'],
     listen:'A long sparse pattern reads as composed. A short dense one reads as a loop.',
     capture:'90s.',
     why:'Direct from the manual, and it is the fastest upgrade available to a sequence.'},

    {id:'w4-sound', week:4, d:'sound', title:'Bass, lead, texture — one engine',
     goal:'Prove that range comes from you, not from preset-hunting.',
     steps:['Choose one engine for the whole session.',
            'Build a bass (short, dark, low), a lead (bright, mid, some resonance), a texture (slow attack, filtered, high).',
            'Save all three if you have slots free.'],
     listen:'How different envelope settings alone make one engine sound like three instruments.',
     capture:'30s of each.',
     why:'Ends Month 1 by proving the instrument is deeper than its preset list.'},

    {id:'w4-melody', week:4, d:'melody', title:'Five notes, then one outsider',
     goal:'Learn why one “wrong” note is worth more than ten right ones.',
     steps:['Restrict yourself to a five-note (pentatonic) set. Write an 8-bar melody.',
            'Now change exactly ONE note to something outside the set.',
            'Move that outside note around until it lands in the most affecting spot.'],
     listen:'The outside note should feel like the point of the melody.',
     capture:'Both versions, back to back.',
     why:'Pentatonic is safe and slightly bland; the single outsider is where feeling comes from.',
     melody:'In A minor, the note to try is usually G# — it belongs to harmonic minor and pulls hard back to A.'},

    {id:'w4-movement', week:4, d:'movement', title:'Two cells at once',
     goal:'Start patching reflexively rather than one connection at a time.',
     steps:['Patch Press → Cutoff AND Key/Arp → Timbre.',
            'Play a line that moves up and down the keyboard, varying pressure.',
            'The sound should now change with both register and touch.'],
     listen:'High notes brighter, hard presses more open — without you touching a knob.',
     capture:'60s.',
     why:'Two or three cells is the difference between a patch and an instrument.'},

    {id:'w4-ear', week:4, d:'ear', title:'From memory, badly',
     goal:'Test what you have actually internalised.',
     steps:['Without listening to it, recreate 8 bars of a track you know well.',
            'Then play the original.',
            'Note the three biggest differences.'],
     listen:'The gaps between your memory and the record are exactly your next month’s syllabus.',
     capture:'Your version.',
     why:'This is a diagnostic, not a performance. Being wrong is the useful outcome.'},

    {id:'w4-assemble', week:4, d:'assemble', title:'Month 1 checkpoint',
     goal:'Produce the month’s deliverable.',
     steps:['Make 60 seconds that sounds intentional rather than exploratory.',
            'Use anything from the month. MicroFreak only.',
            'Then listen to all 24 captures in order and note what improved.'],
     listen:'Compare Week 1 to Week 4. The difference should be audible.',
     capture:'The 60-second checkpoint piece.',
     why:'One month of 15-minute sessions is about six hours. Six focused hours is a lot.'},
  ],
};
