/* curriculum.js — the drill library.
 * Claude edits this file in response to feedback in feedback.js.
 * Loaded as a plain script (not fetched) so it works on file:// and https alike.
 */
window.CURRICULUM = {
  version: 2,
  updated: '2026-07-28',
  startDefault: '2026-07-28',   // Monday

  disciplines: {
    groove:   {label:'Groove',   hue:'#D9974A', blurb:'Rhythm, rests, swing, pattern length.'},
    sound:    {label:'Sound',    hue:'#6B8AAD', blurb:'Engines, filter, envelopes — timbre as craft.'},
    melody:   {label:'Melody',   hue:'#68A98C', blurb:'Motif, contour, development.'},
    movement: {label:'Movement', hue:'#9B7EC0', blurb:'Modulation: matrix, cycling envelope, LFO.'},
    ear:      {label:'Ear',      hue:'#C77D8A', blurb:'Copy what you love. Badly is fine.'},
    assemble: {label:'Assemble', hue:'#8A94A6', blurb:'Turn the week into something.'},
  },

  // weekday index 1=Mon … 6=Sat. Sunday is deliberately empty.
  rotation: {1:'groove', 2:'sound', 3:'melody', 4:'movement', 5:'ear', 6:'assemble'},

  months: [
    {n:1, name:'Play',      weeks:[1,2,3,4],
     constraint:'MicroFreak only. No computer. Record to your phone.',
     checkpoint:'60 seconds that sounds intentional rather than exploratory.'},
    {n:2, name:'Move',      weeks:[5,6,7,8],
     constraint:'Every patch uses at least two matrix cells.',
     checkpoint:'A 2-minute piece where nothing repeats identically.'},
    {n:3, name:'Structure', weeks:[9,10,11,12],
     constraint:'Ableton returns. Loops become sections.',
     checkpoint:'A 3-minute arrangement with a real breakdown.'},
    {n:4, name:'Finish',    weeks:[13,14,15,16],
     constraint:'No new ideas. Only completion.',
     checkpoint:'One finished track.'},
  ],

  drills: [
    /* ---------------- WEEK 1 ---------------- */
    {id:'w1-groove', week:1, d:'groove', title:'Rests are the rhythm',
     goal:'Learn that a pattern is defined by its gaps, not its hits.',
     steps:['Build a 16-step sequence using only ONE low note.',
            'Make three versions that differ only in where rests and ties fall.',
            'Play each at the same tempo. Pick the one that makes you nod.'],
     listen:'The version you like almost certainly has fewer notes than you expected.',
     capture:'60s of the best version.',
     why:'Arturia’s own manual: a 32-step sequence with rests and ties beats a 16-step with every slot filled.'},

    {id:'w1-sound', week:1, d:'sound', title:'One engine you have never used',
     goal:'Break the habit of living in one or two oscillator types.',
     steps:['Pick an oscillator Type you have genuinely never used.',
            'Ten minutes. Find three usable sounds using only Wave, Timbre, Shape and the filter.',
            'Do not touch the matrix or the envelopes yet.'],
     listen:'Notice that Wave/Timbre/Shape do something completely different here than in your usual engine.',
     capture:'20 seconds of each of the three sounds.',
     why:'The three macro knobs are re-wired by every engine. That is the single most misunderstood thing about this synth.'},

    {id:'w1-melody', week:1, d:'melody', title:'Hoketus — one pitch only',
     goal:'Separate "melody" from "pitch".',
     steps:['16-step sequence. Every step the SAME note.',
            'Vary only rhythm: place rests and ties by ear until it stops sounding stuck.',
            'Then record one modulation lane — a Timbre sweep — into the sequence.'],
     listen:'The moment it stops sounding like a held note and starts sounding like a phrase.',
     capture:'60s.',
     why:'An ancient technique the manual names directly. Forces timbre to carry the tune.',
     melody:'If you can make ONE pitch interesting, a real melody becomes much easier — you stop leaning on note choice to do all the work.'},

    {id:'w1-movement', week:1, d:'movement', title:'Cycling Envelope into Timbre',
     goal:'Meet the feature that makes this synth unusual.',
     steps:['Matrix: select Cycling Env → Timbre. Press the encoder, dial a moderate amount.',
            'Set Cycling Env Mode to LOOP. Hold set low.',
            'Hold one note for a full minute. While it runs, move Rise and Fall.'],
     listen:'You are redrawing the shape of the modulation while you hear it. A normal LFO cannot do this.',
     capture:'60s of one held note evolving.',
     why:'A looping envelope is an LFO whose shape you drew. This is the backbone of evolving electronic parts.'},

    {id:'w1-ear', week:1, d:'ear', title:'Steal a rhythm',
     goal:'Start training transcription with the easiest target.',
     steps:['Pick 8 seconds of a track you love.',
            'Work out the BASSLINE RHYTHM only. Ignore pitch entirely if it is hard.',
            'Rebuild that rhythm on the sequencer with any single note.'],
     listen:'Where the bass sits relative to the kick. That relationship is most of the genre.',
     capture:'The rebuilt rhythm, 30s.',
     why:'Rhythm is the most transferable thing you can steal, and nobody can hear that you stole it.'},

    {id:'w1-assemble', week:1, d:'assemble', title:'Two captures, one minute',
     goal:'Practise finishing, at the smallest possible scale.',
     steps:['Listen back to this week’s five captures.',
            'Pick the two that go together. Layer them into 60–90 seconds.',
            'Do not polish. Do not add a third thing.'],
     listen:'Whether the pair actually needs anything else. Usually not.',
     capture:'The 90s assembly.',
     why:'Finishing is a separate skill from making, and it only improves with reps.'},

    /* ---------------- WEEK 2 ---------------- */
    {id:'w2-groove', week:2, d:'groove', title:'Get off the downbeat',
     goal:'Stop writing everything on beats 1 and 3.',
     steps:['Build a 16-step pattern with NOTHING on step 1.',
            'Put your strongest accent on an offbeat 16th.',
            'Then turn on the arpeggiator swing and find the amount that feels human, not broken.'],
     listen:'The pattern should still feel anchored even with an empty downbeat. If it feels lost, move one hit.',
     capture:'60s.',
     why:'House and techno live on the offbeat. Learning to imply the downbeat without playing it is the whole trick.'},

    {id:'w2-sound', week:2, d:'sound', title:'The filter as the instrument',
     goal:'Get three characters from one oscillator setting.',
     steps:['Pick ONE engine and freeze Wave/Timbre/Shape. Do not touch them again.',
            'Using only Cutoff, Resonance and Envelope Filter Amount, build: a dark bass, a bright pluck, a hollow whisper.',
            'For the whisper, switch the filter to band-pass.'],
     listen:'How much of "what instrument is this" is decided after the oscillator.',
     capture:'20s of each.',
     why:'The analogue filter is the only analogue part of the path. It is doing more of the work than you think.'},

    {id:'w2-melody', week:2, d:'melody', title:'One idea, four ways',
     goal:'Learn development — the difference between a loop and a composition.',
     steps:['Write a THREE-note motif. Three notes. No more.',
            'State it four times: as written; inverted (upside-down contour); at half speed; then just its first two notes.',
            'Play them in a row as one 8-bar phrase.'],
     listen:'It should sound like one idea being explored, not four ideas.',
     capture:'The 8-bar phrase.',
     why:'This is what separates composed music from a loop, in every genre.',
     melody:'Inversion, augmentation and fragmentation are the three cheapest ways to get more music out of an idea you already like.'},

    {id:'w2-movement', week:2, d:'movement', title:'Pressure into the matrix',
     goal:'Make the keyboard expressive instead of binary.',
     steps:['Set Utility > Preset > Press mode > Aftertouch.',
            'Matrix: Press → Cutoff, moderate positive amount.',
            'Play one phrase three times: gently, normally, leaning hard.'],
     listen:'The same notes carrying three different intensities with no knob-turning.',
     capture:'The three passes back to back.',
     why:'The keys do not move, so people play this synth like a computer. Pressure is the fix.'},

    {id:'w2-ear', week:2, d:'ear', title:'Contour, not pitches',
     goal:'Train shape-hearing before interval-hearing.',
     steps:['Take a melody you love. Do NOT try to find exact notes.',
            'Draw its shape in the air: up, up, down, big jump down, slow climb.',
            'Play any notes that follow that shape on the MicroFreak.'],
     listen:'How much of the melody’s identity survives with completely wrong pitches.',
     capture:'Your shape version, 30s.',
     why:'Contour is what listeners actually remember. Exact intervals come later and come easier.'},

    {id:'w2-assemble', week:2, d:'assemble', title:'Add the week’s groove to last week’s best',
     goal:'Make captures compound instead of pile up.',
     steps:['Take your favourite capture from Week 1.',
            'Put this week’s groove underneath it.',
            'Cut anything that fights. Keep it under two minutes.'],
     listen:'Whether the older idea still holds up. Be honest.',
     capture:'The combined take.',
     why:'Your library only has value if you go back into it.'},

    /* ---------------- WEEK 3 ---------------- */
    {id:'w3-groove', week:3, d:'groove', title:'A pattern that is not 16 steps',
     goal:'Feel polyrhythm from the inside.',
     steps:['Set the sequence length to 12 steps (Utility > Preset > Seq Length).',
            'Write a pattern you like. Let it run against a straight 4/4 pulse in your head.',
            'Listen for where it comes back into alignment. Then try 7 steps.'],
     listen:'The pattern phases — it drifts against the bar and re-lands. That drift is free variation.',
     capture:'60s of the 12-step version.',
     why:'The manual’s clave trick, generalised: uneven lengths generate variation you never programmed.'},

    {id:'w3-sound', week:3, d:'sound', title:'Same settings, different engine',
     goal:'Build an internal map of what the engines are FOR.',
     steps:['Set Wave, Timbre, Shape all to roughly 12 o’clock. Note the positions.',
            'Now step through six engines without touching those knobs.',
            'Write one word for each engine describing what it is good at.'],
     listen:'Some engines are unusable at these settings. That is information, not failure.',
     capture:'10s of each of the six.',
     why:'You cannot reach for the right engine on purpose until you know what each is for.'},

    {id:'w3-melody', week:3, d:'melody', title:'Call and response',
     goal:'Write in phrases instead of loops.',
     steps:['Write a 2-bar phrase that ends unresolved — it should feel like a question.',
            'Write a 2-bar answer that resolves it, reusing at least one rhythm from the question.',
            'Play the pair. Then play question, question, answer.'],
     listen:'The answer should feel inevitable, not new.',
     capture:'The 8-bar version.',
     why:'Almost all memorable melodies are a question and an answer, in every genre.',
     melody:'If the answer sounds unrelated, you changed too much. Keep the rhythm, change the pitches.'},

    {id:'w3-movement', week:3, d:'movement', title:'Modulate the modulator',
     goal:'Build your first modulation chain.',
     steps:['Matrix: LFO → Cycling Env Rise (a slow sine works well).',
            'Matrix: Cycling Env → Filter Cutoff.',
            'Hold a note. The shape of the filter movement now changes over time by itself.'],
     listen:'A modulation that never quite repeats, from two simple sources.',
     capture:'90s of one held chord.',
     why:'The manual is explicit that this is where it gets good: put the envelope’s own stages under control.'},

    {id:'w3-ear', week:3, d:'ear', title:'Just the roots',
     goal:'Start hearing harmony without theory.',
     steps:['Pick a track with an obvious chord change.',
            'Find only the LOWEST note of each chord by hunting on the keyboard.',
            'Write the sequence of roots down. Ignore whether they are major or minor.'],
     listen:'How few distinct roots most electronic tracks use. Often four.',
     capture:'The root sequence played as long notes.',
     why:'Roots are 80% of a progression’s identity and by far the easiest part to hear.'},

    {id:'w3-assemble', week:3, d:'assemble', title:'Question, answer, and a groove',
     goal:'Combine disciplines rather than stacking captures.',
     steps:['Take this week’s call-and-response melody.',
            'Put the 12-step groove under it. Let the phasing do the variation.',
            'Two minutes maximum.'],
     listen:'The polyrhythm should make the melody feel different on each repeat.',
     capture:'The 2-minute piece.',
     why:'This is the first time the week’s drills are designed to fit together.'},

    /* ---------------- WEEK 4 ---------------- */
    {id:'w4-groove', week:4, d:'groove', title:'Long and sparse',
     goal:'Use the full 64 steps without filling them.',
     steps:['Set sequence length to 32. Double the tempo.',
            'Fill no more than a third of the steps.',
            'Use ties to make some notes long and some very short.'],
     listen:'A long sparse pattern reads as composed. A short dense one reads as a loop.',
     capture:'90s.',
     why:'Direct from the manual, and it is the fastest upgrade available to a sequence.'},

    {id:'w4-sound', week:4, d:'sound', title:'Bass, lead, texture — one engine',
     goal:'Prove that range comes from you, not from preset-hunting.',
     steps:['Choose one engine for the whole session.',
            'Build a bass (short, dark, low), a lead (bright, mid, some resonance), a texture (slow attack, filtered, high).',
            'Save all three if you have slots free.'],
     listen:'How different envelope settings alone make one engine sound like three instruments.',
     capture:'30s of each.',
     why:'Ends Month 1 by proving the instrument is deeper than its preset list.'},

    {id:'w4-melody', week:4, d:'melody', title:'Five notes, then one outsider',
     goal:'Learn why one “wrong” note is worth more than ten right ones.',
     steps:['Restrict yourself to a five-note (pentatonic) set. Write an 8-bar melody.',
            'Now change exactly ONE note to something outside the set.',
            'Move that outside note around until it lands in the most affecting spot.'],
     listen:'The outside note should feel like the point of the melody.',
     capture:'Both versions, back to back.',
     why:'Pentatonic is safe and slightly bland; the single outsider is where feeling comes from.',
     melody:'In A minor, the note to try is usually G# — it belongs to harmonic minor and pulls hard back to A.'},

    {id:'w4-movement', week:4, d:'movement', title:'Two cells at once',
     goal:'Start patching reflexively rather than one connection at a time.',
     steps:['Patch Press → Cutoff AND Key/Arp → Timbre.',
            'Play a line that moves up and down the keyboard, varying pressure.',
            'The sound should now change with both register and touch.'],
     listen:'High notes brighter, hard presses more open — without you touching a knob.',
     capture:'60s.',
     why:'Two or three cells is the difference between a patch and an instrument.'},

    {id:'w4-ear', week:4, d:'ear', title:'From memory, badly',
     goal:'Test what you have actually internalised.',
     steps:['Without listening to it, recreate 8 bars of a track you know well.',
            'Then play the original.',
            'Note the three biggest differences.'],
     listen:'The gaps between your memory and the record are exactly your next month’s syllabus.',
     capture:'Your version.',
     why:'This is a diagnostic, not a performance. Being wrong is the useful outcome.'},

    {id:'w4-assemble', week:4, d:'assemble', title:'Month 1 checkpoint',
     goal:'Produce the month’s deliverable.',
     steps:['Make 60 seconds that sounds intentional rather than exploratory.',
            'Use anything from the month. MicroFreak only.',
            'Then listen to all 24 captures in order and note what improved.'],
     listen:'Compare Week 1 to Week 4. The difference should be audible.',
     capture:'The 60-second checkpoint piece.',
     why:'One month of 15-minute sessions is about six hours. Six focused hours is a lot.'},

    /* ================= MONTH 2 — MOVE ================= */
    /* ---------------- WEEK 5 ---------------- */
    {id:'w5-groove', week:5, d:'groove', title:'Record a knob move into the sequence',
     goal:'Use the modulation lanes — the most ignored feature on the box.',
     steps:['Write a simple 16-step pattern.',
            'Press the record icon for step mode. Turn the Timbre knob at a few steps, advancing with Rate.',
            'Let it loop. The knob move is now part of the pattern.'],
     listen:'The pattern now changes without you touching anything.',
     capture:'60s.',
     why:'Four modulation lanes per sequence. Most owners never record one.'},
    {id:'w5-sound', week:5, d:'sound', title:'Cycling Envelope shapes the main Envelope',
     goal:'Build your first modulation chain in service of a sound.',
     steps:['Matrix: Cycling Env → an assignable slot set to Envelope Decay.',
            'Set Cycling Env to LOOP, slow.',
            'Play a repeating note. The length of each note now varies by itself.'],
     listen:'Notes that breathe — some short, some long, no sequencer involved.',
     capture:'45s.',
     why:'The manual calls this out specifically: use one envelope to control the stages of the other.'},
    {id:'w5-melody', week:5, d:'melody', title:'Same notes, new meaning',
     goal:'Develop a melody without changing a single pitch.',
     steps:['Take your best melody from Month 1.',
            'Change nothing about the notes. Change only: gate length, one modulation lane, and the filter.',
            'Make it feel urgent. Then make the same notes feel resigned.'],
     listen:'How much emotional range lives outside of pitch.',
     capture:'Both versions.',
     why:'Arrangement and timbre carry more feeling than note choice does.',
     melody:'When a melody is not working, the problem is usually rhythm or sound — not the notes.'},
    {id:'w5-movement', week:5, d:'movement', title:'Three cells at once',
     goal:'Make patching reflexive.',
     steps:['Patch Press → Cutoff, Key/Arp → Timbre, and LFO → Shape.',
            'Play a phrase that moves across registers with varying pressure.',
            'Remove one cell. Notice what you lose.'],
     listen:'Which of the three is doing the most work. Keep that one.',
     capture:'60s.',
     why:'Month 2’s rule is two cells minimum. Three teaches you which ones matter.'},
    {id:'w5-ear', week:5, d:'ear', title:'What is moving?',
     goal:'Hear modulation as a separate layer from notes.',
     steps:['Play a track you love. Ignore the melody entirely.',
            'Write down everything that MOVES: filter opening, a pad swelling, a stutter.',
            'Pick one and recreate just that movement.'],
     listen:'Most electronic tracks have three or four things moving continuously.',
     capture:'Your recreation of one movement.',
     why:'Once you hear modulation as its own layer, you cannot un-hear it.'},
    {id:'w5-assemble', week:5, d:'assemble', title:'Nothing repeats identically',
     goal:'Practise the month’s checkpoint at small scale.',
     steps:['Take a 4-bar loop from this week.',
            'Make it run for 90 seconds where no two passes are identical — using modulation only.',
            'Do not add or remove notes.'],
     listen:'Variation without new material. That is the whole month.',
     capture:'90s.',
     why:'The difference between a loop and a piece of music is often just modulation.'},

    /* ---------------- WEEK 6 ---------------- */
    {id:'w6-groove', week:6, d:'groove', title:'Spice and Dice',
     goal:'Use controlled randomness as a compositional tool.',
     steps:['Run a sequence you like. Add a SMALL amount of Spice.',
            'Hit Dice repeatedly. Stop when something better than your idea appears.',
            'Write down what it did so you can do it deliberately next time.'],
     listen:'Low Spice = human looseness. High Spice = a different composer.',
     capture:'The best roll.',
     why:'Dice is a collaborator you can overrule. That is the right way to use randomness.'},
    {id:'w6-sound', week:6, d:'sound', title:'Two engines, one modulation',
     goal:'Learn how engines respond differently to the same movement.',
     steps:['Set up Cycling Env → Timbre at a moderate amount.',
            'Play the same phrase through four different engines without changing the patch.',
            'Rank them for this modulation.'],
     listen:'Some engines transform dramatically; others barely react.',
     capture:'15s of each.',
     why:'Knowing which engines are modulation-friendly saves you hours later.'},
    {id:'w6-melody', week:6, d:'melody', title:'Answer it an octave up',
     goal:'Use register as a development tool.',
     steps:['Play your 2-bar phrase.',
            'Answer it with the same phrase an octave higher — but change one note.',
            'Then answer it an octave DOWN and notice how the mood changes.'],
     listen:'Up feels like a lift; down feels like a consequence.',
     capture:'The 8-bar version.',
     why:'Octave displacement is the cheapest, most reliable development move there is.',
     melody:'Changing exactly one note in the repeat is what stops it sounding lazy.'},
    {id:'w6-movement', week:6, d:'movement', title:'Sync versus free',
     goal:'Understand why synced modulation sits in a track and free modulation floats.',
     steps:['Set the LFO to a free rate, modulating cutoff. Play along to a metronome.',
            'Now switch the LFO to synced. Same amount.',
            'Alternate between them.'],
     listen:'Synced locks to the grid and disappears; free drifts and draws attention.',
     capture:'Both, back to back.',
     why:'This choice is most of the difference between "tight" and "psychedelic".'},
    {id:'w6-ear', week:6, d:'ear', title:'Find the tempo by ear',
     goal:'Stop relying on the display.',
     steps:['Play a track. Tap along. Guess the BPM.',
            'Set your MicroFreak arp to your guess and play along.',
            'Adjust until it locks. Check how close you were.'],
     listen:'Techno is usually 125–140. Your guesses should tighten over the month.',
     capture:'A short jam along to the track.',
     why:'Tempo estimation is a muscle and it is quick to build.'},
    {id:'w6-assemble', week:6, d:'assemble', title:'A piece with one surprise',
     goal:'Learn to place a single event.',
     steps:['Build a 90-second piece from this week.',
            'Put exactly ONE surprise in it — a silence, a jump, a new sound.',
            'Place it where it feels inevitable, not random.'],
     listen:'One well-placed event beats five scattered ones.',
     capture:'90s.',
     why:'Restraint in placement is a skill you can only learn by constraint.'},

    /* ---------------- WEEK 7 ---------------- */
    {id:'w7-groove', week:7, d:'groove', title:'Gate length as groove',
     goal:'Discover a rhythm control most people never touch.',
     steps:['Set Utility > Preset > Default gate length quite short.',
            'Play a pattern. Then set it long and play the identical pattern.',
            'Find the value where it feels best, then vary gates per step.'],
     listen:'Short gates feel nervous and precise; long gates feel heavy and connected.',
     capture:'60s at your favourite setting.',
     why:'Note length is half of rhythm and it is invisible on a piano roll.'},
    {id:'w7-sound', week:7, d:'sound', title:'The filter as an oscillator',
     goal:'Meet self-oscillation.',
     steps:['Turn Resonance up until the filter whistles on its own.',
            'Turn the oscillator level down or pick a quiet engine. The filter is now your voice.',
            'Play the keyboard — the filter tracks pitch.'],
     listen:'A pure sine tone from a filter with no oscillator behind it.',
     capture:'45s.',
     why:'Understanding self-oscillation demystifies resonance permanently.'},
    {id:'w7-melody', week:7, d:'melody', title:'The outsider becomes the hook',
     goal:'Build a melody around a single tense note.',
     steps:['In A minor, find G# — it belongs to harmonic minor, not natural minor.',
            'Write an 8-bar melody where G# appears exactly twice, in the same rhythmic place.',
            'Resolve it to A each time.'],
     listen:'The G# should feel like the melody is leaning, then landing.',
     capture:'The 8 bars.',
     why:'This exact tension is the core of the melodic-techno sound you like.',
     melody:'It is the same G# from the E major chord in your generated tracks. Now you are playing it deliberately.'},
    {id:'w7-movement', week:7, d:'movement', title:'Negative amounts',
     goal:'Use inverted modulation.',
     steps:['Patch Press → Cutoff with a NEGATIVE amount.',
            'Play. Pressing harder now CLOSES the filter.',
            'Then set Cycling Env → Pitch negative and hear the shape flip.'],
     listen:'Inverted modulation is unsettling in a useful way.',
     capture:'60s.',
     why:'The matrix encoder goes both directions and half its range is usually ignored.'},
    {id:'w7-ear', week:7, d:'ear', title:'Copy eight bars properly',
     goal:'Attempt a full transcription.',
     steps:['Pick 8 bars with a clear lead line.',
            'Get the rhythm first, then the contour, then the actual pitches.',
            'Accept 80% accuracy.'],
     listen:'Where your version diverges — those are your blind spots.',
     capture:'Your 8 bars.',
     why:'Transcription is the highest-yield ear exercise that exists.'},
    {id:'w7-assemble', week:7, d:'assemble', title:'Two voices',
     goal:'Handle more than one line at once.',
     steps:['Record a bass part. Then, over it, record a lead.',
            'Make sure they do not occupy the same rhythmic space.',
            'Two minutes.'],
     listen:'When one plays, the other should rest. That is arrangement.',
     capture:'2 min.',
     why:'The MicroFreak is one voice, so layering forces you to think in parts.'},

    /* ---------------- WEEK 8 ---------------- */
    {id:'w8-groove', week:8, d:'groove', title:'Sequence A and B together',
     goal:'Exploit the manual’s hidden feature.',
     steps:['Record a sequence in slot A with modulation lanes.',
            'Record a different sequence in slot B.',
            'Switch between them mid-phrase and listen to how the modulation carries over.'],
     listen:'Switching part-way gives you variants you never programmed.',
     capture:'90s of switching.',
     why:'The two sequences share modulation consequences — the manual flags this as a hidden feature.'},
    {id:'w8-sound', week:8, d:'sound', title:'Paraphony and its limits',
     goal:'Learn to write for four voices sharing one filter.',
     steps:['Play a four-note chord. Notice they all open and close together.',
            'Now play two notes held plus one moving line underneath.',
            'Compare which sounds better.'],
     listen:'Dense block chords turn to mush; a held pair with a moving voice sounds gorgeous.',
     capture:'Both.',
     why:'Understanding the limit is how you write parts that suit the instrument.'},
    {id:'w8-melody', week:8, d:'melody', title:'A counter-melody',
     goal:'Write a second line that serves the first.',
     steps:['Take your best melody. Record it.',
            'Write a second line that plays only in the gaps of the first.',
            'It should be simpler than the melody, not busier.'],
     listen:'If you notice the counter-melody more than the melody, simplify it.',
     capture:'Both lines together.',
     why:'Counterpoint is the oldest trick in music and it works in techno too.',
     melody:'Rule of thumb: the counter-line moves when the melody holds, and holds when the melody moves.'},
    {id:'w8-movement', week:8, d:'movement', title:'Modulate the modulator',
     goal:'Build a three-deep chain.',
     steps:['LFO → Cycling Env Rise.',
            'Cycling Env → Filter Cutoff.',
            'Press → LFO Rate (assignable slot). Now your hand changes how the whole chain behaves.'],
     listen:'Modulation that never repeats, controlled by one physical gesture.',
     capture:'2 min of one held chord.',
     why:'This is the deepest patch the MicroFreak supports without external gear.'},
    {id:'w8-ear', week:8, d:'ear', title:'Month 2 diagnostic',
     goal:'Test what modulation you can now identify.',
     steps:['Play three tracks. For each, name every moving element within 30 seconds.',
            'Then recreate the most interesting one.'],
     listen:'Compare to Week 5. You should hear more, faster.',
     capture:'One recreation.',
     why:'Diagnostics tell you what the next month should contain.'},
    {id:'w8-assemble', week:8, d:'assemble', title:'Month 2 checkpoint',
     goal:'Produce the month’s deliverable.',
     steps:['Two minutes where nothing repeats identically.',
            'Modulation does the variation. MicroFreak only, still.',
            'Then listen to Month 1’s checkpoint next to it.'],
     listen:'Month 2 should sound alive where Month 1 sounded static.',
     capture:'The 2-minute checkpoint.',
     why:'You now have the sound-design vocabulary. Month 3 is about structure.'},

    /* ================= MONTH 3 — STRUCTURE ================= */
    /* ---------------- WEEK 9 ---------------- */
    {id:'w9-groove', week:9, d:'groove', title:'Get it into Ableton properly',
     goal:'Set up the recording chain once, correctly.',
     steps:['MIDI track with External Instrument: MIDI To = MicroFreak Ch.1, Audio From = your interface input.',
            'Record 8 bars of a groove as AUDIO onto a new audio track.',
            'Check the timing lines up with the grid.'],
     listen:'Any latency. External Instrument compensates; if it still drifts, adjust track delay.',
     capture:'8 bars of clean audio.',
     why:'Remember the MicroFreak’s USB carries MIDI but not audio — you need both cables.'},
    {id:'w9-sound', week:9, d:'sound', title:'Resample and mangle',
     goal:'Treat your own recording as raw material.',
     steps:['Take the audio you just recorded.',
            'Chop it, reverse a slice, pitch one down an octave.',
            'Build a new 4-bar loop entirely from those pieces.'],
     listen:'How different your own sound becomes when treated as a sample.',
     capture:'The 4-bar loop.',
     why:'Resampling is how one monophonic synth becomes a whole track.'},
    {id:'w9-melody', week:9, d:'melody', title:'Write to a progression',
     goal:'Compose against harmony instead of in a vacuum.',
     steps:['Put a four-chord pad in Ableton: Am – F – C – E.',
            'Play a MicroFreak melody over it. Land on a chord tone at each change.',
            'Then deliberately land on a NON-chord tone once and resolve it.'],
     listen:'Landing on chord tones feels settled; the one outsider is where the feeling is.',
     capture:'8 bars over the progression.',
     why:'Melody and harmony are a conversation. Month 1–2 only taught you one side.',
     melody:'Over the E chord, G# is a chord tone — that is why it sounds right rather than wrong.'},
    {id:'w9-movement', week:9, d:'movement', title:'Automate the synth from Ableton',
     goal:'Drive the hardware from the DAW.',
     steps:['On the MIDI track, add an automation lane sending CC 23 (filter cutoff).',
            'Draw an 8-bar rise.',
            'Play it back and watch the MicroFreak respond.'],
     listen:'A perfectly repeatable filter sweep you did not have to perform.',
     capture:'The 8 bars.',
     why:'Note: knob moves from external controllers cannot be recorded INTO the MicroFreak sequencer — automation has to live in Ableton.'},
    {id:'w9-ear', week:9, d:'ear', title:'Map an arrangement',
     goal:'Hear structure at track scale.',
     steps:['Play a full track with a timer. Write down every section change with its timestamp.',
            'Mark where elements enter and leave.',
            'Count the bars of each section.'],
     listen:'Almost everything happens in 8, 16 or 32-bar blocks.',
     capture:'Your written map (photograph it).',
     why:'You cannot arrange until you can hear arrangement.'},
    {id:'w9-assemble', week:9, d:'assemble', title:'Two sections that differ',
     goal:'Make a change, not just a loop.',
     steps:['Build a 16-bar section. Then build a second 16-bar section from the same material.',
            'The second must be clearly different — fewer elements, or one big addition.',
            'Play them back to back.'],
     listen:'The moment of change should be satisfying, not jarring.',
     capture:'32 bars.',
     why:'A track is sections in relation to each other. This is the smallest version of that.'},

    /* ---------------- WEEK 10 ---------------- */
    {id:'w10-groove', week:10, d:'groove', title:'Build the drums as layers',
     goal:'Separate the kit so you can arrange it.',
     steps:['Put kick, hats and percussion on SEPARATE tracks in Ableton.',
            'Build a 16-bar section where the hats enter at bar 5 and the percussion at bar 9.',
            'Nothing else changes.'],
     listen:'Staggered entrances create momentum with no new ideas.',
     capture:'16 bars.',
     why:'Separate tracks are what make arrangement possible at all.'},
    {id:'w10-sound', week:10, d:'sound', title:'Three layers that do not fight',
     goal:'Learn frequency space.',
     steps:['Make a low part, a mid part and a high part from the MicroFreak.',
            'Play them together. If it sounds muddy, filter the mid part’s lows out.',
            'Each layer should own a range.'],
     listen:'Mud is almost always two things in the same octave.',
     capture:'The three layers together.',
     why:'Arrangement is as much about frequency as time.'},
    {id:'w10-melody', week:10, d:'melody', title:'Where the hook enters',
     goal:'Learn placement.',
     steps:['Take a 32-bar section with a groove running.',
            'Try the melody entering at bar 1, then bar 9, then bar 17.',
            'Pick the one that feels earned.'],
     listen:'Too early and it is wallpaper; too late and you lose the listener.',
     capture:'The best version.',
     why:'When a hook arrives matters as much as what it is.',
     melody:'Melodic techno usually withholds the main theme for 60–90 seconds. Delay is a technique.'},
    {id:'w10-movement', week:10, d:'movement', title:'Automation curves',
     goal:'Move beyond straight lines.',
     steps:['Draw a filter automation across 16 bars as a straight ramp. Listen.',
            'Now curve it so most of the movement happens in the last 4 bars.',
            'Compare.'],
     listen:'Curved automation feels like a build; linear feels mechanical.',
     capture:'Both versions.',
     why:'The shape of a build is what makes it exciting or boring.'},
    {id:'w10-ear', week:10, d:'ear', title:'Steal a transition',
     goal:'Collect specific moves.',
     steps:['Find one transition you love — into a drop, out of a breakdown.',
            'Work out exactly what happens: what drops out, what enters, is there silence?',
            'Rebuild that transition with your own material.'],
     listen:'Most great transitions involve removing things, not adding them.',
     capture:'Your version of the transition.',
     why:'Transitions are learnable as discrete moves you can bank.'},
    {id:'w10-assemble', week:10, d:'assemble', title:'Intro, build, drop',
     goal:'Assemble the fundamental three-part shape.',
     steps:['16 bars intro, 16 bars build, 32 bars drop.',
            'Use only material you already have.',
            'The build must remove something as well as add.'],
     listen:'The drop should feel like a release of pressure the build created.',
     capture:'The 64 bars.',
     why:'This shape underlies most electronic music. Get it in your hands.'},

    /* ---------------- WEEK 11 ---------------- */
    {id:'w11-groove', week:11, d:'groove', title:'The drop is subtraction',
     goal:'Resist the urge to add.',
     steps:['Take your busiest section.',
            'Make the drop by REMOVING two elements, not adding any.',
            'Compare with a version where you added instead.'],
     listen:'Space reads as power. Density reads as noise.',
     capture:'Both versions.',
     why:'Beginners add at the drop; experienced producers take away.'},
    {id:'w11-sound', week:11, d:'sound', title:'Make room for the kick',
     goal:'Understand the low end.',
     steps:['Play your bass and kick together. Notice the collision.',
            'Either sidechain the bass to the kick, or shorten the bass notes so they sit between kicks.',
            'Try both.'],
     listen:'The kick should feel like it has room to breathe.',
     capture:'Both approaches.',
     why:'The kick–bass relationship is most of what makes a track feel professional.'},
    {id:'w11-melody', week:11, d:'melody', title:'The breakdown restatement',
     goal:'Use augmentation as an emotional device.',
     steps:['Take your main theme.',
            'In a breakdown section, play it at HALF SPEED as long sustained notes, with drums gone.',
            'Bring the drums back after it.'],
     listen:'The same melody becomes emotional when slowed and exposed.',
     capture:'The breakdown plus re-entry.',
     why:'This is the single most reliable emotional move in melodic techno.',
     melody:'Augmentation — same notes, longer values. It is what your generated track does at bar 113.'},
    {id:'w11-movement', week:11, d:'movement', title:'One long sweep',
     goal:'Automate at track scale.',
     steps:['Draw a single filter automation that spans 32 bars.',
            'Add a second automation on resonance that peaks in the middle.',
            'Listen to the whole thing without touching anything.'],
     listen:'Slow, long automation is felt rather than noticed. That is the goal.',
     capture:'The 32 bars.',
     why:'Short automation is an effect; long automation is structure.'},
    {id:'w11-ear', week:11, d:'ear', title:'Why does this section work?',
     goal:'Move from what to why.',
     steps:['Pick one 30-second stretch of a track you love.',
            'Write three sentences on WHY it works — not what is in it.',
            'Apply one of those three reasons to your own material.'],
     listen:'Push past "it sounds good" to a mechanism.',
     capture:'Your applied version.',
     why:'Naming the mechanism is what makes it reusable.'},
    {id:'w11-assemble', week:11, d:'assemble', title:'Add the breakdown',
     goal:'Extend to a four-part shape.',
     steps:['Take last week’s intro/build/drop.',
            'Add a breakdown after the drop, using the augmented theme.',
            'Then rebuild into a second drop.'],
     listen:'The second drop should hit harder purely because of what preceded it.',
     capture:'The full arrangement so far.',
     why:'You now have the complete skeleton of a track.'},

    /* ---------------- WEEK 12 ---------------- */
    {id:'w12-groove', week:12, d:'groove', title:'Fills and micro-transitions',
     goal:'Smooth the seams.',
     steps:['At each section change, add a one-bar fill: a drum roll, a reversed sample, a silence.',
            'Try one section change with NOTHING — just a hard cut.',
            'Keep whichever is better per transition.'],
     listen:'Not every seam needs a fill. Some want a cliff edge.',
     capture:'Two transitions.',
     why:'Fills are punctuation. Overusing them reads as nervousness.'},
    {id:'w12-sound', week:12, d:'sound', title:'The outro',
     goal:'Learn to end.',
     steps:['Take your arrangement and write 16 bars of ending.',
            'Remove elements in reverse order of how they entered.',
            'End on the element you started with.'],
     listen:'A good ending feels like the track completing a circle.',
     capture:'The outro.',
     why:'Most unfinished tracks are unfinished because nobody wrote an ending.'},
    {id:'w12-melody', week:12, d:'melody', title:'The whole melodic arc',
     goal:'Plan a theme across a full track.',
     steps:['Map where your theme appears: first hint, full statement, breakdown version, final version.',
            'Make each appearance different — register, timbre, or accompaniment.',
            'Four appearances minimum.'],
     listen:'The listener should recognise it every time and never be bored by it.',
     capture:'A note of your map plus the final version.',
     why:'One idea developed four ways beats four ideas stated once.',
     melody:'This is motif development at track scale — the thing that makes music feel composed.'},
    {id:'w12-movement', week:12, d:'movement', title:'Everything moving',
     goal:'Layer automation without chaos.',
     steps:['Add slow automation to three different elements across your arrangement.',
            'Make sure they peak at DIFFERENT times.',
            'Listen for whether it feels alive or seasick.'],
     listen:'Staggered peaks feel organic; simultaneous peaks feel like a mistake.',
     capture:'The arrangement with automation.',
     why:'Automation is arrangement by another name.'},
    {id:'w12-ear', week:12, d:'ear', title:'Month 3 diagnostic',
     goal:'Test structural hearing.',
     steps:['Play an unfamiliar track. Predict where the next section change will come.',
            'Check yourself. Repeat with two more tracks.'],
     listen:'You should be right most of the time now.',
     capture:'A note on your hit rate.',
     why:'Predicting structure means you have internalised it.'},
    {id:'w12-assemble', week:12, d:'assemble', title:'Month 3 checkpoint',
     goal:'Produce a real arrangement.',
     steps:['A three-minute arrangement with intro, build, drop, breakdown and outro.',
            'It does not need to be mixed. It needs to be STRUCTURED.',
            'Listen next to Month 2’s checkpoint.'],
     listen:'Month 3 should have shape where Month 2 had texture.',
     capture:'The 3-minute arrangement.',
     why:'Everything from here is finishing, not building.'},

    /* ================= MONTH 4 — FINISH ================= */
    /* ---------------- WEEK 13 ---------------- */
    {id:'w13-groove', week:13, d:'groove', title:'Audit and choose',
     goal:'Pick the one thing you will finish.',
     steps:['Listen to every capture from three months.',
            'Shortlist three. Then pick ONE. Write down why.',
            'Everything else is now off the table for four weeks.'],
     listen:'Trust the one you keep returning to, not the cleverest one.',
     capture:'A note naming the track and why.',
     why:'Not choosing is the main reason producers never finish anything.'},
    {id:'w13-sound', week:13, d:'sound', title:'Commit the palette',
     goal:'Stop sound-designing.',
     steps:['List every sound your chosen track uses.',
            'Fix each one. Save the presets. Record any hardware parts to audio.',
            'No new sounds from here.'],
     listen:'Whether any element is obviously weaker than the rest. Fix that one only.',
     capture:'All parts as audio.',
     why:'Committing to audio removes the temptation to keep tweaking forever.'},
    {id:'w13-melody', week:13, d:'melody', title:'Commit the theme',
     goal:'Finalise the tune.',
     steps:['Play your theme ten times. Change nothing.',
            'Note any moment that irritates you and fix ONLY that.',
            'Then declare it done.'],
     listen:'Irritation on repeat listening is real feedback. Mild boredom is not.',
     capture:'The final theme.',
     why:'A finished melody is one you have stopped editing, not a perfect one.'},
    {id:'w13-movement', week:13, d:'movement', title:'Commit the automation',
     goal:'Lock the movement.',
     steps:['Go through your arrangement and finalise every automation lane.',
            'Delete any automation that you cannot hear.',
            'Keep what survives.'],
     listen:'If removing it makes no difference, it was decoration.',
     capture:'The locked arrangement.',
     why:'Invisible automation is just CPU and confusion.'},
    {id:'w13-ear', week:13, d:'ear', title:'Pick a reference',
     goal:'Give yourself a target.',
     steps:['Choose ONE released track your piece should sit beside.',
            'Play 30 seconds of it, then 30 of yours.',
            'Write the three biggest differences.'],
     listen:'Usually: low end, loudness, and how much space theirs has.',
     capture:'The three differences.',
     why:'A reference converts vague dissatisfaction into a list.'},
    {id:'w13-assemble', week:13, d:'assemble', title:'Full pass, top to bottom',
     goal:'Hear it whole.',
     steps:['Listen to the entire track without stopping. No edits allowed.',
            'Write down timestamps where your attention drifted.',
            'That list is next week’s work.'],
     listen:'Attention drift is the most honest signal you have.',
     capture:'The timestamp list.',
     why:'You cannot fix a track you have only ever heard in eight-bar loops.'},

    /* ---------------- WEEK 14 ---------------- */
    {id:'w14-groove', week:14, d:'groove', title:'Fix the boring bars',
     goal:'Act on last week’s list.',
     steps:['Take the first timestamp where attention drifted.',
            'Fix it by REMOVING or SHORTENING, not adding.',
            'Repeat for the next two timestamps.'],
     listen:'Most boring sections are simply too long.',
     capture:'The revised arrangement.',
     why:'Cutting length is the highest-yield edit in arranging.'},
    {id:'w14-sound', week:14, d:'sound', title:'Fix the weakest element',
     goal:'Raise the floor, not the ceiling.',
     steps:['Identify the one sound that feels amateur next to your reference.',
            'Replace or reprocess only that.',
            'Do not touch anything else.'],
     listen:'A track is judged by its weakest element, not its best.',
     capture:'Before and after.',
     why:'Targeted fixes beat general polishing.'},
    {id:'w14-melody', week:14, d:'melody', title:'Does the hook land?',
     goal:'Test memorability.',
     steps:['Play the track for someone, or leave it a day.',
            'Can you hum the theme afterwards without hearing it?',
            'If not, simplify it — fewer notes, more repetition.'],
     listen:'Hummable usually means fewer notes than you think.',
     capture:'The simplified theme if you changed it.',
     why:'If you cannot recall it, nobody else will.',
     melody:'When in doubt, repeat the first half and change only the ending.'},
    {id:'w14-movement', week:14, d:'movement', title:'Transitions pass',
     goal:'Smooth every seam.',
     steps:['Solo each section change and listen only to the two bars either side.',
            'Fix any that feel abrupt for the wrong reason.',
            'Leave the deliberate hard cuts alone.'],
     listen:'Seams are where amateur arrangements reveal themselves.',
     capture:'The revised arrangement.',
     why:'Nobody notices good transitions, which is the point.'},
    {id:'w14-ear', week:14, d:'ear', title:'A/B against the reference',
     goal:'Compare honestly.',
     steps:['Level-match your track to the reference so both are equally loud.',
            'Switch between them every 15 seconds.',
            'Note what still differs.'],
     listen:'Level-matching is essential — louder always sounds better and it is a trap.',
     capture:'Your notes.',
     why:'Unmatched A/B tells you nothing except which is louder.'},
    {id:'w14-assemble', week:14, d:'assemble', title:'Second full pass',
     goal:'Re-test after edits.',
     steps:['Full listen, no stopping, new timestamp list.',
            'The list should be shorter than last week’s.'],
     listen:'Shrinking lists mean you are converging.',
     capture:'The new list.',
     why:'Finishing is measurable if you keep the list.'},

    /* ---------------- WEEK 15 ---------------- */
    {id:'w15-groove', week:15, d:'groove', title:'Kick and bass, alone',
     goal:'Get the foundation right.',
     steps:['Solo the kick and bass. Listen for a full minute.',
            'They should feel like one instrument, not two fighting.',
            'Adjust levels and note lengths until they lock.'],
     listen:'If you cannot get it right soloed, no amount of mixing will fix it later.',
     capture:'The soloed pair.',
     why:'Everything else sits on this.'},
    {id:'w15-sound', week:15, d:'sound', title:'Balance, not effects',
     goal:'Mix with the faders first.',
     steps:['Pull every fader down. Bring them up one at a time, in order of importance.',
            'Stop when it sounds balanced. Do not add EQ or compression yet.',
            'Only then fix anything still wrong.'],
     listen:'Most mix problems are level problems wearing a disguise.',
     capture:'The balanced mix.',
     why:'Faders first is the oldest and most reliable mixing advice there is.'},
    {id:'w15-melody', week:15, d:'melody', title:'Is the theme loud enough?',
     goal:'Check the hook sits right.',
     steps:['Listen at very low volume. Can you still hear the melody?',
            'If it disappears, it is too quiet or occupying a crowded frequency range.',
            'Fix by level or by moving its register.'],
     listen:'At low volume you only hear what matters. That is a useful filter.',
     capture:'The adjusted mix.',
     why:'The quiet-listening test is free and brutally honest.'},
    {id:'w15-movement', week:15, d:'movement', title:'Final automation sweep',
     goal:'Last movement pass.',
     steps:['Add volume automation to smooth any moment that jumps out.',
            'Check the intro and outro fade sensibly.',
            'Then stop touching automation.'],
     listen:'Small level rides fix more than plugins do.',
     capture:'Final arrangement.',
     why:'Automation is the last thing to finish because everything else must be settled.'},
    {id:'w15-ear', week:15, d:'ear', title:'Different speakers',
     goal:'Test outside your bubble.',
     steps:['Play the track on your phone speaker, in headphones, and in a car if possible.',
            'Note anything that falls apart on any system.',
            'Fix only what is broken everywhere.'],
     listen:'Phone speakers expose weak midrange; headphones expose the low end.',
     capture:'Your notes.',
     why:'A mix that only works on your setup is not finished.'},
    {id:'w15-assemble', week:15, d:'assemble', title:'Third full pass',
     goal:'Converge.',
     steps:['Full listen. New list. It should now be very short.',
            'Fix only what is on it.'],
     listen:'If the list is empty, you are done and should stop.',
     capture:'The list.',
     why:'Knowing when to stop is the final skill.'},

    /* ---------------- WEEK 16 ---------------- */
    {id:'w16-groove', week:16, d:'groove', title:'Final rhythm check',
     goal:'Last look at the foundation.',
     steps:['Listen once focusing only on drums and bass.',
            'Fix anything genuinely wrong. Otherwise leave it.'],
     listen:'Resist re-opening settled decisions.',
     capture:'—',
     why:'Late-stage tinkering usually makes things worse.'},
    {id:'w16-sound', week:16, d:'sound', title:'Rest your ears',
     goal:'Get distance.',
     steps:['Do not listen to the track at all today.',
            'Listen to other music instead.'],
     listen:'Nothing. That is the exercise.',
     capture:'—',
     why:'Ear fatigue makes you fix things that were never broken.'},
    {id:'w16-melody', week:16, d:'melody', title:'Fresh ears on the theme',
     goal:'Final judgement.',
     steps:['Listen once, after a day away.',
            'If the theme still works, it is done.'],
     listen:'First impression after a break is the most reliable one you will get.',
     capture:'—',
     why:'Distance is the only real quality control available to you.'},
    {id:'w16-movement', week:16, d:'movement', title:'Export and check',
     goal:'Technical finish.',
     steps:['Export the track. Listen to the EXPORTED file, not the session.',
            'Check for clipping, silence at the start, and a clean ending.'],
     listen:'Exports sometimes differ from the session. Always check.',
     capture:'The exported file.',
     why:'More tracks are ruined at export than at any other stage.'},
    {id:'w16-ear', week:16, d:'ear', title:'Play it to one person',
     goal:'Meet an audience.',
     steps:['Play it for someone whose taste you respect.',
            'Say nothing. Watch their face.',
            'Ask one question afterwards: "where did you lose interest?"'],
     listen:'Their attention tells you more than their compliments.',
     capture:'What they said.',
     why:'Music is finished when it meets a listener.'},
    {id:'w16-assemble', week:16, d:'assemble', title:'Ship it',
     goal:'Finish. Actually finish.',
     steps:['Put it somewhere public, or send it to three people.',
            'Then listen to Month 1 Week 1 and this, back to back.',
            'Start again at Week 1 with everything you now know.'],
     listen:'Four months of fifteen minutes is roughly thirty hours. It should be obvious.',
     capture:'The finished track.',
     why:'The loop closes: shipping is what turns practice into a body of work.'},
  ],
};
