/* farsi.js — the Conversational Farsi (Persian) deck for /anki.
 *
 * Registered in anki/decks/index.js. Read the header of greek.js for the editing
 * rules: append only, never rename or reuse an id, bump version and updated,
 * run `node anki/deck.test.js` before committing.
 *
 * Spoken Tehrani Persian, the way people actually talk (می‌خوام not می‌خواهم),
 * with the written form in a note where it differs.
 * MEMOS FOR FARSI: lean on Indo-European cousins (do/two, se/three, haft/seven,
 *   garm/warm, to/thou, nām/name), French and Arabic loans (mersi, kārt, salām), the
 *   ezāfe -e, the mi- present marker, the endings (-am I, -i you, -e he/she/it, -im we,
 *   -id you pl., -an they), na-/ne- for not, and noun + kardan/zadan verbs.
 *
 * TRANSLITERATION: ā = long "aa" (آب → āb), a = short (like "cat"), e, o, i, u.
 * kh (خ), gh (غ/ق), sh, ch, zh (ژ), ' for ع/ء. The ezāfe link is written -e.
 * Fields: id, term (Persian script), tr, en, tags, note?, ex?{term,tr,en}
 */
window.DECKS = window.DECKS || {};
window.DECKS.farsi = {
  id: 'farsi',
  name: 'Conversational Farsi',
  version: 2,
  updated: '2026-10-01',

  notes: [
    /* ---------------- GREETINGS ---------------- */
    {id:'greet-salam', term:'سلام', tr:'salām', en:'Hello / Hi', memo:'salām = peace, the same root as Arabic salaam and Hebrew shalom. Saying hello is wishing peace.',
     parts:[{t:'سلام', tr:'salām', m:'peace (hello)'}],
     tags:['greetings']},
    {id:'greet-sobh-bekheir', term:'صبح بخیر', tr:'sobh bekheir', en:'Good morning', memo:'sobh = morning + be = to + kheir = goodness: \'morning to the good\'. Same shape as shab bekheir.',
     parts:[{t:'صبح', tr:'sobh', m:'morning'}, {t:'بخیر', tr:'bekheir', m:'to goodness, be well'}],
     tags:['greetings']},
    {id:'greet-shab-bekheir', term:'شب بخیر', tr:'shab bekheir', en:'Good evening / Good night', memo:'shab = night + bekheir = to the good. Swap sobh (morning) for shab (night) and you have both greetings.',
     parts:[{t:'شب', tr:'shab', m:'night, evening'}, {t:'بخیر', tr:'bekheir', m:'to goodness'}],
     tags:['greetings'],
     note:'Used for both.'},
    {id:'greet-khodahafez', term:'خداحافظ', tr:'khodāhāfez', en:'Goodbye', memo:'khodā = God + hāfez = keeper, protector (the poet Hafez took his name from \'keeper of the Quran\'). \'God keep you.\'',
     parts:[{t:'خدا', tr:'khodā', m:'God'}, {t:'حافظ', tr:'hāfez', m:'keeper, protector'}],
     tags:['greetings'],
     note:'Literally "God protect you". Casual: خدافظ (khodāfez).'},
    {id:'greet-chetori', term:'چطوری؟', tr:'chetori?', en:'How are you? (informal)', memo:'chetor = how + -i = you are: \'how are you?\' in one word. The -i ending = you.',
     parts:[{t:'چطور', tr:'chetor', m:'how'}, {t:'ی', tr:'i', m:'you are (ending)'}, {t:'؟', tr:'?', m:'Persian question mark'}],
     tags:['greetings']},
    {id:'greet-shoma-chetorid', term:'شما چطورید؟', tr:'shomā chetorid?', en:'How are you? (formal)', memo:'shomā = you (formal) + chetor + -id = you (plural) are. -i for a friend, -id for respect.',
     parts:[{t:'شما', tr:'shomā', m:'you (formal)'}, {t:'چطور', tr:'chetor', m:'how'}, {t:'ید', tr:'id', m:'you are (plural, formal)'}],
     tags:['greetings']},
    {id:'greet-khubam', term:'خوبم، مرسی', tr:'khubam, mersi', en:'I\'m fine, thanks', memo:'khub = good + -am = I am: \'I\'m good\'. mersi = thanks, straight from French merci. -am is the I ending everywhere.',
     parts:[{t:'خوب', tr:'khub', m:'good'}, {t:'م', tr:'am', m:'I am (ending)'}, {t:'مرسی', tr:'mersi', m:'thanks (French merci)'}],
     tags:['greetings'],
     ex:{term:'خوبم، مرسی. تو چطوری؟', tr:'khubam, mersi. to chetori?', en:'I\'m fine, thanks. And you?'}},
    {id:'greet-khosh-amadid', term:'خوش آمدید', tr:'khosh āmadid', en:'Welcome', memo:'khosh = happy, pleasant + āmadid = you came: \'you came pleasantly\' = welcome. Like English \'well-come\'.',
     parts:[{t:'خوش', tr:'khosh', m:'pleasant, happy'}, {t:'آمد', tr:'āmad', m:'came'}, {t:'ید', tr:'id', m:'you (plural, formal)'}],
     tags:['greetings']},
    {id:'greet-khoshbakhtam', term:'خوشبختم', tr:'khoshbakhtam', en:'Nice to meet you', memo:'khosh = happy + bakht = fortune, luck + -am = I am: \'I am fortunate\' to meet you.',
     parts:[{t:'خوش', tr:'khosh', m:'happy'}, {t:'بخت', tr:'bakht', m:'fortune, luck'}, {t:'م', tr:'am', m:'I am'}],
     tags:['greetings']},
    {id:'greet-felan', term:'فعلاً', tr:'fe\'lan', en:'See you (for now)', memo:'fe\'lan = for now, from fe\'l = action, the current state (Arabic loan). \'For now\' = see you.',
     parts:[{t:'فعلاً', tr:'fe\'lan', m:'for now, currently'}],
     tags:['greetings']},
    {id:'greet-be-salamat', term:'به سلامت', tr:'be salāmat', en:'Safe travels / Goodbye', memo:'be = to, with + salāmat = health, safety (the salām root): \'in safety\', safe travels.',
     parts:[{t:'به', tr:'be', m:'to, with'}, {t:'سلامت', tr:'salāmat', m:'health, safety'}],
     tags:['greetings'],
     note:'Said to the person who is leaving.'},
    {id:'greet-esmam', term:'اسمم ... است', tr:'esmam ... ast', en:'My name is ...', memo:'esm = name (the Arabic ism) + -am = my; ast = is. nām is the native Persian word, a cousin of English \'name\'.',
     parts:[{t:'اسم', tr:'esm', m:'name'}, {t:'م', tr:'am', m:'my (suffix)'}, {t:'...', tr:'...', m:'the name'}, {t:'است', tr:'ast', m:'is'}],
     tags:['greetings'],
     note:'Spoken: اسمم سامه (esmam Sām-e).',
     ex:{term:'اسمم سام است.', tr:'esmam Sām ast.', en:'My name is Sam.'}},
    {id:'greet-esmet-chie', term:'اسمت چیه؟', tr:'esmet chie?', en:'What\'s your name? (informal)', memo:'esm = name + -et = your; chi = what + -e = is: \'your name is what?\'. -am my, -et your.',
     parts:[{t:'اسم', tr:'esm', m:'name'}, {t:'ت', tr:'et', m:'your (suffix)'}, {t:'چی', tr:'chi', m:'what'}, {t:'ه', tr:'e', m:'is (spoken)'}],
     tags:['greetings'],
     note:'Formal: اسم شما چیست؟ (esm-e shomā chist?)'},

    /* ---------------- POLITENESS ---------------- */
    {id:'pol-mersi', term:'مرسی', tr:'mersi', en:'Thanks', memo:'mersi = merci. French, borrowed whole. Iran\'s everyday thanks.',
     parts:[{t:'مرسی', tr:'mersi', m:'thanks (French)'}],
     tags:['politeness'],
     note:'Borrowed from French and used all day.'},
    {id:'pol-mamnun', term:'ممنون', tr:'mamnun', en:'Thank you', memo:'mamnun = grateful, literally \'obliged\' (Arabic root). Think \'I\'m in your debt, man-noon\'.',
     parts:[{t:'ممنون', tr:'mamnun', m:'grateful, obliged'}],
     tags:['politeness'],
     ex:{term:'خیلی ممنون.', tr:'kheili mamnun.', en:'Thank you very much.'}},
    {id:'pol-khahesh-mikonam', term:'خواهش می‌کنم', tr:'khāhesh mikonam', en:'You\'re welcome / Please', memo:'khāhesh = request (khāstan = to want, the mikhām root) + mikonam = I do: \'I make a request\', please / you\'re welcome.',
     parts:[{t:'خواهش', tr:'khāhesh', m:'request, plea'}, {t:'می', tr:'mi', m:'present marker'}, {t:'کن', tr:'kon', m:'do'}, {t:'م', tr:'am', m:'I'}],
     tags:['politeness'],
     note:'The reply to thanks, and a polite "please".'},
    {id:'pol-lotfan', term:'لطفاً', tr:'lotfan', en:'Please', memo:'lotf = kindness, grace + -an = -ly: \'kindly\'. Think \'lots of kindness\'.',
     parts:[{t:'لطف', tr:'lotf', m:'kindness, favour'}, {t:'اً', tr:'an', m:'-ly (adverb ending)'}],
     tags:['politeness'],
     ex:{term:'لطفاً آب.', tr:'lotfan āb.', en:'Water, please.'}},
    {id:'pol-bebakhshid', term:'ببخشید', tr:'bebakhshid', en:'Excuse me / Sorry', memo:'be- = do! + bakhsh = forgive, grant (bakhshidan) + -id = you (plural): \'forgive me\'. Think \'be back, excuse me\'.',
     parts:[{t:'ب', tr:'be', m:'command prefix'}, {t:'بخش', tr:'bakhsh', m:'forgive, grant'}, {t:'ید', tr:'id', m:'you (plural, formal)'}],
     tags:['politeness'],
     note:'For getting attention and for apologies.'},
    {id:'pol-moteassefam', term:'متأسفم', tr:'mote\'assefam', en:'I\'m sorry (regret)', memo:'mote\'assef = regretful (Arabic root asaf = sorrow) + -am = I am. \'I am sorry\' with real regret.',
     parts:[{t:'متأسف', tr:'mote\'assef', m:'regretful, sorry'}, {t:'م', tr:'am', m:'I am'}],
     tags:['politeness']},
    {id:'pol-befarmaid', term:'بفرمایید', tr:'befarmāid', en:'Please (go ahead / here you are / come in)', memo:'farmudan = to command, do (polite); be- + farmā + -id = \'please command\': go ahead, here you are, come in.',
     parts:[{t:'ب', tr:'be', m:'command prefix'}, {t:'فرما', tr:'farmā', m:'command, deign to'}, {t:'یید', tr:'id', m:'you (plural, formal)'}],
     tags:['politeness'],
     note:'The host\'s word for everything.'},
    {id:'pol-ghabel-nadare', term:'قابل نداره', tr:'ghābel nadāre', en:'It\'s nothing (shopkeeper refusing payment)', memo:'ghābel = worth + na- = not + dāre = it has: \'it has no worth\', i.e. don\'t pay. The tārof dance; insist and pay.',
     parts:[{t:'قابل', tr:'ghābel', m:'worth, worthy'}, {t:'ن', tr:'na', m:'not'}, {t:'دار', tr:'dār', m:'have'}, {t:'ه', tr:'e', m:'it (spoken 3rd person)'}],
     tags:['politeness','shopping'],
     note:'Tārof ritual. You insist and pay anyway.'},
    {id:'pol-dast-shoma-dard-nakone', term:'دست شما درد نکنه', tr:'dast-e shomā dard nakone', en:'Thank you (for effort)', memo:'dast = hand (your dast did the work) + -e shomā = of you + dard = pain + na-kone = may it not do: \'may your hand not hurt\'.',
     parts:[{t:'دست', tr:'dast', m:'hand'}, {t:'ـِ', tr:'-e', m:'of (ezāfe link)'}, {t:'شما', tr:'shomā', m:'you (formal)'}, {t:'درد', tr:'dard', m:'pain'}, {t:'نکنه', tr:'nakone', m:'may it not do'}],
     tags:['politeness'],
     note:'Literally "may your hand not hurt".'},
    {id:'pol-be-salamati', term:'به سلامتی', tr:'be salāmati', en:'Cheers / To your health', memo:'be = to + salāmati = health (salām again, with -i making a noun). \'To health!\'',
     parts:[{t:'به', tr:'be', m:'to'}, {t:'سلامت', tr:'salāmat', m:'health'}, {t:'ی', tr:'i', m:'noun ending (-ness)'}],
     tags:['politeness','food']},
    {id:'pol-chashm', term:'چشم', tr:'chashm', en:'Certainly / Will do', memo:'chashm = eye. Saying \'eye\' means \'on my eyes\', I\'ll do it gladly. Think \'chasm\' with a soft sh.',
     parts:[{t:'چشم', tr:'chashm', m:'eye (= will do)'}],
     tags:['politeness'],
     note:'Literally "eye". The polite yes to a request.'},

    /* ---------------- BASICS ---------------- */
    {id:'bas-bale', term:'بله', tr:'bale', en:'Yes', memo:'bale = yes (formal). Think \'ballet, yes\'. Friends say āre.',
     parts:[{t:'بله', tr:'bale', m:'yes'}],
     tags:['basics'],
     note:'Casual: آره (āre).'},
    {id:'bas-na', term:'نه', tr:'na', en:'No', memo:'na = no. The same na- that negates verbs: na-dāram = I don\'t have. Think \'nah\'.',
     parts:[{t:'نه', tr:'na', m:'no'}],
     tags:['basics'],
     note:'Polite: نخیر (nakheir).'},
    {id:'bas-bashe', term:'باشه', tr:'bāshe', en:'OK', memo:'bāshe = \'let it be\', from budan = to be: OK, fine. Think \'bah, sure\'.',
     parts:[{t:'باش', tr:'bāsh', m:'be (subjunctive of budan)'}, {t:'ه', tr:'e', m:'it (3rd person)'}],
     tags:['basics']},
    {id:'bas-khub', term:'خوب', tr:'khub', en:'Good / Well', memo:'khub = good. The khu of khubam. Think a throaty \'hoob\'.',
     parts:[{t:'خوب', tr:'khub', m:'good, well'}],
     tags:['basics']},
    {id:'bas-shayad', term:'شاید', tr:'shāyad', en:'Maybe', memo:'shāyad = maybe, from shāyestan = to be fitting: \'it may fit\'. Think \'shy, add maybe\'.',
     parts:[{t:'شاید', tr:'shāyad', m:'maybe, perhaps'}],
     tags:['basics']},
    {id:'bas-hatman', term:'حتماً', tr:'hatman', en:'Certainly / Of course', memo:'hatm = certainty (Arabic) + -an = -ly: certainly. Same -an as lotfan.',
     parts:[{t:'حتم', tr:'hatm', m:'certainty'}, {t:'اً', tr:'an', m:'-ly'}],
     tags:['basics']},
    {id:'bas-nemidunam', term:'نمی‌دونم', tr:'nemidunam', en:'I don\'t know', memo:'ne- = not + mi- = present + dun = know (dānestan) + -am = I: \'I don\'t know\'. ne-mi- is the negative present.',
     parts:[{t:'ن', tr:'ne', m:'not'}, {t:'می', tr:'mi', m:'present marker'}, {t:'دون', tr:'dun', m:'know'}, {t:'م', tr:'am', m:'I'}],
     tags:['basics','verbs'],
     note:'Written: نمی‌دانم (nemidānam).'},
    {id:'bas-ali', term:'عالی', tr:'āli', en:'Excellent', memo:'āli = high, exalted (the name Ali is the same word): \'top\'. Think \'Ali is great\'.',
     parts:[{t:'عالی', tr:'āli', m:'excellent, exalted'}],
     tags:['basics']},
    {id:'bas-kheili', term:'خیلی', tr:'kheili', en:'Very / A lot', memo:'kheili = very, a lot. Think \'hay-lee: a hale lot\'. Goes before adjectives: kheili khub.',
     parts:[{t:'خیلی', tr:'kheili', m:'very, a lot'}],
     tags:['basics'],
     ex:{term:'خیلی خوب', tr:'kheili khub', en:'Very good'}},
    {id:'bas-ye-kam', term:'یه کم', tr:'ye kam', en:'A little bit', memo:'ye = a (spoken yek) + kam = little, few. \'A little.\' kam is the kam of kam-kam, bit by bit.',
     parts:[{t:'یه', tr:'ye', m:'a, one (spoken)'}, {t:'کم', tr:'kam', m:'little, few'}],
     tags:['basics'],
     ex:{term:'یه کم فارسی بلدم.', tr:'ye kam fārsi baladam.', en:'I know a little Persian.'}},
    {id:'bas-moshkeli-nist', term:'مشکلی نیست', tr:'moshkeli nist', en:'No problem', memo:'moshkel = problem (Arabic) + -i = a + nist = is not: \'a problem is not\'. nist = the negative of ast.',
     parts:[{t:'مشکل', tr:'moshkel', m:'problem'}, {t:'ی', tr:'i', m:'a (indefinite)'}, {t:'نیست', tr:'nist', m:'is not'}],
     tags:['basics']},

    /* ---------------- NUMBERS ---------------- */
    {id:'num-yek', term:'یک', tr:'yek', en:'One', memo:'yek = one. Think \'yeah, one\'. Spoken ye before a noun: ye chāi = a tea.',
     parts:[{t:'یک', tr:'yek', m:'one'}],
     tags:['numbers'],
     note:'Spoken: یه (ye) before a noun.'},
    {id:'num-do', term:'دو', tr:'do', en:'Two', memo:'do = two, a cousin of English two, Latin duo, Greek dío. Said \'doh\'.',
     parts:[{t:'دو', tr:'do', m:'two (cognate of two)'}],
     tags:['numbers']},
    {id:'num-se', term:'سه', tr:'se', en:'Three', memo:'se = three, cousin of three, tres, tría. The th became s.',
     parts:[{t:'سه', tr:'se', m:'three (cognate of three)'}],
     tags:['numbers']},
    {id:'num-chahar', term:'چهار', tr:'chahār', en:'Four', memo:'chahār = four, cousin of Latin quattuor. Think \'cha-har\' = \'quatre\' with a Persian accent.',
     parts:[{t:'چهار', tr:'chahār', m:'four (cognate of quattuor)'}],
     tags:['numbers']},
    {id:'num-panj', term:'پنج', tr:'panj', en:'Five', memo:'panj = five, cousin of Greek pénde and Punjab, \'five rivers\'. Punch (the drink) had five ingredients.',
     parts:[{t:'پنج', tr:'panj', m:'five (Punjab = five rivers)'}],
     tags:['numbers']},
    {id:'num-shesh', term:'شش', tr:'shesh', en:'Six', memo:'shesh = six, cousin of six and Greek éxi. Think \'shh, shh\' twice = six.',
     parts:[{t:'شش', tr:'shesh', m:'six (cognate of six)'}],
     tags:['numbers']},
    {id:'num-haft', term:'هفت', tr:'haft', en:'Seven', memo:'haft = seven, cousin of hepta and seven (s and h swap). Haft-sin, the seven S\'s of Nowruz.',
     parts:[{t:'هفت', tr:'haft', m:'seven (cognate of hepta)'}],
     tags:['numbers']},
    {id:'num-hasht', term:'هشت', tr:'hasht', en:'Eight', memo:'hasht = eight, cousin of octo and eight. haft, hasht: seven, eight rhyme.',
     parts:[{t:'هشت', tr:'hasht', m:'eight (cognate of eight)'}],
     tags:['numbers']},
    {id:'num-noh', term:'نه', tr:'noh', en:'Nine', memo:'noh = nine, cousin of nine, novem. Spelled like na (no); the o vowel makes it nine.',
     parts:[{t:'نه', tr:'noh', m:'nine (cognate of nine)'}],
     tags:['numbers'],
     note:'Spelled like "no" (na). The vowel tells them apart.'},
    {id:'num-dah', term:'ده', tr:'dah', en:'Ten', memo:'dah = ten, cousin of deca and ten. Think \'duh, ten fingers\'.',
     parts:[{t:'ده', tr:'dah', m:'ten (cognate of deca)'}],
     tags:['numbers']},
    {id:'num-bist', term:'بیست', tr:'bist', en:'Twenty', memo:'bist = twenty, from the same root as Latin viginti (dvi-, two tens). Think \'beast, twenty\'.',
     parts:[{t:'بیست', tr:'bist', m:'twenty'}],
     tags:['numbers']},
    {id:'num-sad', term:'صد', tr:'sad', en:'One hundred', memo:'sad = hundred, cousin of Latin centum and Greek ekató (the k became s). Think \'sad: a hundred\'.',
     parts:[{t:'صد', tr:'sad', m:'hundred (cognate of centum)'}],
     tags:['numbers']},
    {id:'num-hezar', term:'هزار', tr:'hezār', en:'One thousand', memo:'hezār = thousand. Think \'has R, a thousand\'. Prices: dah hezār tomān.',
     parts:[{t:'هزار', tr:'hezār', m:'thousand'}],
     tags:['numbers'],
     ex:{term:'ده هزار تومان', tr:'dah hezār tomān', en:'Ten thousand tomans'}},

    /* ---------------- QUESTION WORDS ---------------- */
    {id:'q-chi', term:'چی؟', tr:'chi?', en:'What?', memo:'chi = what. Think \'chee: what?\'. chie = what is it (chi + -e is).',
     parts:[{t:'چی', tr:'chi', m:'what'}, {t:'؟', tr:'?', m:'question mark'}],
     tags:['questions'],
     ex:{term:'این چیه؟', tr:'in chie?', en:'What is this?'}},
    {id:'q-koja', term:'کجا؟', tr:'kojā?', en:'Where?', memo:'kojā = where; ko- is the question stem (ki who, key when, kodum which). kojāst = where is.',
     parts:[{t:'کجا', tr:'kojā', m:'where'}, {t:'؟', tr:'?', m:'question mark'}],
     tags:['questions'],
     ex:{term:'دستشویی کجاست؟', tr:'dastshui kojāst?', en:'Where is the toilet?'}},
    {id:'q-key', term:'کی؟', tr:'key?', en:'When?', memo:'key = when, said \'kay\'. Spelled like ki (who); only the vowel differs. Think \'okay, when?\'.',
     parts:[{t:'کی', tr:'key', m:'when'}, {t:'؟', tr:'?', m:'question mark'}],
     tags:['questions'],
     note:'Spelled like "who" (ki). The vowel differs.'},
    {id:'q-chera', term:'چرا؟', tr:'cherā?', en:'Why?', memo:'che = what + rā = for (object marker): \'for what?\' = why. Like Greek yatí (for-what).',
     parts:[{t:'چه', tr:'che', m:'what'}, {t:'را', tr:'rā', m:'for, object marker'}],
     tags:['questions']},
    {id:'q-chetor', term:'چطور؟', tr:'chetor?', en:'How?', memo:'che = what + tor = manner (Arabic tawr): \'what manner\' = how. The chetor of chetori.',
     parts:[{t:'چه', tr:'che', m:'what'}, {t:'طور', tr:'tor', m:'manner, way'}],
     tags:['questions']},
    {id:'q-ki', term:'کی؟', tr:'ki?', en:'Who?', memo:'ki = who, said \'kee\'. Think \'key person: who?\'.',
     parts:[{t:'کی', tr:'ki', m:'who'}, {t:'؟', tr:'?', m:'question mark'}],
     tags:['questions']},
    {id:'q-chand', term:'چند؟', tr:'chand?', en:'How much / How many?', memo:'chand = how many, how much. Think \'chand-elier: how many candles?\'. chande = how much is it.',
     parts:[{t:'چند', tr:'chand', m:'how many, how much'}, {t:'؟', tr:'?', m:'question mark'}],
     tags:['questions','shopping']},
    {id:'q-kodum', term:'کدوم؟', tr:'kodum?', en:'Which one?', memo:'kodum = which one. The ko- question stem + dum. Written kodām.',
     parts:[{t:'کدوم', tr:'kodum', m:'which one'}, {t:'؟', tr:'?', m:'question mark'}],
     tags:['questions'],
     note:'Written: کدام (kodām).'},

    /* ---------------- PRONOUNS ---------------- */
    {id:'pro-man', term:'من', tr:'man', en:'I', memo:'man = I. Think \'me, man\'. Add -am to verbs for the same I: dāram, mikhām.',
     parts:[{t:'من', tr:'man', m:'I'}],
     tags:['pronouns']},
    {id:'pro-to', term:'تو', tr:'to', en:'You (informal)', memo:'to = you (one friend), a cousin of English thou and French tu. Verbs take -i: dāri, miri.',
     parts:[{t:'تو', tr:'to', m:'you (informal, cognate of thou)'}],
     tags:['pronouns']},
    {id:'pro-shoma', term:'شما', tr:'shomā', en:'You (formal or plural)', memo:'shomā = you, plural or polite. Think \'show ma respect\'. Verbs take -id: dārid.',
     parts:[{t:'شما', tr:'shomā', m:'you (plural, formal)'}],
     tags:['pronouns']},
    {id:'pro-u', term:'او', tr:'u', en:'He / She', memo:'u = he or she, just \'oo\'. No gender in Persian. Spoken: un.',
     parts:[{t:'او', tr:'u', m:'he / she'}],
     tags:['pronouns'],
     note:'Persian pronouns have no gender. Spoken: اون (un).'},
    {id:'pro-ma', term:'ما', tr:'mā', en:'We', memo:'mā = we. Think \'ma and the family: we\'. Verbs take -im: dārim.',
     parts:[{t:'ما', tr:'mā', m:'we'}],
     tags:['pronouns']},
    {id:'pro-unha', term:'اون‌ها', tr:'unhā', en:'They', memo:'un = that + -hā = plural: \'those\' = they. -hā makes any noun plural: ketābhā = books.',
     parts:[{t:'اون', tr:'un', m:'that'}, {t:'ها', tr:'hā', m:'plural ending'}],
     tags:['pronouns'],
     note:'Written: آن‌ها (ānhā).'},
    {id:'pro-in', term:'این', tr:'in', en:'This', memo:'in = this. Think \'in here, this one\'. in chie = what is this?',
     parts:[{t:'این', tr:'in', m:'this'}],
     tags:['pronouns']},
    {id:'pro-un', term:'اون', tr:'un', en:'That', memo:'un = that (written ān). in this, un that: \'in here, un there\'.',
     parts:[{t:'اون', tr:'un', m:'that'}],
     tags:['pronouns']},
    {id:'pro-e-man', term:'ـِ من', tr:'-e man', en:'My (after the noun)', memo:'The ezāfe: an unwritten -e glues noun to owner or adjective. ketāb-e man = book-of me. Say the -e softly.',
     parts:[{t:'ـِ', tr:'-e', m:'of (ezāfe link)'}, {t:'من', tr:'man', m:'I, me'}],
     tags:['pronouns'],
     note:'The ezāfe -e links a noun to its owner.',
     ex:{term:'کتاب من', tr:'ketāb-e man', en:'My book'}},
    {id:'pro-am', term:'ـم', tr:'-am', en:'My (suffix, spoken)', memo:'-am stuck to a noun = my: esm-am = my name. The same -am that means I on verbs. -et your, -esh his/her.',
     parts:[{t:'ـم', tr:'-am', m:'my (possessive suffix)'}],
     tags:['pronouns'],
     ex:{term:'اسمم', tr:'esmam', en:'My name'}},

    /* ---------------- TIME ---------------- */
    {id:'time-emruz', term:'امروز', tr:'emruz', en:'Today', memo:'em- = this + ruz = day (Nowruz = new day, the Persian new year). \'This day.\'',
     parts:[{t:'ام', tr:'em', m:'this'}, {t:'روز', tr:'ruz', m:'day (as in Nowruz)'}],
     tags:['time']},
    {id:'time-farda', term:'فردا', tr:'fardā', en:'Tomorrow', memo:'fardā = tomorrow. Think \'far day\', the day that is still far. pas-fardā = the day after.',
     parts:[{t:'فردا', tr:'fardā', m:'tomorrow'}],
     tags:['time']},
    {id:'time-diruz', term:'دیروز', tr:'diruz', en:'Yesterday', memo:'di = yesterday (old word) + ruz = day. The ruz of emruz again.',
     parts:[{t:'دی', tr:'di', m:'yesterday (old)'}, {t:'روز', tr:'ruz', m:'day'}],
     tags:['time']},
    {id:'time-alan', term:'الان', tr:'alān', en:'Now', memo:'alān = now (Arabic al-ān, \'the moment\'). Think \'all on: now\'.',
     parts:[{t:'الان', tr:'alān', m:'now'}],
     tags:['time']},
    {id:'time-badan', term:'بعداً', tr:'ba\'dan', en:'Later', memo:'ba\'d = after + -an = -ly: \'afterwards\'. The ba\'d of con-bad (then).',
     parts:[{t:'بعد', tr:'ba\'d', m:'after'}, {t:'اً', tr:'an', m:'-ly'}],
     tags:['time']},
    {id:'time-saat-chande', term:'ساعت چنده؟', tr:'sā\'at chande?', en:'What time is it?', memo:'sā\'at = hour, clock (Arabic sā\'a) + chand = how much + -e = is: \'the hour is how much?\'',
     parts:[{t:'ساعت', tr:'sā\'at', m:'hour, clock'}, {t:'چند', tr:'chand', m:'how much'}, {t:'ه', tr:'e', m:'is (spoken)'}],
     tags:['time','questions']},
    {id:'time-sobh', term:'صبح', tr:'sobh', en:'Morning', memo:'sobh = morning, the sobh of sobh bekheir. Think \'sob in the morning\'.',
     parts:[{t:'صبح', tr:'sobh', m:'morning'}],
     tags:['time']},
    {id:'time-shab', term:'شب', tr:'shab', en:'Night', memo:'shab = night, the shab of shab bekheir. Think \'shabby night\'.',
     parts:[{t:'شب', tr:'shab', m:'night'}],
     tags:['time']},
    {id:'time-shanbe', term:'شنبه', tr:'shanbe', en:'Saturday', memo:'shanbe = Saturday, a cousin of Sabbath. The other days count from it: yek-shanbe (1), do-shanbe (2)...',
     parts:[{t:'شنبه', tr:'shanbe', m:'Saturday (Sabbath)'}],
     tags:['time'],
     note:'The week starts on Saturday: شنبه، یکشنبه، دوشنبه، سه‌شنبه، چهارشنبه، پنجشنبه، جمعه.'},
    {id:'time-jome', term:'جمعه', tr:'jom\'e', en:'Friday', memo:'jom\'e = Friday, from Arabic jum\'a = gathering: the day of the congregation.',
     parts:[{t:'جمعه', tr:'jom\'e', m:'Friday (gathering day)'}],
     tags:['time'],
     note:'The weekend day.'},
    {id:'time-akhar-e-hafte', term:'آخر هفته', tr:'ākhar-e hafte', en:'Weekend', memo:'ākhar = end + -e = of + hafte = week (from haft = seven: seven days). \'End of the week.\'',
     parts:[{t:'آخر', tr:'ākhar', m:'end'}, {t:'ـِ', tr:'-e', m:'of (ezāfe)'}, {t:'هفته', tr:'hafte', m:'week (from haft, seven)'}],
     tags:['time']},

    /* ---------------- FOOD & ORDERING ---------------- */
    {id:'food-ab', term:'آب', tr:'āb', en:'Water', memo:'āb = water, as in Punjab, \'five waters\'. Think \'ahh, water\'.',
     parts:[{t:'آب', tr:'āb', m:'water'}],
     tags:['food'],
     ex:{term:'یه آب لطفاً.', tr:'ye āb lotfan.', en:'A water, please.'}},
    {id:'food-chai', term:'چای', tr:'chāi', en:'Tea', memo:'chāi = tea, the same word as chai, from Chinese cha. Served in small glasses, constantly.',
     parts:[{t:'چای', tr:'chāi', m:'tea (chai)'}],
     tags:['food'],
     note:'The national drink, served constantly.'},
    {id:'food-ghahve', term:'قهوه', tr:'ghahve', en:'Coffee', memo:'ghahve = coffee, the Arabic qahwa that gave the world \'coffee\' and \'café\'.',
     parts:[{t:'قهوه', tr:'ghahve', m:'coffee (qahwa)'}],
     tags:['food']},
    {id:'food-nun', term:'نون', tr:'nun', en:'Bread', memo:'nun = bread (written nān). Think \'naan\', the Indian bread: same word.',
     parts:[{t:'نون', tr:'nun', m:'bread (naan)'}],
     tags:['food'],
     note:'Written: نان (nān).'},
    {id:'food-berenj', term:'برنج', tr:'berenj', en:'Rice', memo:'berenj = rice (the grain). Think \'bring the rice\'. Cooked on the plate it is polo.',
     parts:[{t:'برنج', tr:'berenj', m:'rice (grain)'}],
     tags:['food'],
     note:'Cooked rice on the plate is پلو (polo).'},
    {id:'food-khoshmaze', term:'خوشمزه', tr:'khoshmaze', en:'Delicious', memo:'khosh = pleasant (khoshbakhtam) + maze = taste: \'pleasant-tasting\'. Think \'it amazes\'.',
     parts:[{t:'خوش', tr:'khosh', m:'pleasant'}, {t:'مزه', tr:'maze', m:'taste'}],
     tags:['food'],
     ex:{term:'خیلی خوشمزه است.', tr:'kheili khoshmaze ast.', en:'It\'s very tasty.'}},
    {id:'food-surat-hesab', term:'صورت‌حساب لطفاً', tr:'surat-hesāb lotfan', en:'The bill, please', memo:'surat = list, form + hesāb = account (Arabic hisāb, counting): \'account list\' = the bill.',
     parts:[{t:'صورت', tr:'surat', m:'list, form'}, {t:'حساب', tr:'hesāb', m:'account, reckoning'}, {t:'لطفاً', tr:'lotfan', m:'please'}],
     tags:['food']},
    {id:'food-meno', term:'منو لطفاً', tr:'meno lotfan', en:'The menu, please', memo:'meno = menu, from French. lotfan = please.',
     parts:[{t:'منو', tr:'meno', m:'menu (French)'}, {t:'لطفاً', tr:'lotfan', m:'please'}],
     tags:['food']},
    {id:'food-gorosname', term:'گرسنمه', tr:'gorosname', en:'I\'m hungry', memo:'gorosne = hungry + -am = I am, spoken as gorosname: \'hungry-am-I\'.',
     parts:[{t:'گرسنه', tr:'gorosne', m:'hungry'}, {t:'م', tr:'am', m:'I am (spoken -ame)'}],
     tags:['food','feelings'],
     note:'Written: گرسنه هستم (gorosne hastam).'},
    {id:'food-teshname', term:'تشنمه', tr:'teshname', en:'I\'m thirsty', memo:'teshne = thirsty + -am = I am. Same shape as gorosname.',
     parts:[{t:'تشنه', tr:'teshne', m:'thirsty'}, {t:'م', tr:'am', m:'I am'}],
     tags:['food','feelings']},
    {id:'food-bedun', term:'بدون', tr:'bedun', en:'Without', memo:'bedun = without. Think \'be done without it\'. Links with the ezāfe: bedun-e shekar.',
     parts:[{t:'بدون', tr:'bedun', m:'without'}],
     tags:['food'],
     ex:{term:'بدون شکر', tr:'bedun-e shekar', en:'Without sugar'}},
    {id:'food-ba', term:'با', tr:'bā', en:'With', memo:'bā = with. Think \'bā with you\'. bā shir = with milk, bā kārt = by card.',
     parts:[{t:'با', tr:'bā', m:'with'}],
     tags:['food'],
     ex:{term:'با شیر', tr:'bā shir', en:'With milk'}},
    {id:'food-miz-baraye-do', term:'یه میز برای دو نفر', tr:'ye miz barāye do nafar', en:'A table for two', memo:'ye = a + miz = table + barāye = for + do = two + nafar = person(s). nafar counts people.',
     parts:[{t:'یه', tr:'ye', m:'a'}, {t:'میز', tr:'miz', m:'table'}, {t:'برای', tr:'barāye', m:'for'}, {t:'دو', tr:'do', m:'two'}, {t:'نفر', tr:'nafar', m:'person (counter)'}],
     tags:['food']},
    {id:'food-nush-e-jan', term:'نوش جان', tr:'nush-e jān', en:'Enjoy your meal', memo:'nush = drink, enjoy + -e = of + jān = soul, life: \'drink of the soul\', enjoy. jān is also \'dear\'.',
     parts:[{t:'نوش', tr:'nush', m:'enjoy, drink'}, {t:'ـِ', tr:'-e', m:'of (ezāfe)'}, {t:'جان', tr:'jān', m:'soul, life'}],
     tags:['food','politeness'],
     note:'Also the reply when someone thanks you for food.'},

    /* ---------------- PLACES & DIRECTIONS ---------------- */
    {id:'place-kojast', term:'... کجاست؟', tr:'... kojāst?', en:'Where is ...?', memo:'kojā = where + -st = is (ast): \'where is\'. Put the place first: metro kojāst?',
     parts:[{t:'کجا', tr:'kojā', m:'where'}, {t:'ست', tr:'st', m:'is (ast)'}],
     tags:['places','questions'],
     ex:{term:'ایستگاه مترو کجاست؟', tr:'istgāh-e metro kojāst?', en:'Where is the metro station?'}},
    {id:'place-chap', term:'چپ', tr:'chap', en:'Left', memo:'chap = left. Think \'chap on the left\'.',
     parts:[{t:'چپ', tr:'chap', m:'left'}],
     tags:['places']},
    {id:'place-rast', term:'راست', tr:'rāst', en:'Right', memo:'rāst = right, and also true, straight. Think \'right as rust-free\'.',
     parts:[{t:'راست', tr:'rāst', m:'right, straight, true'}],
     tags:['places']},
    {id:'place-mostaghim', term:'مستقیم', tr:'mostaghim', en:'Straight ahead', memo:'mostaghim = straight, direct (Arabic). Think \'most-a-ghim: most direct\'.',
     parts:[{t:'مستقیم', tr:'mostaghim', m:'straight, direct'}],
     tags:['places']},
    {id:'place-inja', term:'اینجا', tr:'injā', en:'Here', memo:'in = this + jā = place: \'this place\' = here. jā = place appears in kojā too (which place).',
     parts:[{t:'این', tr:'in', m:'this'}, {t:'جا', tr:'jā', m:'place'}],
     tags:['places']},
    {id:'place-unja', term:'اونجا', tr:'unjā', en:'There', memo:'un = that + jā = place: \'that place\' = there. injā here, unjā there, kojā where.',
     parts:[{t:'اون', tr:'un', m:'that'}, {t:'جا', tr:'jā', m:'place'}],
     tags:['places']},
    {id:'place-nazdik', term:'نزدیک', tr:'nazdik', en:'Near', memo:'nazdik = near. Think \'next-door, near\'. nazdike = it is near.',
     parts:[{t:'نزدیک', tr:'nazdik', m:'near'}],
     tags:['places'],
     ex:{term:'نزدیکه؟', tr:'nazdike?', en:'Is it near?'}},
    {id:'place-dur', term:'دور', tr:'dur', en:'Far', memo:'dur = far. Think \'durable, lasting a long way\'.',
     parts:[{t:'دور', tr:'dur', m:'far'}],
     tags:['places']},
    {id:'place-forudgah', term:'فرودگاه', tr:'forudgāh', en:'Airport', memo:'forud = landing, descent + -gāh = place: \'landing-place\'. -gāh is the place suffix (dāneshgāh = university).',
     parts:[{t:'فرود', tr:'forud', m:'landing'}, {t:'گاه', tr:'gāh', m:'place (suffix)'}],
     tags:['places']},
    {id:'place-dastshui', term:'دستشویی', tr:'dastshui', en:'Toilet', memo:'dast = hand + shui = washing (shostan = wash): \'hand-washing\' place.',
     parts:[{t:'دست', tr:'dast', m:'hand'}, {t:'شویی', tr:'shui', m:'washing'}],
     tags:['places']},
    {id:'place-bazar', term:'بازار', tr:'bāzār', en:'Bazaar / Market', memo:'bāzār = market, the word English borrowed as bazaar.',
     parts:[{t:'بازار', tr:'bāzār', m:'market (bazaar)'}],
     tags:['places']},
    {id:'place-khiyaban', term:'خیابان', tr:'khiyābān', en:'Street', memo:'khiyābān = street, originally a tree-lined avenue. Think \'the cab on the street\'.',
     parts:[{t:'خیابان', tr:'khiyābān', m:'street, avenue'}],
     tags:['places']},

    /* ---------------- SHOPPING & MONEY ---------------- */
    {id:'shop-chande', term:'چنده؟', tr:'chande?', en:'How much is it?', memo:'chand = how much + -e = is: \'how much is it?\'. The shortest shopping question.',
     parts:[{t:'چند', tr:'chand', m:'how much'}, {t:'ه', tr:'e', m:'is (spoken)'}],
     tags:['shopping']},
    {id:'shop-gerun', term:'گرون', tr:'gerun', en:'Expensive', memo:'gerun = expensive (written gerān), from the root \'heavy\': a heavy price. Think \'groan at the price\'.',
     parts:[{t:'گرون', tr:'gerun', m:'expensive (heavy)'}],
     tags:['shopping'],
     note:'Written: گران (gerān).'},
    {id:'shop-arzun', term:'ارزون', tr:'arzun', en:'Cheap', memo:'arzun = cheap (written arzān), from arz = value: \'within value\'. Think \'a reason-able price\'.',
     parts:[{t:'ارزون', tr:'arzun', m:'cheap'}],
     tags:['shopping'],
     note:'Written: ارزان (arzān).'},
    {id:'shop-ba-kart', term:'با کارت', tr:'bā kārt', en:'By card', memo:'bā = with + kārt = card (loanword). \'With card.\'',
     parts:[{t:'با', tr:'bā', m:'with'}, {t:'کارت', tr:'kārt', m:'card'}],
     tags:['shopping']},
    {id:'shop-naghd', term:'نقد', tr:'naghd', en:'Cash', memo:'naghd = cash (Arabic naqd, \'ready money\'). Think \'nagged for cash\'.',
     parts:[{t:'نقد', tr:'naghd', m:'cash'}],
     tags:['shopping']},
    {id:'shop-pul', term:'پول', tr:'pul', en:'Money', memo:'pul = money. Think \'pool of money\'.',
     parts:[{t:'پول', tr:'pul', m:'money'}],
     tags:['shopping']},
    {id:'shop-toman', term:'تومان', tr:'tomān', en:'Toman', memo:'tomān = toman, the price unit (10 rials). From Mongolian tümen = ten thousand.',
     parts:[{t:'تومان', tr:'tomān', m:'toman (10 rials)'}],
     tags:['shopping'],
     note:'Prices are quoted in tomans. One toman is ten rials.'},
    {id:'shop-hamin-o-mikham', term:'همین رو می‌خوام', tr:'hamin ro mikhām', en:'I\'ll take this one', memo:'hamin = this very one + ro = object marker + mikhām = I want. \'This one I want.\'',
     parts:[{t:'همین', tr:'hamin', m:'this very one'}, {t:'رو', tr:'ro', m:'object marker (spoken rā)'}, {t:'می‌خوام', tr:'mikhām', m:'I want'}],
     tags:['shopping']},
    {id:'shop-faghat-negah', term:'فقط نگاه می‌کنم', tr:'faghat negāh mikonam', en:'Just looking', memo:'faghat = only + negāh = a look + mikonam = I do: \'only I do a look\'. Verbs often = noun + kardan (do).',
     parts:[{t:'فقط', tr:'faghat', m:'only'}, {t:'نگاه', tr:'negāh', m:'a look'}, {t:'می‌کنم', tr:'mikonam', m:'I do'}],
     tags:['shopping']},
    {id:'shop-takhfif', term:'تخفیف', tr:'takhfif', en:'Discount', memo:'takhfif = discount, from Arabic \'to lighten\'. Think \'take-fief off the price\'. takhfif dāre? = does it have a discount?',
     parts:[{t:'تخفیف', tr:'takhfif', m:'discount (lightening)'}],
     tags:['shopping'],
     ex:{term:'تخفیف داره؟', tr:'takhfif dāre?', en:'Is there a discount?'}},

    /* ---------------- FEELINGS & SMALL TALK ---------------- */
    {id:'feel-khoshhalam', term:'خوشحالم', tr:'khoshhālam', en:'I\'m happy', memo:'khosh = happy (khoshbakhtam, khoshmaze) + hāl = state, mood + -am = I am: \'my state is happy\'.',
     parts:[{t:'خوش', tr:'khosh', m:'happy, pleasant'}, {t:'حال', tr:'hāl', m:'state, condition'}, {t:'م', tr:'am', m:'I am'}],
     tags:['feelings']},
    {id:'feel-khaste-am', term:'خسته‌ام', tr:'khaste-am', en:'I\'m tired', memo:'khaste = tired + -am = I am. Think \'cast-eh: cast down, tired\'.',
     parts:[{t:'خسته', tr:'khaste', m:'tired'}, {t:'ام', tr:'am', m:'I am'}],
     tags:['feelings']},
    {id:'feel-hava-garme', term:'هوا گرمه', tr:'havā garme', en:'It\'s hot (weather)', memo:'havā = weather, air + garm = warm (a cousin of English warm) + -e = is. \'Weather is warm.\'',
     parts:[{t:'هوا', tr:'havā', m:'weather, air'}, {t:'گرم', tr:'garm', m:'warm, hot (cognate of warm)'}, {t:'ه', tr:'e', m:'is'}],
     tags:['feelings','time']},
    {id:'feel-hava-sarde', term:'هوا سرده', tr:'havā sarde', en:'It\'s cold (weather)', memo:'havā = weather + sard = cold + -e = is. Think \'sardines are kept cold\'.',
     parts:[{t:'هوا', tr:'havā', m:'weather'}, {t:'سرد', tr:'sard', m:'cold'}, {t:'ه', tr:'e', m:'is'}],
     tags:['feelings','time']},
    {id:'feel-dust-daram', term:'دوست دارم', tr:'dust dāram', en:'I like it / I love it', memo:'dust = friend (Hindi \'dost\' is the same word) + dāram = I have: \'I have it as a friend\' = I like / love it.',
     parts:[{t:'دوست', tr:'dust', m:'friend'}, {t:'دار', tr:'dār', m:'have'}, {t:'م', tr:'am', m:'I'}],
     tags:['feelings','verbs'],
     ex:{term:'ایران رو دوست دارم.', tr:'Irān ro dust dāram.', en:'I like Iran.'}},
    {id:'feel-dust-nadaram', term:'دوست ندارم', tr:'dust nadāram', en:'I don\'t like it', memo:'dust + na-dāram = I don\'t have. na- before the verb = not (ne- before mi-).',
     parts:[{t:'دوست', tr:'dust', m:'friend'}, {t:'ن', tr:'na', m:'not'}, {t:'دارم', tr:'dāram', m:'I have'}],
     tags:['feelings','verbs']},
    {id:'feel-khub-nistam', term:'خوب نیستم', tr:'khub nistam', en:'I\'m not well', memo:'khub = good + nistam = I am not (nist + -am). \'I\'m not well.\'',
     parts:[{t:'خوب', tr:'khub', m:'good, well'}, {t:'نیست', tr:'nist', m:'is not'}, {t:'م', tr:'am', m:'I'}],
     tags:['feelings']},
    {id:'feel-ghorbunet-beram', term:'قربونت برم', tr:'ghorbunet beram', en:'(term of endearment)', memo:'ghorbun = sacrifice + -et = your + beram = may I go: \'may I go as your sacrifice\'. Said like \'sweetie\'.',
     parts:[{t:'قربون', tr:'ghorbun', m:'sacrifice'}, {t:'ت', tr:'et', m:'your'}, {t:'برم', tr:'beram', m:'may I go'}],
     tags:['feelings'],
     note:'Literally "may I be sacrificed for you". Family and friends say it constantly.'},
    {id:'feel-jun', term:'جون', tr:'jun', en:'Dear (after a name)', memo:'jun = dear, from jān = soul, life (nush-e jān). Add after a name: Sām jun.',
     parts:[{t:'جون', tr:'jun', m:'dear (soul)'}],
     tags:['feelings'],
     ex:{term:'سام جون', tr:'Sām jun', en:'Dear Sam'}},

    /* ---------------- VERBS (spoken present, I / you) ---------------- */
    {id:'verb-mikham', term:'می‌خوام', tr:'mikhām', en:'I want', memo:'mi- = present + khā(h) = want (khāstan) + -am = I: \'I want\'. mi- + stem + ending is every present verb.',
     parts:[{t:'می', tr:'mi', m:'present marker'}, {t:'خوا', tr:'khā', m:'want'}, {t:'م', tr:'am', m:'I'}],
     tags:['verbs'],
     note:'Written: می‌خواهم (mikhāham).',
     ex:{term:'آب می‌خوام.', tr:'āb mikhām.', en:'I want water.'}},
    {id:'verb-mikhay', term:'می‌خوای؟', tr:'mikhāy?', en:'Do you want?', memo:'mi-khā-y: the -i/-y ending = you. mikhām I want, mikhāy you want.',
     parts:[{t:'می', tr:'mi', m:'present marker'}, {t:'خوا', tr:'khā', m:'want'}, {t:'ی', tr:'y', m:'you'}],
     tags:['verbs'],
     ex:{term:'چای می‌خوای؟', tr:'chāi mikhāy?', en:'Do you want tea?'}},
    {id:'verb-daram', term:'دارم', tr:'dāram', en:'I have', memo:'dār = have (dāshtan) + -am = I. No mi- needed on \'have\'. Think \'I dare have it\'.',
     parts:[{t:'دار', tr:'dār', m:'have'}, {t:'م', tr:'am', m:'I'}],
     tags:['verbs']},
    {id:'verb-dari', term:'داری؟', tr:'dāri?', en:'Do you have?', memo:'dār + -i = you have. vaght dāri? = do you have time?',
     parts:[{t:'دار', tr:'dār', m:'have'}, {t:'ی', tr:'i', m:'you'}],
     tags:['verbs'],
     ex:{term:'وقت داری؟', tr:'vaght dāri?', en:'Do you have time?'}},
    {id:'verb-miram', term:'می‌رم', tr:'miram', en:'I go', memo:'mi- + r (raftan = go) + -am = I go. Think \'me run\'. khune miram = I go home.',
     parts:[{t:'می', tr:'mi', m:'present marker'}, {t:'ر', tr:'r', m:'go (raftan)'}, {t:'م', tr:'am', m:'I'}],
     tags:['verbs'],
     ex:{term:'خونه می‌رم.', tr:'khune miram.', en:'I\'m going home.'}},
    {id:'verb-miri', term:'می‌ری؟', tr:'miri?', en:'Are you going?', memo:'mi-r-i = you go. kojā miri? = where are you going?',
     parts:[{t:'می', tr:'mi', m:'present marker'}, {t:'ر', tr:'r', m:'go'}, {t:'ی', tr:'i', m:'you'}],
     tags:['verbs'],
     ex:{term:'کجا می‌ری؟', tr:'kojā miri?', en:'Where are you going?'}},
    {id:'verb-mifahmam', term:'می‌فهمم', tr:'mifahmam', en:'I understand', memo:'mi- + fahm = understand (Arabic fahm) + -am = I. Think \'I fathom\'.',
     parts:[{t:'می', tr:'mi', m:'present marker'}, {t:'فهم', tr:'fahm', m:'understand'}, {t:'م', tr:'am', m:'I'}],
     tags:['verbs']},
    {id:'verb-mifahmi', term:'می‌فهمی؟', tr:'mifahmi?', en:'Do you understand?', memo:'mi-fahm-i = you understand. Question with a rising tone.',
     parts:[{t:'می', tr:'mi', m:'present marker'}, {t:'فهم', tr:'fahm', m:'understand'}, {t:'ی', tr:'i', m:'you'}],
     tags:['verbs']},
    {id:'verb-midunam', term:'می‌دونم', tr:'midunam', en:'I know', memo:'mi- + dun = know (dānestan) + -am = I. The positive of nemidunam.',
     parts:[{t:'می', tr:'mi', m:'present marker'}, {t:'دون', tr:'dun', m:'know'}, {t:'م', tr:'am', m:'I'}],
     tags:['verbs']},
    {id:'verb-mitunam', term:'می‌تونم', tr:'mitunam', en:'I can', memo:'mi- + tun = can (tavānestan) + -am = I. Think \'me, I\'m able to tune\'.',
     parts:[{t:'می', tr:'mi', m:'present marker'}, {t:'تون', tr:'tun', m:'can, be able'}, {t:'م', tr:'am', m:'I'}],
     tags:['verbs']},
    {id:'verb-mituni', term:'می‌تونی؟', tr:'mituni?', en:'Can you?', memo:'mi-tun-i = you can. mituni komakam koni? = can you help me?',
     parts:[{t:'می', tr:'mi', m:'present marker'}, {t:'تون', tr:'tun', m:'can'}, {t:'ی', tr:'i', m:'you'}],
     tags:['verbs'],
     ex:{term:'می‌تونی کمکم کنی؟', tr:'mituni komakam koni?', en:'Can you help me?'}},
    {id:'verb-hastam', term:'هستم', tr:'hastam', en:'I am', memo:'hast = is, exists + -am = I: \'I am\'. The full form; -am alone often does the job (khubam).',
     parts:[{t:'هست', tr:'hast', m:'is, exists'}, {t:'م', tr:'am', m:'I'}],
     tags:['verbs'],
     ex:{term:'من آمریکایی هستم.', tr:'man āmrikāi hastam.', en:'I\'m American.'}},
    {id:'verb-hasti', term:'هستی؟', tr:'hasti?', en:'Are you?', memo:'hast + -i = you are. ahl-e kojā hasti? = where are you from?',
     parts:[{t:'هست', tr:'hast', m:'is'}, {t:'ی', tr:'i', m:'you'}],
     tags:['verbs'],
     ex:{term:'اهل کجا هستی؟', tr:'ahl-e kojā hasti?', en:'Where are you from?'}},
    {id:'verb-harf-mizanam', term:'حرف می‌زنم', tr:'harf mizanam', en:'I speak', memo:'harf = word, letter + mizanam = I hit (zadan): \'I hit words\' = I speak. Many verbs are noun + zadan or kardan.',
     parts:[{t:'حرف', tr:'harf', m:'word, speech'}, {t:'می', tr:'mi', m:'present marker'}, {t:'زن', tr:'zan', m:'hit, strike (zadan)'}, {t:'م', tr:'am', m:'I'}],
     tags:['verbs'],
     ex:{term:'یه کم فارسی حرف می‌زنم.', tr:'ye kam fārsi harf mizanam.', en:'I speak a little Persian.'}},
    {id:'verb-berim', term:'بریم', tr:'berim', en:'Let\'s go', memo:'be- = let\'s / command prefix + r = go + -im = we: \'let\'s go\'. Think \'be rim: let\'s go to the rim\'.',
     parts:[{t:'ب', tr:'be', m:'subjunctive prefix (let\'s)'}, {t:'ر', tr:'r', m:'go'}, {t:'یم', tr:'im', m:'we'}],
     tags:['verbs']},
    {id:'verb-biya', term:'بیا', tr:'biyā', en:'Come (here)', memo:'bi- + ā = come (āmadan): \'come!\'. Think \'be here\'. biyā tu = come in.',
     parts:[{t:'بی', tr:'bi', m:'command prefix'}, {t:'ا', tr:'ā', m:'come (āmadan)'}],
     tags:['verbs']},

    /* ---------------- SURVIVAL ---------------- */
    {id:'surv-nemifahmam', term:'نمی‌فهمم', tr:'nemifahmam', en:'I don\'t understand', memo:'ne- + mi- + fahm + -am: \'I don\'t understand\'. ne-mi- is the negative present, as in nemidunam.',
     parts:[{t:'ن', tr:'ne', m:'not'}, {t:'می', tr:'mi', m:'present marker'}, {t:'فهم', tr:'fahm', m:'understand'}, {t:'م', tr:'am', m:'I'}],
     tags:['survival']},
    {id:'surv-yavash-tar', term:'یواش‌تر لطفاً', tr:'yavāsh-tar lotfan', en:'Slower, please', memo:'yavāsh = slow, quiet + -tar = more (comparative, like English -er): \'slower\'. Think \'yeah, wash slower\'.',
     parts:[{t:'یواش', tr:'yavāsh', m:'slow, quiet'}, {t:'تر', tr:'tar', m:'more (-er)'}, {t:'لطفاً', tr:'lotfan', m:'please'}],
     tags:['survival']},
    {id:'surv-englisi-baladid', term:'انگلیسی بلدید؟', tr:'englisi baladid?', en:'Do you speak English?', memo:'englisi = English + balad = knowing how + -id = you are: \'are you knowing English?\'. balad = skilled at.',
     parts:[{t:'انگلیسی', tr:'englisi', m:'English'}, {t:'بلد', tr:'balad', m:'knowing how, skilled'}, {t:'ید', tr:'id', m:'you are (plural, formal)'}],
     tags:['survival'],
     note:'بلد بودن = to know how.'},
    {id:'surv-farsi-balad-nistam', term:'فارسی خوب بلد نیستم', tr:'fārsi khub balad nistam', en:'I don\'t speak Persian well', memo:'fārsi = Persian + khub = well + balad = knowing + nistam = I am not. \'I\'m not well-knowing Persian.\'',
     parts:[{t:'فارسی', tr:'fārsi', m:'Persian'}, {t:'خوب', tr:'khub', m:'well'}, {t:'بلد', tr:'balad', m:'knowing how'}, {t:'نیستم', tr:'nistam', m:'I am not'}],
     tags:['survival']},
    {id:'surv-be-farsi-chi-migan', term:'به فارسی چی می‌گن؟', tr:'be fārsi chi migan?', en:'How do you say it in Persian?', memo:'be = in + fārsi + chi = what + migan = they say (mi- + g + -an): \'in Persian what do they say?\'. -an = they.',
     parts:[{t:'به', tr:'be', m:'in, to'}, {t:'فارسی', tr:'fārsi', m:'Persian'}, {t:'چی', tr:'chi', m:'what'}, {t:'می‌گن', tr:'migan', m:'they say'}],
     tags:['survival']},
    {id:'surv-yani-chi', term:'یعنی چی؟', tr:'ya\'ni chi?', en:'What does it mean?', memo:'ya\'ni = it means (Arabic) + chi = what: \'means what?\'. ya\'ni alone is \'I mean...\'.',
     parts:[{t:'یعنی', tr:'ya\'ni', m:'it means'}, {t:'چی', tr:'chi', m:'what'}],
     tags:['survival']},
    {id:'surv-dobare', term:'دوباره لطفاً', tr:'dobāre lotfan', en:'Again, please', memo:'do = two + bāre = time: \'a second time\' = again. The do of \'two\'.',
     parts:[{t:'دو', tr:'do', m:'two'}, {t:'باره', tr:'bāre', m:'time, instance'}, {t:'لطفاً', tr:'lotfan', m:'please'}],
     tags:['survival']},
    {id:'surv-ye-lahze', term:'یه لحظه', tr:'ye lahze', en:'One moment', memo:'ye = a + lahze = moment (Arabic, \'a glance\'). \'A moment.\'',
     parts:[{t:'یه', tr:'ye', m:'a'}, {t:'لحظه', tr:'lahze', m:'moment'}],
     tags:['survival']},
    {id:'surv-komak', term:'کمک!', tr:'komak!', en:'Help!', memo:'komak = help. Think \'come back and help\'. komakam koni = help me.',
     parts:[{t:'کمک', tr:'komak', m:'help'}],
     tags:['survival']},

    /* ---------------- CONNECTORS ---------------- */
    {id:'con-va', term:'و', tr:'va', en:'And', memo:'va = and; spoken as -o glued on: nun-o panir. Think \'va = and, o = \'n\'.',
     parts:[{t:'و', tr:'va / -o', m:'and'}],
     tags:['connectors'],
     note:'Spoken as -o glued to the first word: nun-o panir.',
     ex:{term:'چای و نون', tr:'chāi-o nun', en:'Tea and bread'}},
    {id:'con-vali', term:'ولی', tr:'vali', en:'But', memo:'vali = but (Arabic). Think \'volley back: but\'.',
     parts:[{t:'ولی', tr:'vali', m:'but'}],
     tags:['connectors']},
    {id:'con-chon', term:'چون', tr:'chon', en:'Because', memo:'chon = because, since. Think \'chon-cause\'. Also \'like, as\' in older usage.',
     parts:[{t:'چون', tr:'chon', m:'because'}],
     tags:['connectors']},
    {id:'con-ya', term:'یا', tr:'yā', en:'Or', memo:'yā = or. Think \'yeah, or...\'. chāi yā ghahve = tea or coffee.',
     parts:[{t:'یا', tr:'yā', m:'or'}],
     tags:['connectors'],
     ex:{term:'چای یا قهوه؟', tr:'chāi yā ghahve?', en:'Tea or coffee?'}},
    {id:'con-ham', term:'هم', tr:'ham', en:'Also / Too', memo:'ham = also, too. Think \'ham too, please\'. man ham = me too. Also the prefix for \'same, together\' (hamkār = colleague).',
     parts:[{t:'هم', tr:'ham', m:'also, too'}],
     tags:['connectors'],
     ex:{term:'من هم.', tr:'man ham.', en:'Me too.'}},
    {id:'con-bad', term:'بعد', tr:'ba\'d', en:'Then / After', memo:'ba\'d = then, after (Arabic). The root of ba\'dan (later). Say it with a tiny catch: ba-\'d.',
     parts:[{t:'بعد', tr:'ba\'d', m:'then, after'}],
     tags:['connectors']},
    {id:'con-age', term:'اگه', tr:'age', en:'If', memo:'age = if (written agar). Think \'age, if you\'re old enough\'.',
     parts:[{t:'اگه', tr:'age', m:'if'}],
     tags:['connectors'],
     note:'Written: اگر (agar).'},
    {id:'con-pas', term:'پس', tr:'pas', en:'So / Then', memo:'pas = so, then, therefore. Also \'behind\'. Think \'pass on, so then\'.',
     parts:[{t:'پس', tr:'pas', m:'so, then'}],
     tags:['connectors']},
    {id:'con-khob', term:'خب', tr:'khob', en:'Well...', memo:'khob = well... the same khub (good) used as a filler to start a sentence, like English \'well\'.',
     parts:[{t:'خب', tr:'khob', m:'well... (filler)'}],
     tags:['connectors'],
     note:'The filler to start a sentence.'},
    {id:'con-yani', term:'یعنی', tr:'ya\'ni', en:'That is / I mean', memo:'ya\'ni = that is, I mean (Arabic \'it means\'). The ya\'ni of ya\'ni chi. Iranians say it every few sentences.',
     parts:[{t:'یعنی', tr:'ya\'ni', m:'that is, I mean'}],
     tags:['connectors']},
  ],
};
