/* farsi.js — the Conversational Farsi (Persian) deck for /anki.
 *
 * Registered in anki/decks/index.js. Read the header of greek.js for the editing
 * rules: append only, never rename or reuse an id, bump version and updated,
 * run `node anki/deck.test.js` before committing.
 *
 * Spoken Tehrani Persian, the way people actually talk (می‌خوام not می‌خواهم),
 * with the written form in a note where it differs.
 * TRANSLITERATION: ā = long "aa" (آب → āb), a = short (like "cat"), e, o, i, u.
 * kh (خ), gh (غ/ق), sh, ch, zh (ژ), ' for ع/ء. The ezāfe link is written -e.
 * Fields: id, term (Persian script), tr, en, tags, note?, ex?{term,tr,en}
 */
window.DECKS = window.DECKS || {};
window.DECKS.farsi = {
  id: 'farsi',
  name: 'Conversational Farsi',
  version: 1,
  updated: '2026-10-01',

  notes: [
    /* ---------------- GREETINGS ---------------- */
    {id:'greet-salam', term:'سلام', tr:'salām', en:'Hello / Hi', tags:['greetings']},
    {id:'greet-sobh-bekheir', term:'صبح بخیر', tr:'sobh bekheir', en:'Good morning', tags:['greetings']},
    {id:'greet-shab-bekheir', term:'شب بخیر', tr:'shab bekheir', en:'Good evening / Good night', tags:['greetings'],
     note:'Used for both.'},
    {id:'greet-khodahafez', term:'خداحافظ', tr:'khodāhāfez', en:'Goodbye', tags:['greetings'],
     note:'Literally "God protect you". Casual: خدافظ (khodāfez).'},
    {id:'greet-chetori', term:'چطوری؟', tr:'chetori?', en:'How are you? (informal)', tags:['greetings']},
    {id:'greet-shoma-chetorid', term:'شما چطورید؟', tr:'shomā chetorid?', en:'How are you? (formal)', tags:['greetings']},
    {id:'greet-khubam', term:'خوبم، مرسی', tr:'khubam, mersi', en:'I\'m fine, thanks', tags:['greetings'],
     ex:{term:'خوبم، مرسی. تو چطوری؟', tr:'khubam, mersi. to chetori?', en:'I\'m fine, thanks. And you?'}},
    {id:'greet-khosh-amadid', term:'خوش آمدید', tr:'khosh āmadid', en:'Welcome', tags:['greetings']},
    {id:'greet-khoshbakhtam', term:'خوشبختم', tr:'khoshbakhtam', en:'Nice to meet you', tags:['greetings']},
    {id:'greet-felan', term:'فعلاً', tr:'fe\'lan', en:'See you (for now)', tags:['greetings']},
    {id:'greet-be-salamat', term:'به سلامت', tr:'be salāmat', en:'Safe travels / Goodbye', tags:['greetings'],
     note:'Said to the person who is leaving.'},
    {id:'greet-esmam', term:'اسمم ... است', tr:'esmam ... ast', en:'My name is ...', tags:['greetings'],
     note:'Spoken: اسمم سامه (esmam Sām-e).',
     ex:{term:'اسمم سام است.', tr:'esmam Sām ast.', en:'My name is Sam.'}},
    {id:'greet-esmet-chie', term:'اسمت چیه؟', tr:'esmet chie?', en:'What\'s your name? (informal)', tags:['greetings'],
     note:'Formal: اسم شما چیست؟ (esm-e shomā chist?)'},

    /* ---------------- POLITENESS ---------------- */
    {id:'pol-mersi', term:'مرسی', tr:'mersi', en:'Thanks', tags:['politeness'],
     note:'Borrowed from French and used all day.'},
    {id:'pol-mamnun', term:'ممنون', tr:'mamnun', en:'Thank you', tags:['politeness'],
     ex:{term:'خیلی ممنون.', tr:'kheili mamnun.', en:'Thank you very much.'}},
    {id:'pol-khahesh-mikonam', term:'خواهش می‌کنم', tr:'khāhesh mikonam', en:'You\'re welcome / Please', tags:['politeness'],
     note:'The reply to thanks, and a polite "please".'},
    {id:'pol-lotfan', term:'لطفاً', tr:'lotfan', en:'Please', tags:['politeness'],
     ex:{term:'لطفاً آب.', tr:'lotfan āb.', en:'Water, please.'}},
    {id:'pol-bebakhshid', term:'ببخشید', tr:'bebakhshid', en:'Excuse me / Sorry', tags:['politeness'],
     note:'For getting attention and for apologies.'},
    {id:'pol-moteassefam', term:'متأسفم', tr:'mote\'assefam', en:'I\'m sorry (regret)', tags:['politeness']},
    {id:'pol-befarmaid', term:'بفرمایید', tr:'befarmāid', en:'Please (go ahead / here you are / come in)', tags:['politeness'],
     note:'The host\'s word for everything.'},
    {id:'pol-ghabel-nadare', term:'قابل نداره', tr:'ghābel nadāre', en:'It\'s nothing (shopkeeper refusing payment)', tags:['politeness','shopping'],
     note:'Tārof ritual. You insist and pay anyway.'},
    {id:'pol-dast-shoma-dard-nakone', term:'دست شما درد نکنه', tr:'dast-e shomā dard nakone', en:'Thank you (for effort)', tags:['politeness'],
     note:'Literally "may your hand not hurt".'},
    {id:'pol-be-salamati', term:'به سلامتی', tr:'be salāmati', en:'Cheers / To your health', tags:['politeness','food']},
    {id:'pol-chashm', term:'چشم', tr:'chashm', en:'Certainly / Will do', tags:['politeness'],
     note:'Literally "eye". The polite yes to a request.'},

    /* ---------------- BASICS ---------------- */
    {id:'bas-bale', term:'بله', tr:'bale', en:'Yes', tags:['basics'],
     note:'Casual: آره (āre).'},
    {id:'bas-na', term:'نه', tr:'na', en:'No', tags:['basics'],
     note:'Polite: نخیر (nakheir).'},
    {id:'bas-bashe', term:'باشه', tr:'bāshe', en:'OK', tags:['basics']},
    {id:'bas-khub', term:'خوب', tr:'khub', en:'Good / Well', tags:['basics']},
    {id:'bas-shayad', term:'شاید', tr:'shāyad', en:'Maybe', tags:['basics']},
    {id:'bas-hatman', term:'حتماً', tr:'hatman', en:'Certainly / Of course', tags:['basics']},
    {id:'bas-nemidunam', term:'نمی‌دونم', tr:'nemidunam', en:'I don\'t know', tags:['basics','verbs'],
     note:'Written: نمی‌دانم (nemidānam).'},
    {id:'bas-ali', term:'عالی', tr:'āli', en:'Excellent', tags:['basics']},
    {id:'bas-kheili', term:'خیلی', tr:'kheili', en:'Very / A lot', tags:['basics'],
     ex:{term:'خیلی خوب', tr:'kheili khub', en:'Very good'}},
    {id:'bas-ye-kam', term:'یه کم', tr:'ye kam', en:'A little bit', tags:['basics'],
     ex:{term:'یه کم فارسی بلدم.', tr:'ye kam fārsi baladam.', en:'I know a little Persian.'}},
    {id:'bas-moshkeli-nist', term:'مشکلی نیست', tr:'moshkeli nist', en:'No problem', tags:['basics']},

    /* ---------------- NUMBERS ---------------- */
    {id:'num-yek', term:'یک', tr:'yek', en:'One', tags:['numbers'],
     note:'Spoken: یه (ye) before a noun.'},
    {id:'num-do', term:'دو', tr:'do', en:'Two', tags:['numbers']},
    {id:'num-se', term:'سه', tr:'se', en:'Three', tags:['numbers']},
    {id:'num-chahar', term:'چهار', tr:'chahār', en:'Four', tags:['numbers']},
    {id:'num-panj', term:'پنج', tr:'panj', en:'Five', tags:['numbers']},
    {id:'num-shesh', term:'شش', tr:'shesh', en:'Six', tags:['numbers']},
    {id:'num-haft', term:'هفت', tr:'haft', en:'Seven', tags:['numbers']},
    {id:'num-hasht', term:'هشت', tr:'hasht', en:'Eight', tags:['numbers']},
    {id:'num-noh', term:'نه', tr:'noh', en:'Nine', tags:['numbers'],
     note:'Spelled like "no" (na). The vowel tells them apart.'},
    {id:'num-dah', term:'ده', tr:'dah', en:'Ten', tags:['numbers']},
    {id:'num-bist', term:'بیست', tr:'bist', en:'Twenty', tags:['numbers']},
    {id:'num-sad', term:'صد', tr:'sad', en:'One hundred', tags:['numbers']},
    {id:'num-hezar', term:'هزار', tr:'hezār', en:'One thousand', tags:['numbers'],
     ex:{term:'ده هزار تومان', tr:'dah hezār tomān', en:'Ten thousand tomans'}},

    /* ---------------- QUESTION WORDS ---------------- */
    {id:'q-chi', term:'چی؟', tr:'chi?', en:'What?', tags:['questions'],
     ex:{term:'این چیه؟', tr:'in chie?', en:'What is this?'}},
    {id:'q-koja', term:'کجا؟', tr:'kojā?', en:'Where?', tags:['questions'],
     ex:{term:'دستشویی کجاست؟', tr:'dastshui kojāst?', en:'Where is the toilet?'}},
    {id:'q-key', term:'کی؟', tr:'key?', en:'When?', tags:['questions'],
     note:'Spelled like "who" (ki). The vowel differs.'},
    {id:'q-chera', term:'چرا؟', tr:'cherā?', en:'Why?', tags:['questions']},
    {id:'q-chetor', term:'چطور؟', tr:'chetor?', en:'How?', tags:['questions']},
    {id:'q-ki', term:'کی؟', tr:'ki?', en:'Who?', tags:['questions']},
    {id:'q-chand', term:'چند؟', tr:'chand?', en:'How much / How many?', tags:['questions','shopping']},
    {id:'q-kodum', term:'کدوم؟', tr:'kodum?', en:'Which one?', tags:['questions'],
     note:'Written: کدام (kodām).'},

    /* ---------------- PRONOUNS ---------------- */
    {id:'pro-man', term:'من', tr:'man', en:'I', tags:['pronouns']},
    {id:'pro-to', term:'تو', tr:'to', en:'You (informal)', tags:['pronouns']},
    {id:'pro-shoma', term:'شما', tr:'shomā', en:'You (formal or plural)', tags:['pronouns']},
    {id:'pro-u', term:'او', tr:'u', en:'He / She', tags:['pronouns'],
     note:'Persian pronouns have no gender. Spoken: اون (un).'},
    {id:'pro-ma', term:'ما', tr:'mā', en:'We', tags:['pronouns']},
    {id:'pro-unha', term:'اون‌ها', tr:'unhā', en:'They', tags:['pronouns'],
     note:'Written: آن‌ها (ānhā).'},
    {id:'pro-in', term:'این', tr:'in', en:'This', tags:['pronouns']},
    {id:'pro-un', term:'اون', tr:'un', en:'That', tags:['pronouns']},
    {id:'pro-e-man', term:'ـِ من', tr:'-e man', en:'My (after the noun)', tags:['pronouns'],
     note:'The ezāfe -e links a noun to its owner.',
     ex:{term:'کتاب من', tr:'ketāb-e man', en:'My book'}},
    {id:'pro-am', term:'ـم', tr:'-am', en:'My (suffix, spoken)', tags:['pronouns'],
     ex:{term:'اسمم', tr:'esmam', en:'My name'}},

    /* ---------------- TIME ---------------- */
    {id:'time-emruz', term:'امروز', tr:'emruz', en:'Today', tags:['time']},
    {id:'time-farda', term:'فردا', tr:'fardā', en:'Tomorrow', tags:['time']},
    {id:'time-diruz', term:'دیروز', tr:'diruz', en:'Yesterday', tags:['time']},
    {id:'time-alan', term:'الان', tr:'alān', en:'Now', tags:['time']},
    {id:'time-badan', term:'بعداً', tr:'ba\'dan', en:'Later', tags:['time']},
    {id:'time-saat-chande', term:'ساعت چنده؟', tr:'sā\'at chande?', en:'What time is it?', tags:['time','questions']},
    {id:'time-sobh', term:'صبح', tr:'sobh', en:'Morning', tags:['time']},
    {id:'time-shab', term:'شب', tr:'shab', en:'Night', tags:['time']},
    {id:'time-shanbe', term:'شنبه', tr:'shanbe', en:'Saturday', tags:['time'],
     note:'The week starts on Saturday: شنبه، یکشنبه، دوشنبه، سه‌شنبه، چهارشنبه، پنجشنبه، جمعه.'},
    {id:'time-jome', term:'جمعه', tr:'jom\'e', en:'Friday', tags:['time'],
     note:'The weekend day.'},
    {id:'time-akhar-e-hafte', term:'آخر هفته', tr:'ākhar-e hafte', en:'Weekend', tags:['time']},

    /* ---------------- FOOD & ORDERING ---------------- */
    {id:'food-ab', term:'آب', tr:'āb', en:'Water', tags:['food'],
     ex:{term:'یه آب لطفاً.', tr:'ye āb lotfan.', en:'A water, please.'}},
    {id:'food-chai', term:'چای', tr:'chāi', en:'Tea', tags:['food'],
     note:'The national drink, served constantly.'},
    {id:'food-ghahve', term:'قهوه', tr:'ghahve', en:'Coffee', tags:['food']},
    {id:'food-nun', term:'نون', tr:'nun', en:'Bread', tags:['food'],
     note:'Written: نان (nān).'},
    {id:'food-berenj', term:'برنج', tr:'berenj', en:'Rice', tags:['food'],
     note:'Cooked rice on the plate is پلو (polo).'},
    {id:'food-khoshmaze', term:'خوشمزه', tr:'khoshmaze', en:'Delicious', tags:['food'],
     ex:{term:'خیلی خوشمزه است.', tr:'kheili khoshmaze ast.', en:'It\'s very tasty.'}},
    {id:'food-surat-hesab', term:'صورت‌حساب لطفاً', tr:'surat-hesāb lotfan', en:'The bill, please', tags:['food']},
    {id:'food-meno', term:'منو لطفاً', tr:'meno lotfan', en:'The menu, please', tags:['food']},
    {id:'food-gorosname', term:'گرسنمه', tr:'gorosname', en:'I\'m hungry', tags:['food','feelings'],
     note:'Written: گرسنه هستم (gorosne hastam).'},
    {id:'food-teshname', term:'تشنمه', tr:'teshname', en:'I\'m thirsty', tags:['food','feelings']},
    {id:'food-bedun', term:'بدون', tr:'bedun', en:'Without', tags:['food'],
     ex:{term:'بدون شکر', tr:'bedun-e shekar', en:'Without sugar'}},
    {id:'food-ba', term:'با', tr:'bā', en:'With', tags:['food'],
     ex:{term:'با شیر', tr:'bā shir', en:'With milk'}},
    {id:'food-miz-baraye-do', term:'یه میز برای دو نفر', tr:'ye miz barāye do nafar', en:'A table for two', tags:['food']},
    {id:'food-nush-e-jan', term:'نوش جان', tr:'nush-e jān', en:'Enjoy your meal', tags:['food','politeness'],
     note:'Also the reply when someone thanks you for food.'},

    /* ---------------- PLACES & DIRECTIONS ---------------- */
    {id:'place-kojast', term:'... کجاست؟', tr:'... kojāst?', en:'Where is ...?', tags:['places','questions'],
     ex:{term:'ایستگاه مترو کجاست؟', tr:'istgāh-e metro kojāst?', en:'Where is the metro station?'}},
    {id:'place-chap', term:'چپ', tr:'chap', en:'Left', tags:['places']},
    {id:'place-rast', term:'راست', tr:'rāst', en:'Right', tags:['places']},
    {id:'place-mostaghim', term:'مستقیم', tr:'mostaghim', en:'Straight ahead', tags:['places']},
    {id:'place-inja', term:'اینجا', tr:'injā', en:'Here', tags:['places']},
    {id:'place-unja', term:'اونجا', tr:'unjā', en:'There', tags:['places']},
    {id:'place-nazdik', term:'نزدیک', tr:'nazdik', en:'Near', tags:['places'],
     ex:{term:'نزدیکه؟', tr:'nazdike?', en:'Is it near?'}},
    {id:'place-dur', term:'دور', tr:'dur', en:'Far', tags:['places']},
    {id:'place-forudgah', term:'فرودگاه', tr:'forudgāh', en:'Airport', tags:['places']},
    {id:'place-dastshui', term:'دستشویی', tr:'dastshui', en:'Toilet', tags:['places']},
    {id:'place-bazar', term:'بازار', tr:'bāzār', en:'Bazaar / Market', tags:['places']},
    {id:'place-khiyaban', term:'خیابان', tr:'khiyābān', en:'Street', tags:['places']},

    /* ---------------- SHOPPING & MONEY ---------------- */
    {id:'shop-chande', term:'چنده؟', tr:'chande?', en:'How much is it?', tags:['shopping']},
    {id:'shop-gerun', term:'گرون', tr:'gerun', en:'Expensive', tags:['shopping'],
     note:'Written: گران (gerān).'},
    {id:'shop-arzun', term:'ارزون', tr:'arzun', en:'Cheap', tags:['shopping'],
     note:'Written: ارزان (arzān).'},
    {id:'shop-ba-kart', term:'با کارت', tr:'bā kārt', en:'By card', tags:['shopping']},
    {id:'shop-naghd', term:'نقد', tr:'naghd', en:'Cash', tags:['shopping']},
    {id:'shop-pul', term:'پول', tr:'pul', en:'Money', tags:['shopping']},
    {id:'shop-toman', term:'تومان', tr:'tomān', en:'Toman', tags:['shopping'],
     note:'Prices are quoted in tomans. One toman is ten rials.'},
    {id:'shop-hamin-o-mikham', term:'همین رو می‌خوام', tr:'hamin ro mikhām', en:'I\'ll take this one', tags:['shopping']},
    {id:'shop-faghat-negah', term:'فقط نگاه می‌کنم', tr:'faghat negāh mikonam', en:'Just looking', tags:['shopping']},
    {id:'shop-takhfif', term:'تخفیف', tr:'takhfif', en:'Discount', tags:['shopping'],
     ex:{term:'تخفیف داره؟', tr:'takhfif dāre?', en:'Is there a discount?'}},

    /* ---------------- FEELINGS & SMALL TALK ---------------- */
    {id:'feel-khoshhalam', term:'خوشحالم', tr:'khoshhālam', en:'I\'m happy', tags:['feelings']},
    {id:'feel-khaste-am', term:'خسته‌ام', tr:'khaste-am', en:'I\'m tired', tags:['feelings']},
    {id:'feel-hava-garme', term:'هوا گرمه', tr:'havā garme', en:'It\'s hot (weather)', tags:['feelings','time']},
    {id:'feel-hava-sarde', term:'هوا سرده', tr:'havā sarde', en:'It\'s cold (weather)', tags:['feelings','time']},
    {id:'feel-dust-daram', term:'دوست دارم', tr:'dust dāram', en:'I like it / I love it', tags:['feelings','verbs'],
     ex:{term:'ایران رو دوست دارم.', tr:'Irān ro dust dāram.', en:'I like Iran.'}},
    {id:'feel-dust-nadaram', term:'دوست ندارم', tr:'dust nadāram', en:'I don\'t like it', tags:['feelings','verbs']},
    {id:'feel-khub-nistam', term:'خوب نیستم', tr:'khub nistam', en:'I\'m not well', tags:['feelings']},
    {id:'feel-ghorbunet-beram', term:'قربونت برم', tr:'ghorbunet beram', en:'(term of endearment)', tags:['feelings'],
     note:'Literally "may I be sacrificed for you". Family and friends say it constantly.'},
    {id:'feel-jun', term:'جون', tr:'jun', en:'Dear (after a name)', tags:['feelings'],
     ex:{term:'سام جون', tr:'Sām jun', en:'Dear Sam'}},

    /* ---------------- VERBS (spoken present, I / you) ---------------- */
    {id:'verb-mikham', term:'می‌خوام', tr:'mikhām', en:'I want', tags:['verbs'],
     note:'Written: می‌خواهم (mikhāham).',
     ex:{term:'آب می‌خوام.', tr:'āb mikhām.', en:'I want water.'}},
    {id:'verb-mikhay', term:'می‌خوای؟', tr:'mikhāy?', en:'Do you want?', tags:['verbs'],
     ex:{term:'چای می‌خوای؟', tr:'chāi mikhāy?', en:'Do you want tea?'}},
    {id:'verb-daram', term:'دارم', tr:'dāram', en:'I have', tags:['verbs']},
    {id:'verb-dari', term:'داری؟', tr:'dāri?', en:'Do you have?', tags:['verbs'],
     ex:{term:'وقت داری؟', tr:'vaght dāri?', en:'Do you have time?'}},
    {id:'verb-miram', term:'می‌رم', tr:'miram', en:'I go', tags:['verbs'],
     ex:{term:'خونه می‌رم.', tr:'khune miram.', en:'I\'m going home.'}},
    {id:'verb-miri', term:'می‌ری؟', tr:'miri?', en:'Are you going?', tags:['verbs'],
     ex:{term:'کجا می‌ری؟', tr:'kojā miri?', en:'Where are you going?'}},
    {id:'verb-mifahmam', term:'می‌فهمم', tr:'mifahmam', en:'I understand', tags:['verbs']},
    {id:'verb-mifahmi', term:'می‌فهمی؟', tr:'mifahmi?', en:'Do you understand?', tags:['verbs']},
    {id:'verb-midunam', term:'می‌دونم', tr:'midunam', en:'I know', tags:['verbs']},
    {id:'verb-mitunam', term:'می‌تونم', tr:'mitunam', en:'I can', tags:['verbs']},
    {id:'verb-mituni', term:'می‌تونی؟', tr:'mituni?', en:'Can you?', tags:['verbs'],
     ex:{term:'می‌تونی کمکم کنی؟', tr:'mituni komakam koni?', en:'Can you help me?'}},
    {id:'verb-hastam', term:'هستم', tr:'hastam', en:'I am', tags:['verbs'],
     ex:{term:'من آمریکایی هستم.', tr:'man āmrikāi hastam.', en:'I\'m American.'}},
    {id:'verb-hasti', term:'هستی؟', tr:'hasti?', en:'Are you?', tags:['verbs'],
     ex:{term:'اهل کجا هستی؟', tr:'ahl-e kojā hasti?', en:'Where are you from?'}},
    {id:'verb-harf-mizanam', term:'حرف می‌زنم', tr:'harf mizanam', en:'I speak', tags:['verbs'],
     ex:{term:'یه کم فارسی حرف می‌زنم.', tr:'ye kam fārsi harf mizanam.', en:'I speak a little Persian.'}},
    {id:'verb-berim', term:'بریم', tr:'berim', en:'Let\'s go', tags:['verbs']},
    {id:'verb-biya', term:'بیا', tr:'biyā', en:'Come (here)', tags:['verbs']},

    /* ---------------- SURVIVAL ---------------- */
    {id:'surv-nemifahmam', term:'نمی‌فهمم', tr:'nemifahmam', en:'I don\'t understand', tags:['survival']},
    {id:'surv-yavash-tar', term:'یواش‌تر لطفاً', tr:'yavāsh-tar lotfan', en:'Slower, please', tags:['survival']},
    {id:'surv-englisi-baladid', term:'انگلیسی بلدید؟', tr:'englisi baladid?', en:'Do you speak English?', tags:['survival'],
     note:'بلد بودن = to know how.'},
    {id:'surv-farsi-balad-nistam', term:'فارسی خوب بلد نیستم', tr:'fārsi khub balad nistam', en:'I don\'t speak Persian well', tags:['survival']},
    {id:'surv-be-farsi-chi-migan', term:'به فارسی چی می‌گن؟', tr:'be fārsi chi migan?', en:'How do you say it in Persian?', tags:['survival']},
    {id:'surv-yani-chi', term:'یعنی چی؟', tr:'ya\'ni chi?', en:'What does it mean?', tags:['survival']},
    {id:'surv-dobare', term:'دوباره لطفاً', tr:'dobāre lotfan', en:'Again, please', tags:['survival']},
    {id:'surv-ye-lahze', term:'یه لحظه', tr:'ye lahze', en:'One moment', tags:['survival']},
    {id:'surv-komak', term:'کمک!', tr:'komak!', en:'Help!', tags:['survival']},

    /* ---------------- CONNECTORS ---------------- */
    {id:'con-va', term:'و', tr:'va', en:'And', tags:['connectors'],
     note:'Spoken as -o glued to the first word: nun-o panir.',
     ex:{term:'چای و نون', tr:'chāi-o nun', en:'Tea and bread'}},
    {id:'con-vali', term:'ولی', tr:'vali', en:'But', tags:['connectors']},
    {id:'con-chon', term:'چون', tr:'chon', en:'Because', tags:['connectors']},
    {id:'con-ya', term:'یا', tr:'yā', en:'Or', tags:['connectors'],
     ex:{term:'چای یا قهوه؟', tr:'chāi yā ghahve?', en:'Tea or coffee?'}},
    {id:'con-ham', term:'هم', tr:'ham', en:'Also / Too', tags:['connectors'],
     ex:{term:'من هم.', tr:'man ham.', en:'Me too.'}},
    {id:'con-bad', term:'بعد', tr:'ba\'d', en:'Then / After', tags:['connectors']},
    {id:'con-age', term:'اگه', tr:'age', en:'If', tags:['connectors'],
     note:'Written: اگر (agar).'},
    {id:'con-pas', term:'پس', tr:'pas', en:'So / Then', tags:['connectors']},
    {id:'con-khob', term:'خب', tr:'khob', en:'Well...', tags:['connectors'],
     note:'The filler to start a sentence.'},
    {id:'con-yani', term:'یعنی', tr:'ya\'ni', en:'That is / I mean', tags:['connectors']},
  ],
};
