/* greek.js — the Conversational Greek deck for /anki.
 *
 * HOW CARDS GET HERE
 *   Sam asks Claude for new cards in a Claude Code session. Claude appends notes
 *   to `notes` below, runs `node anki/deck.test.js`, commits, and pushes to main.
 *   Vercel deploys from main, and vercel.json serves this folder with no-cache so
 *   the phone sees the new deck on the next load. Study progress never lives
 *   here: it stays in the browser (localStorage key sam_anki_v1), keyed by deck
 *   id and note id, so a deck push only ever ADDS cards.
 *   This deck is registered in anki/decks/index.js; new decks go there too.
 *
 * RULES FOR EDITING (Claude: read these before touching the file)
 *   - APPEND new notes at the end of the relevant theme block, or add a new block.
 *   - NEVER rename or reuse an `id`. Progress is keyed on `<id>:fwd` (Greek→English)
 *     and `<id>:rev` (English→Greek). A renamed id resets both cards to new.
 *   - Editing el / tr / en / note / ex of an existing note is fine; progress is kept.
 *   - To retire a note, delete it. Its saved progress is kept but hidden. Do not
 *     recycle the id for something else.
 *   - Bump `version` (+1) and `updated` (YYYY-MM-DD) on every change.
 *   - id format: `<theme>-<slug>`, lowercase a-z, 0-9 and hyphens, e.g. greet-kalimera.
 *   - Fields: id, term (Greek script), tr (transliteration), en (English), tags (array),
 *     optional note (one line of usage), optional ex {term, tr, en} (example sentence).
 *
 * TRANSLITERATION (keep it the way you would read it aloud)
 *   stress marked with an acute: á é í ó ú        β→v  δ→d  θ→th  χ→ch  ξ→x  ψ→ps  ζ→z
 *   γ→g, but y before e/i sounds (γεια→ya, γιατί→yatí)    ου→ou  αι→e  ει/οι/υ/η→i
 *   μπ→b at the start, mb inside    ντ→d at the start, nd inside    γκ/γγ→g / ng
 *   Greek question mark is ; — keep it in `term`, and use ? in `tr` and `en`.
 */
window.DECKS = window.DECKS || {};
window.DECKS.greek = {
  id: 'greek',
  name: 'Conversational Greek',
  version: 1,
  updated: '2026-10-01',

  notes: [
    /* ---------------- GREETINGS ---------------- */
    {id:'greet-kalimera', term:'Καλημέρα', tr:'kaliméra', en:'Good morning', tags:['greetings'],
     note:'Used until early afternoon.',
     ex:{term:'Καλημέρα σας!', tr:'kaliméra sas!', en:'Good morning (formal)!'}},
    {id:'greet-kalispera', term:'Καλησπέρα', tr:'kalispéra', en:'Good evening', tags:['greetings'],
     note:'The greeting from late afternoon on. For parting, use καλό βράδυ.'},
    {id:'greet-kalinychta', term:'Καληνύχτα', tr:'kaliníchta', en:'Good night', tags:['greetings'],
     note:'Only when leaving for the night or going to bed.'},
    {id:'greet-yasou', term:'Γεια σου', tr:'ya sou', en:'Hi / Bye (informal)', tags:['greetings'],
     note:'To one person you know. Works for hello and goodbye. Just "γεια" is fine too.',
     ex:{term:'Γεια σου, Μαρία!', tr:'ya sou, María!', en:'Hi, Maria!'}},
    {id:'greet-yasas', term:'Γεια σας', tr:'ya sas', en:'Hello / Goodbye (formal or plural)', tags:['greetings'],
     note:'To a stranger, an older person, or a group.'},
    {id:'greet-ti-kanis', term:'Τι κάνεις;', tr:'ti kánis?', en:'How are you? (informal)', tags:['greetings'],
     note:'Literally "what are you doing?". The Greek question mark is a semicolon.',
     ex:{term:'Τι κάνεις; Καλά;', tr:'ti kánis? kalá?', en:'How are you? Good?'}},
    {id:'greet-ti-kanete', term:'Τι κάνετε;', tr:'ti kánete?', en:'How are you? (formal)', tags:['greetings']},
    {id:'greet-kala-esi', term:'Καλά, εσύ;', tr:'kalá, esí?', en:'Fine, and you?', tags:['greetings'],
     note:'The standard answer to τι κάνεις.'},
    {id:'greet-adio', term:'Αντίο', tr:'adío', en:'Goodbye', tags:['greetings'],
     note:'A little formal. "Γεια" is more common day to day.'},
    {id:'greet-ta-leme', term:'Τα λέμε', tr:'ta léme', en:'See you', tags:['greetings'],
     note:'Literally "we will talk". Very common.',
     ex:{term:'Τα λέμε αύριο!', tr:'ta léme ávrio!', en:'See you tomorrow!'}},
    {id:'greet-kalo-vradi', term:'Καλό βράδυ', tr:'kaló vrádi', en:'Have a good evening', tags:['greetings'],
     note:'Said when parting in the evening.'},
    {id:'greet-kali-orexi', term:'Καλή όρεξη', tr:'kalí órexi', en:'Enjoy your meal', tags:['greetings','food'],
     note:'Said by waiters and by everyone at the table. Reply: επίσης (likewise).'},

    /* ---------------- POLITENESS ---------------- */
    {id:'pol-efcharisto', term:'Ευχαριστώ', tr:'efcharistó', en:'Thank you', tags:['politeness'],
     ex:{term:'Ευχαριστώ πολύ!', tr:'efcharistó polí!', en:'Thank you very much!'}},
    {id:'pol-parakalo', term:'Παρακαλώ', tr:'parakaló', en:'Please / You\'re welcome', tags:['politeness'],
     note:'One word, many jobs: please, you\'re welcome, "can I help you?", "come in".'},
    {id:'pol-signomi', term:'Συγγνώμη', tr:'signómi', en:'Sorry / Excuse me', tags:['politeness'],
     note:'Both for apologising and for getting attention.'},
    {id:'pol-me-sinchorite', term:'Με συγχωρείτε', tr:'me sinchoríte', en:'Excuse me (formal)', tags:['politeness'],
     note:'To get past someone, or to call a waiter.'},
    {id:'pol-tipota', term:'Τίποτα', tr:'típota', en:'It\'s nothing / Nothing', tags:['politeness','basics'],
     note:'The usual reply to ευχαριστώ, and also the word for "nothing".'},
    {id:'pol-charika', term:'Χάρηκα', tr:'chárika', en:'Nice to meet you', tags:['politeness'],
     note:'Literally "I was glad".',
     ex:{term:'Χάρηκα πολύ.', tr:'chárika polí.', en:'Very nice to meet you.'}},
    {id:'pol-me-lene', term:'Με λένε...', tr:'me léne...', en:'My name is...', tags:['politeness'],
     note:'Literally "they call me".',
     ex:{term:'Με λένε Σαμ.', tr:'me léne Sam.', en:'My name is Sam.'}},
    {id:'pol-pos-se-lene', term:'Πώς σε λένε;', tr:'pos se léne?', en:'What\'s your name? (informal)', tags:['politeness'],
     note:'Formal: Πώς σας λένε; (pos sas léne?)'},
    {id:'pol-stin-iyia-mas', term:'Στην υγειά μας', tr:'stin iyá mas', en:'Cheers', tags:['politeness','food'],
     note:'Literally "to our health". Short form: Γεια μας! (ya mas!)'},

    /* ---------------- BASICS ---------------- */
    {id:'bas-ne', term:'Ναι', tr:'ne', en:'Yes', tags:['basics'],
     note:'Sounds like "nay" but means yes.'},
    {id:'bas-ochi', term:'Όχι', tr:'óchi', en:'No', tags:['basics'],
     note:'Often with a small upward tilt of the head.'},
    {id:'bas-endaxi', term:'Εντάξει', tr:'endáxi', en:'OK / All right', tags:['basics'],
     ex:{term:'Εντάξει, πάμε.', tr:'endáxi, páme.', en:'OK, let\'s go.'}},
    {id:'bas-kala', term:'Καλά', tr:'kalá', en:'Fine / Well', tags:['basics'],
     note:'The answer to "how are you", and the adverb "well".'},
    {id:'bas-isos', term:'Ίσως', tr:'ísos', en:'Maybe', tags:['basics']},
    {id:'bas-vevea', term:'Βέβαια', tr:'vévea', en:'Of course', tags:['basics'],
     note:'Also βεβαίως (vevéos), slightly more formal.'},
    {id:'bas-den-xero', term:'Δεν ξέρω', tr:'den xéro', en:'I don\'t know', tags:['basics','verbs'],
     note:'δεν before a verb makes it negative.'},
    {id:'bas-orea', term:'Ωραία', tr:'oréa', en:'Nice / Great', tags:['basics'],
     note:'Everyday approval. ωραίο for a thing, ωραία for a situation.'},
    {id:'bas-poli', term:'Πολύ', tr:'polí', en:'Very / A lot', tags:['basics'],
     ex:{term:'Πολύ ωραία!', tr:'polí oréa!', en:'Very nice!'}},
    {id:'bas-ligo', term:'Λίγο', tr:'lígo', en:'A little', tags:['basics'],
     ex:{term:'Μιλάω λίγο ελληνικά.', tr:'miláo lígo elliniká.', en:'I speak a little Greek.'}},

    /* ---------------- NUMBERS ---------------- */
    {id:'num-ena', term:'Ένα', tr:'éna', en:'One', tags:['numbers'],
     note:'Also "a / an" (neuter). Masculine ένας (énas), feminine μία (mía).'},
    {id:'num-dio', term:'Δύο', tr:'dío', en:'Two', tags:['numbers']},
    {id:'num-tria', term:'Τρία', tr:'tría', en:'Three', tags:['numbers'],
     note:'Masculine and feminine: τρεις (tris).'},
    {id:'num-tessera', term:'Τέσσερα', tr:'téssera', en:'Four', tags:['numbers'],
     note:'Masculine and feminine: τέσσερις (tésseris).'},
    {id:'num-pende', term:'Πέντε', tr:'pénde', en:'Five', tags:['numbers']},
    {id:'num-exi', term:'Έξι', tr:'éxi', en:'Six', tags:['numbers']},
    {id:'num-epta', term:'Επτά', tr:'eptá', en:'Seven', tags:['numbers'],
     note:'In speech often εφτά (eftá).'},
    {id:'num-okto', term:'Οκτώ', tr:'októ', en:'Eight', tags:['numbers'],
     note:'In speech often οχτώ (ochtó).'},
    {id:'num-ennea', term:'Εννέα', tr:'ennéa', en:'Nine', tags:['numbers'],
     note:'In speech often εννιά (enniá).'},
    {id:'num-deka', term:'Δέκα', tr:'déka', en:'Ten', tags:['numbers']},
    {id:'num-ikosi', term:'Είκοσι', tr:'íkosi', en:'Twenty', tags:['numbers']},
    {id:'num-peninda', term:'Πενήντα', tr:'penínda', en:'Fifty', tags:['numbers']},
    {id:'num-ekato', term:'Εκατό', tr:'ekató', en:'One hundred', tags:['numbers']},

    /* ---------------- QUESTION WORDS ---------------- */
    {id:'q-ti', term:'Τι;', tr:'ti?', en:'What?', tags:['questions'],
     ex:{term:'Τι είναι αυτό;', tr:'ti íne aftó?', en:'What is this?'}},
    {id:'q-pou', term:'Πού;', tr:'pou?', en:'Where?', tags:['questions'],
     ex:{term:'Πού είναι η τουαλέτα;', tr:'pou íne i toualéta?', en:'Where is the toilet?'}},
    {id:'q-pote', term:'Πότε;', tr:'póte?', en:'When?', tags:['questions']},
    {id:'q-yati', term:'Γιατί;', tr:'yatí?', en:'Why?', tags:['questions'],
     note:'The same word answers the question: γιατί also means "because".'},
    {id:'q-pos', term:'Πώς;', tr:'pos?', en:'How?', tags:['questions']},
    {id:'q-pios', term:'Ποιος;', tr:'pios?', en:'Who?', tags:['questions'],
     note:'Masculine ποιος, feminine ποια (pia), neuter ποιο (pio).'},
    {id:'q-poso', term:'Πόσο;', tr:'póso?', en:'How much?', tags:['questions','shopping']},
    {id:'q-posa', term:'Πόσα;', tr:'pósa?', en:'How many?', tags:['questions'],
     ex:{term:'Πόσα άτομα;', tr:'pósa átoma?', en:'How many people?'}},

    /* ---------------- PRONOUNS ---------------- */
    {id:'pro-ego', term:'Εγώ', tr:'egó', en:'I', tags:['pronouns'],
     note:'Usually dropped; the verb ending says who. Use it for emphasis.'},
    {id:'pro-esi', term:'Εσύ', tr:'esí', en:'You (singular, informal)', tags:['pronouns']},
    {id:'pro-aftos', term:'Αυτός', tr:'aftós', en:'He', tags:['pronouns'],
     note:'Also "this one" (masculine).'},
    {id:'pro-afti', term:'Αυτή', tr:'aftí', en:'She', tags:['pronouns']},
    {id:'pro-afto', term:'Αυτό', tr:'aftó', en:'It / This', tags:['pronouns'],
     ex:{term:'Αυτό, παρακαλώ.', tr:'aftó, parakaló.', en:'This one, please.'}},
    {id:'pro-emis', term:'Εμείς', tr:'emís', en:'We', tags:['pronouns']},
    {id:'pro-esis', term:'Εσείς', tr:'esís', en:'You (plural or formal)', tags:['pronouns']},
    {id:'pro-afti-pl', term:'Αυτοί', tr:'aftí', en:'They (masculine or mixed)', tags:['pronouns'],
     note:'Sounds exactly like "she" (αυτή). Context decides.'},
    {id:'pro-mou', term:'Μου', tr:'mou', en:'My / To me', tags:['pronouns'],
     note:'Possessives come after the noun.',
     ex:{term:'Το όνομά μου', tr:'to ónomá mou', en:'My name'}},
    {id:'pro-sou', term:'Σου', tr:'sou', en:'Your (informal) / To you', tags:['pronouns'],
     ex:{term:'Το τηλέφωνό σου', tr:'to tiléfonó sou', en:'Your phone'}},

    /* ---------------- TIME ---------------- */
    {id:'time-simera', term:'Σήμερα', tr:'símera', en:'Today', tags:['time']},
    {id:'time-avrio', term:'Αύριο', tr:'ávrio', en:'Tomorrow', tags:['time']},
    {id:'time-chthes', term:'Χθες', tr:'chthes', en:'Yesterday', tags:['time'],
     note:'In speech often χτες (chtes).'},
    {id:'time-tora', term:'Τώρα', tr:'tóra', en:'Now', tags:['time']},
    {id:'time-meta', term:'Μετά', tr:'metá', en:'Later / After', tags:['time'],
     ex:{term:'Τα λέμε μετά.', tr:'ta léme metá.', en:'See you later.'}},
    {id:'time-ti-ora', term:'Τι ώρα είναι;', tr:'ti óra íne?', en:'What time is it?', tags:['time','questions']},
    {id:'time-proi', term:'Πρωί', tr:'proí', en:'Morning', tags:['time'],
     ex:{term:'Το πρωί', tr:'to proí', en:'In the morning'}},
    {id:'time-vradi', term:'Βράδυ', tr:'vrádi', en:'Evening / Night', tags:['time']},
    {id:'time-deftera', term:'Δευτέρα', tr:'deftéra', en:'Monday', tags:['time'],
     note:'Literally "second". Days: Δευτέρα, Τρίτη, Τετάρτη, Πέμπτη, Παρασκευή, Σάββατο, Κυριακή.'},
    {id:'time-paraskevi', term:'Παρασκευή', tr:'paraskeví', en:'Friday', tags:['time']},
    {id:'time-savato', term:'Σάββατο', tr:'sávato', en:'Saturday', tags:['time']},
    {id:'time-kiriaki', term:'Κυριακή', tr:'kiriakí', en:'Sunday', tags:['time'],
     note:'Literally "the Lord\'s day".'},
    {id:'time-savatokiriako', term:'Σαββατοκύριακο', tr:'savatokíriako', en:'Weekend', tags:['time'],
     note:'Saturday and Sunday glued into one word.'},

    /* ---------------- FOOD & ORDERING ---------------- */
    {id:'food-kafes', term:'Καφές', tr:'kafés', en:'Coffee', tags:['food'],
     note:'Masculine, so it is έναν καφέ when ordering.',
     ex:{term:'Έναν καφέ, παρακαλώ.', tr:'énan kafé, parakaló.', en:'A coffee, please.'}},
    {id:'food-nero', term:'Νερό', tr:'neró', en:'Water', tags:['food'],
     ex:{term:'Ένα νερό, παρακαλώ.', tr:'éna neró, parakaló.', en:'A water, please.'}},
    {id:'food-krasi', term:'Κρασί', tr:'krasí', en:'Wine', tags:['food'],
     ex:{term:'Ένα ποτήρι κρασί', tr:'éna potíri krasí', en:'A glass of wine'}},
    {id:'food-bira', term:'Μπίρα', tr:'bíra', en:'Beer', tags:['food']},
    {id:'food-psomi', term:'Ψωμί', tr:'psomí', en:'Bread', tags:['food']},
    {id:'food-logariasmo', term:'Τον λογαριασμό, παρακαλώ', tr:'ton logariazmó, parakaló', en:'The bill, please', tags:['food'],
     note:'Miming a signature in the air also works everywhere.'},
    {id:'food-katalogo', term:'Τον κατάλογο, παρακαλώ', tr:'ton katálogo, parakaló', en:'The menu, please', tags:['food'],
     note:'Μενού (menoú) is also understood.'},
    {id:'food-tha-ithela', term:'Θα ήθελα...', tr:'tha íthela...', en:'I would like...', tags:['food','verbs'],
     note:'Politer than θέλω.',
     ex:{term:'Θα ήθελα έναν καφέ.', tr:'tha íthela énan kafé.', en:'I would like a coffee.'}},
    {id:'food-nostimo', term:'Νόστιμο', tr:'nóstimo', en:'Delicious', tags:['food'],
     ex:{term:'Πολύ νόστιμο!', tr:'polí nóstimo!', en:'Very tasty!'}},
    {id:'food-pinao', term:'Πεινάω', tr:'pináo', en:'I\'m hungry', tags:['food','feelings'],
     note:'A verb in Greek: "I hunger".'},
    {id:'food-dipsao', term:'Διψάω', tr:'dipsáo', en:'I\'m thirsty', tags:['food','feelings']},
    {id:'food-choris', term:'Χωρίς', tr:'chorís', en:'Without', tags:['food'],
     ex:{term:'Χωρίς ζάχαρη', tr:'chorís záchari', en:'Without sugar'}},
    {id:'food-me', term:'Με', tr:'me', en:'With', tags:['food'],
     ex:{term:'Με γάλα', tr:'me gála', en:'With milk'}},
    {id:'food-trapezi-ya-dio', term:'Ένα τραπέζι για δύο', tr:'éna trapézi ya dío', en:'A table for two', tags:['food']},

    /* ---------------- PLACES & DIRECTIONS ---------------- */
    {id:'place-pou-ine', term:'Πού είναι...;', tr:'pou íne...?', en:'Where is...?', tags:['places','questions'],
     ex:{term:'Πού είναι ο σταθμός;', tr:'pou íne o stathmós?', en:'Where is the station?'}},
    {id:'place-aristera', term:'Αριστερά', tr:'aristerá', en:'Left', tags:['places']},
    {id:'place-dexia', term:'Δεξιά', tr:'dexiá', en:'Right', tags:['places']},
    {id:'place-efthia', term:'Ευθεία', tr:'efthía', en:'Straight ahead', tags:['places'],
     ex:{term:'Όλο ευθεία', tr:'ólo efthía', en:'Straight on'}},
    {id:'place-edo', term:'Εδώ', tr:'edó', en:'Here', tags:['places']},
    {id:'place-eki', term:'Εκεί', tr:'ekí', en:'There', tags:['places']},
    {id:'place-konda', term:'Κοντά', tr:'kondá', en:'Near', tags:['places'],
     ex:{term:'Είναι κοντά;', tr:'íne kondá?', en:'Is it near?'}},
    {id:'place-makria', term:'Μακριά', tr:'makriá', en:'Far', tags:['places']},
    {id:'place-paralia', term:'Παραλία', tr:'paralía', en:'Beach', tags:['places']},
    {id:'place-stathmos', term:'Σταθμός', tr:'stathmós', en:'Station', tags:['places']},
    {id:'place-toualeta', term:'Τουαλέτα', tr:'toualéta', en:'Toilet', tags:['places']},
    {id:'place-aerodromio', term:'Αεροδρόμιο', tr:'aerodrómio', en:'Airport', tags:['places']},

    /* ---------------- SHOPPING & MONEY ---------------- */
    {id:'shop-poso-kani', term:'Πόσο κάνει;', tr:'póso káni?', en:'How much is it?', tags:['shopping'],
     note:'Literally "how much does it make?". Plural: πόσο κάνουν;'},
    {id:'shop-akrivo', term:'Ακριβό', tr:'akrivó', en:'Expensive', tags:['shopping'],
     ex:{term:'Είναι πολύ ακριβό.', tr:'íne polí akrivó.', en:'It\'s very expensive.'}},
    {id:'shop-ftino', term:'Φτηνό', tr:'ftinó', en:'Cheap', tags:['shopping']},
    {id:'shop-me-karta', term:'Με κάρτα', tr:'me kárta', en:'By card', tags:['shopping'],
     ex:{term:'Μπορώ να πληρώσω με κάρτα;', tr:'boró na pliróso me kárta?', en:'Can I pay by card?'}},
    {id:'shop-metrita', term:'Μετρητά', tr:'metritá', en:'Cash', tags:['shopping']},
    {id:'shop-lefta', term:'Λεφτά', tr:'leftá', en:'Money (colloquial)', tags:['shopping'],
     note:'Formal word: χρήματα (chrímata).'},
    {id:'shop-evro', term:'Ευρώ', tr:'evró', en:'Euro', tags:['shopping'],
     note:'Never changes in the plural: δέκα ευρώ.'},
    {id:'shop-tha-to-paro', term:'Θα το πάρω', tr:'tha to páro', en:'I\'ll take it', tags:['shopping']},
    {id:'shop-aplos-kitao', term:'Απλώς κοιτάω', tr:'aplós kitáo', en:'Just looking', tags:['shopping']},

    /* ---------------- FEELINGS & SMALL TALK ---------------- */
    {id:'feel-ime-kala', term:'Είμαι καλά', tr:'íme kalá', en:'I\'m fine', tags:['feelings']},
    {id:'feel-kourazmenos', term:'Είμαι κουρασμένος', tr:'íme kourazménos', en:'I\'m tired (m.)', tags:['feelings'],
     note:'Feminine: κουρασμένη (kourazméni).'},
    {id:'feel-charoumenos', term:'Χαρούμενος', tr:'charoúmenos', en:'Happy (m.)', tags:['feelings'],
     note:'Feminine: χαρούμενη (charoúmeni).'},
    {id:'feel-mou-aresi', term:'Μου αρέσει', tr:'mou arési', en:'I like it', tags:['feelings','verbs'],
     note:'Literally "it pleases me". Plural things: μου αρέσουν (mou arésoun).',
     ex:{term:'Μου αρέσει η Ελλάδα.', tr:'mou arési i Elláda.', en:'I like Greece.'}},
    {id:'feel-den-mou-aresi', term:'Δεν μου αρέσει', tr:'den mou arési', en:'I don\'t like it', tags:['feelings','verbs']},
    {id:'feel-kani-zesti', term:'Κάνει ζέστη', tr:'káni zésti', en:'It\'s hot (weather)', tags:['feelings','time']},
    {id:'feel-kani-krio', term:'Κάνει κρύο', tr:'káni krío', en:'It\'s cold (weather)', tags:['feelings','time']},
    {id:'feel-ola-kala', term:'Όλα καλά', tr:'óla kalá', en:'All good', tags:['feelings'],
     note:'Works as both the question and the answer.'},
    {id:'feel-siga-siga', term:'Σιγά σιγά', tr:'sigá sigá', en:'Slowly, take it easy', tags:['feelings'],
     note:'The Greek pace of life in two words.'},

    /* ---------------- VERBS (present, I / you) ---------------- */
    {id:'verb-thelo', term:'Θέλω', tr:'thélo', en:'I want', tags:['verbs'],
     ex:{term:'Θέλω ένα νερό.', tr:'thélo éna neró.', en:'I want a water.'}},
    {id:'verb-thelis', term:'Θέλεις', tr:'thélis', en:'You want', tags:['verbs'],
     note:'-ω is "I", -εις is "you". No pronoun needed.',
     ex:{term:'Θέλεις καφέ;', tr:'thélis kafé?', en:'Do you want coffee?'}},
    {id:'verb-echo', term:'Έχω', tr:'écho', en:'I have', tags:['verbs']},
    {id:'verb-echis', term:'Έχεις', tr:'échis', en:'You have', tags:['verbs'],
     ex:{term:'Έχεις ώρα;', tr:'échis óra?', en:'Do you have the time?'}},
    {id:'verb-pao', term:'Πάω', tr:'páo', en:'I go', tags:['verbs'],
     ex:{term:'Πάω σπίτι.', tr:'páo spíti.', en:'I\'m going home.'}},
    {id:'verb-pas', term:'Πας', tr:'pas', en:'You go', tags:['verbs'],
     ex:{term:'Πού πας;', tr:'pou pas?', en:'Where are you going?'}},
    {id:'verb-pame', term:'Πάμε', tr:'páme', en:'Let\'s go / We go', tags:['verbs'],
     note:'The most useful verb form in Greece.',
     ex:{term:'Πάμε για καφέ;', tr:'páme ya kafé?', en:'Shall we go for coffee?'}},
    {id:'verb-milao', term:'Μιλάω', tr:'miláo', en:'I speak', tags:['verbs']},
    {id:'verb-milas', term:'Μιλάς', tr:'milás', en:'You speak', tags:['verbs'],
     ex:{term:'Μιλάς αγγλικά;', tr:'milás angliká?', en:'Do you speak English?'}},
    {id:'verb-katalaveno', term:'Καταλαβαίνω', tr:'katalavéno', en:'I understand', tags:['verbs']},
    {id:'verb-katalavenis', term:'Καταλαβαίνεις;', tr:'katalavénis?', en:'Do you understand?', tags:['verbs']},
    {id:'verb-xero', term:'Ξέρω', tr:'xéro', en:'I know', tags:['verbs']},
    {id:'verb-xeris', term:'Ξέρεις', tr:'xéris', en:'You know', tags:['verbs'],
     ex:{term:'Ξέρεις πού είναι;', tr:'xéris pou íne?', en:'Do you know where it is?'}},
    {id:'verb-boro', term:'Μπορώ', tr:'boró', en:'I can', tags:['verbs'],
     note:'μπορώ να + verb.',
     ex:{term:'Μπορώ να...;', tr:'boró na...?', en:'Can I...?'}},
    {id:'verb-ime', term:'Είμαι', tr:'íme', en:'I am', tags:['verbs'],
     ex:{term:'Είμαι από την Αμερική.', tr:'íme apó tin Amerikí.', en:'I\'m from America.'}},
    {id:'verb-ise', term:'Είσαι', tr:'íse', en:'You are', tags:['verbs'],
     ex:{term:'Από πού είσαι;', tr:'apó pou íse?', en:'Where are you from?'}},

    /* ---------------- SURVIVAL ---------------- */
    {id:'surv-den-katalaveno', term:'Δεν καταλαβαίνω', tr:'den katalavéno', en:'I don\'t understand', tags:['survival']},
    {id:'surv-pio-siga', term:'Πιο σιγά, παρακαλώ', tr:'pio sigá, parakaló', en:'Slower, please', tags:['survival'],
     note:'σιγά is both "slowly" and "quietly".'},
    {id:'surv-milate-anglika', term:'Μιλάτε αγγλικά;', tr:'miláte angliká?', en:'Do you speak English? (formal)', tags:['survival']},
    {id:'surv-pos-leyete', term:'Πώς λέγεται... στα ελληνικά;', tr:'pos léyete... sta elliniká?', en:'How do you say... in Greek?', tags:['survival']},
    {id:'surv-den-milao-kala', term:'Δεν μιλάω καλά ελληνικά', tr:'den miláo kalá elliniká', en:'I don\'t speak Greek well', tags:['survival'],
     note:'Greeks will be delighted you tried.'},
    {id:'surv-xana', term:'Ξανά, παρακαλώ', tr:'xaná, parakaló', en:'Again, please', tags:['survival']},
    {id:'surv-ti-simeni', term:'Τι σημαίνει...;', tr:'ti siméni...?', en:'What does... mean?', tags:['survival']},
    {id:'surv-mia-stigmi', term:'Μια στιγμή', tr:'mia stigmí', en:'One moment', tags:['survival']},
    {id:'surv-voithia', term:'Βοήθεια!', tr:'voíthia!', en:'Help!', tags:['survival']},

    /* ---------------- CONNECTORS ---------------- */
    {id:'con-ke', term:'Και', tr:'ke', en:'And', tags:['connectors'],
     ex:{term:'Καφέ και νερό', tr:'kafé ke neró', en:'Coffee and water'}},
    {id:'con-alla', term:'Αλλά', tr:'allá', en:'But', tags:['connectors']},
    {id:'con-epidi', term:'Επειδή', tr:'epidí', en:'Because', tags:['connectors'],
     note:'γιατί also works as "because" in speech.'},
    {id:'con-i', term:'Ή', tr:'i', en:'Or', tags:['connectors'],
     ex:{term:'Καφέ ή τσάι;', tr:'kafé i tsái?', en:'Coffee or tea?'}},
    {id:'con-episis', term:'Επίσης', tr:'epísis', en:'Also / Likewise', tags:['connectors'],
     note:'The reply to καλή όρεξη.'},
    {id:'con-tote', term:'Τότε', tr:'tóte', en:'Then', tags:['connectors']},
    {id:'con-an', term:'Αν', tr:'an', en:'If', tags:['connectors']},
    {id:'con-omos', term:'Όμως', tr:'ómos', en:'However', tags:['connectors']},
    {id:'con-lipon', term:'Λοιπόν', tr:'lipón', en:'So / Well...', tags:['connectors'],
     note:'The filler Greeks start sentences with.'},
  ],
};
