/* greek-myth.js — Greek Gods & Myths for /anki.
 *
 * Fact deck: term = the name, en = who or what it is. Both directions are
 * studied (name → description, description → name). No speech.
 * Rules as in greek.js: append only, never rename or reuse an id, bump
 * version and updated, run `node anki/deck.test.js`.
 * memo = a hook: an English word that comes from the name, a family link, or
 * a picture. parts = the key facts in pieces (domain, symbol, Roman name, parents).
 */
window.DECKS = window.DECKS || {};
window.DECKS['greek-myth'] = {
  id: 'greek-myth',
  name: 'Greek Gods & Myths',
  version: 1,
  updated: '2026-10-01',

  notes: [
    /* ---------------- THE TWELVE OLYMPIANS ---------------- */
    {id:'oly-zeus', term:'Zeus', en:'King of the gods; god of the sky, thunder and justice. Rules from Mount Olympus. Roman: Jupiter.', tags:['olympians'],
     memo:'Zeus and Jupiter share a root meaning "sky father" (Zeus patēr, Ju-piter). The lightning bolt is his.',
     parts:[{t:'Domain', m:'sky, thunder, law, hospitality'},{t:'Symbols', m:'thunderbolt, eagle, oak'},{t:'Parents', m:'Cronus and Rhea'},{t:'Roman', m:'Jupiter'}]},
    {id:'oly-hera', term:'Hera', en:'Queen of the gods; goddess of marriage and family. Wife and sister of Zeus, famously jealous of his lovers. Roman: Juno.', tags:['olympians'],
     memo:'Hera is the "hero" word\'s cousin: a hero was originally someone under Hera\'s protection, like Heracles ("glory of Hera").',
     parts:[{t:'Domain', m:'marriage, women, family'},{t:'Symbols', m:'peacock, cow, pomegranate'},{t:'Husband', m:'Zeus'},{t:'Roman', m:'Juno'}]},
    {id:'oly-poseidon', term:'Poseidon', en:'God of the sea, earthquakes and horses. Brother of Zeus; carries a trident. Roman: Neptune.', tags:['olympians'],
     memo:'Three prongs for the three realms he shakes: sea, earth (earthquakes) and horses. Think "poised on the ocean".',
     parts:[{t:'Domain', m:'sea, earthquakes, horses'},{t:'Symbol', m:'trident'},{t:'Parents', m:'Cronus and Rhea'},{t:'Roman', m:'Neptune'}]},
    {id:'oly-athena', term:'Athena', en:'Goddess of wisdom, strategy in war and crafts. Born fully armed from Zeus\'s head; patron of Athens. Roman: Minerva.', tags:['olympians'],
     memo:'Athens is named for her; she won the city by giving it the olive tree. The owl is her bird, which is why owls mean wisdom.',
     parts:[{t:'Domain', m:'wisdom, strategic war, weaving, crafts'},{t:'Symbols', m:'owl, olive tree, aegis'},{t:'Birth', m:'from Zeus\'s head, in armour'},{t:'Roman', m:'Minerva'}]},
    {id:'oly-apollo', term:'Apollo', en:'God of the sun, music, poetry, prophecy and healing. Twin of Artemis; his oracle was at Delphi. Roman: Apollo.', tags:['olympians'],
     memo:'NASA\'s Apollo program: the sun god for the trip to the sky. Same name in Rome, one of the few.',
     parts:[{t:'Domain', m:'sun, music, prophecy, medicine, archery'},{t:'Symbols', m:'lyre, laurel, bow'},{t:'Twin', m:'Artemis'},{t:'Oracle', m:'Delphi'}]},
    {id:'oly-artemis', term:'Artemis', en:'Goddess of the hunt, the moon, wild animals and young girls. Twin of Apollo; a virgin goddess with a bow. Roman: Diana.', tags:['olympians'],
     memo:'Apollo sun, Artemis moon: the twins split the sky. NASA\'s Artemis program sends people back to the moon.',
     parts:[{t:'Domain', m:'hunt, moon, wilderness'},{t:'Symbols', m:'bow, deer, crescent moon'},{t:'Twin', m:'Apollo'},{t:'Roman', m:'Diana'}]},
    {id:'oly-ares', term:'Ares', en:'God of war in its violent, bloody form. Son of Zeus and Hera; disliked by most gods; lover of Aphrodite. Roman: Mars.', tags:['olympians'],
     memo:'Athena is the strategy of war, Ares the rage of it. Mars the planet is red like blood, and March was the month to start wars.',
     parts:[{t:'Domain', m:'war, violence'},{t:'Symbols', m:'spear, helmet, vulture'},{t:'Lover', m:'Aphrodite'},{t:'Roman', m:'Mars'}]},
    {id:'oly-aphrodite', term:'Aphrodite', en:'Goddess of love, beauty and desire. Born from sea foam; married to Hephaestus, lover of Ares. Roman: Venus.', tags:['olympians'],
     memo:'aphros = sea foam, which she rose from (Botticelli\'s Birth of Venus). "Aphrodisiac" comes from her.',
     parts:[{t:'Domain', m:'love, beauty, desire'},{t:'Symbols', m:'dove, rose, scallop shell'},{t:'Husband', m:'Hephaestus'},{t:'Roman', m:'Venus'}]},
    {id:'oly-hermes', term:'Hermes', en:'Messenger of the gods; god of travel, trade, thieves and boundaries. Guides souls to the Underworld; winged sandals. Roman: Mercury.', tags:['olympians'],
     memo:'Hermes the luxury brand sells to travellers; Mercury the planet is the fastest. The caduceus staff with two snakes is his.',
     parts:[{t:'Domain', m:'messages, travel, trade, thieves'},{t:'Symbols', m:'winged sandals, caduceus'},{t:'Role', m:'psychopomp: guides the dead'},{t:'Roman', m:'Mercury'}]},
    {id:'oly-hephaestus', term:'Hephaestus', en:'God of fire, the forge and craftsmen. Lame; thrown from Olympus as a baby; made the gods\' weapons. Married to Aphrodite. Roman: Vulcan.', tags:['olympians'],
     memo:'Vulcan gives us "volcano": his forge is under the mountain. The only ugly Olympian, married to the most beautiful.',
     parts:[{t:'Domain', m:'fire, metalwork, craft'},{t:'Symbols', m:'hammer, anvil, tongs'},{t:'Wife', m:'Aphrodite'},{t:'Roman', m:'Vulcan'}]},
    {id:'oly-demeter', term:'Demeter', en:'Goddess of the harvest, grain and the seasons. Mother of Persephone; her grief makes winter. Roman: Ceres.', tags:['olympians'],
     memo:'Ceres gives us "cereal". Dē-mētēr may mean "earth mother".',
     parts:[{t:'Domain', m:'harvest, grain, fertility of the earth'},{t:'Symbols', m:'wheat, torch, cornucopia'},{t:'Daughter', m:'Persephone'},{t:'Roman', m:'Ceres'}]},
    {id:'oly-dionysus', term:'Dionysus', en:'God of wine, theatre, ecstasy and madness. Born from Zeus\'s thigh; followed by satyrs and maenads. Roman: Bacchus.', tags:['olympians'],
     memo:'Bacchus gives "bacchanal", a drunken party. Greek drama began as festivals in his honour.',
     parts:[{t:'Domain', m:'wine, theatre, ritual madness'},{t:'Symbols', m:'grapevine, thyrsus staff, leopard'},{t:'Followers', m:'satyrs and maenads'},{t:'Roman', m:'Bacchus'}]},
    {id:'oly-hestia', term:'Hestia', en:'Goddess of the hearth and home. Eldest child of Cronus; gave up her Olympian seat to Dionysus. Roman: Vesta.', tags:['olympians'],
     memo:'The Vestal Virgins kept Rome\'s sacred fire. Quiet, no myths of her own: the hearth is just always there.',
     parts:[{t:'Domain', m:'hearth, home, family fire'},{t:'Symbol', m:'the hearth flame'},{t:'Note', m:'swapped out of the Twelve for Dionysus'},{t:'Roman', m:'Vesta'}]},
    {id:'oly-hades', term:'Hades', en:'God of the Underworld and the dead; also of wealth under the earth. Brother of Zeus; abducted Persephone. Roman: Pluto.', tags:['olympians','underworld'],
     memo:'Pluto means "wealthy" (plutocracy): gold and crops come from under the ground. Not evil, just the landlord of the dead.',
     parts:[{t:'Domain', m:'the dead, the Underworld, riches below'},{t:'Symbols', m:'helmet of invisibility, Cerberus, bident'},{t:'Wife', m:'Persephone'},{t:'Roman', m:'Pluto'}]},

    /* ---------------- BEFORE THE OLYMPIANS ---------------- */
    {id:'pri-chaos', term:'Chaos', en:'The first thing to exist: the yawning void from which Gaia, Tartarus, Eros, Erebus and Nyx emerged.', tags:['primordials'],
     memo:'Chaos originally meant a gap or chasm, not disorder. The word kept the name, lost the meaning.',
     parts:[{t:'Role', m:'the first being, a void'},{t:'Children', m:'Gaia, Tartarus, Eros, Erebus, Nyx'}]},
    {id:'pri-gaia', term:'Gaia', en:'The Earth, mother of everything: of Uranus, the Titans, the Cyclopes and the Giants.', tags:['primordials'],
     memo:'Geo-graphy, geo-logy: Gaia is the ge- in every earth word.',
     parts:[{t:'Role', m:'Earth personified'},{t:'Children', m:'Uranus (sky), the Titans, Cyclopes, Giants'}]},
    {id:'pri-uranus', term:'Uranus', en:'The Sky, husband of Gaia, father of the Titans. Castrated and overthrown by his son Cronus.', tags:['primordials'],
     memo:'The planet Uranus is named for the sky god; uranium was named for the planet.',
     parts:[{t:'Role', m:'Sky personified'},{t:'Fate', m:'overthrown by Cronus with a sickle'}]},
    {id:'pri-cronus', term:'Cronus', en:'King of the Titans. Overthrew his father Uranus, then swallowed his own children to keep his throne, until Zeus beat him.', tags:['titans'],
     memo:'Often confused with Chronos (time), hence "Father Time" with a scythe. The Romans called him Saturn.',
     parts:[{t:'Role', m:'leader of the Titans'},{t:'Wife', m:'Rhea'},{t:'Fate', m:'defeated by Zeus in the Titanomachy'},{t:'Roman', m:'Saturn'}]},
    {id:'pri-rhea', term:'Rhea', en:'Titaness, wife of Cronus, mother of the Olympians. Saved baby Zeus by giving Cronus a stone wrapped in cloth to swallow.', tags:['titans'],
     memo:'The stone trick: Rhea is the mother who outwitted the swallowing father.',
     parts:[{t:'Role', m:'mother of Zeus, Hera, Poseidon, Hades, Demeter, Hestia'},{t:'Trick', m:'a swaddled stone for Cronus'}]},
    {id:'pri-prometheus', term:'Prometheus', en:'Titan who made humans from clay and stole fire from the gods for them. Zeus chained him to a rock where an eagle ate his liver daily.', tags:['titans','stories'],
     memo:'pro-metheus = "forethought"; his brother Epimetheus is "afterthought". Promethean = boldly creative.',
     parts:[{t:'Gift', m:'fire, stolen from Olympus'},{t:'Punishment', m:'chained; eagle eats his liver, which regrows'},{t:'Rescued by', m:'Heracles'}]},
    {id:'pri-atlas', term:'Atlas', en:'Titan condemned to hold up the sky forever after the Titans lost the war against Zeus.', tags:['titans'],
     memo:'An atlas of maps got its name from a book with Atlas on the cover holding the world. The Atlas Mountains are him turned to stone.',
     parts:[{t:'Burden', m:'the sky (later pictured as the globe)'},{t:'Brother', m:'Prometheus'}]},
    {id:'pri-titanomachy', term:'Titanomachy', en:'The ten-year war in which Zeus and the Olympians overthrew Cronus and the Titans, who were then imprisoned in Tartarus.', tags:['titans','stories'],
     memo:'-machy = battle (as in "logomachy"). Titanic = huge, from these giants.',
     parts:[{t:'Sides', m:'Olympians vs Titans'},{t:'Allies of Zeus', m:'Cyclopes (made the thunderbolt) and Hundred-Handers'},{t:'Result', m:'Titans locked in Tartarus'}]},

    /* ---------------- HEROES ---------------- */
    {id:'hero-heracles', term:'Heracles', en:'Strongest of heroes, son of Zeus and Alcmene. Driven mad by Hera, killed his family, and atoned with the Twelve Labours. Roman: Hercules.', tags:['heroes'],
     memo:'"Glory of Hera", ironically, since Hera hated him. Herculean task = one of the Twelve Labours.',
     parts:[{t:'Parents', m:'Zeus and the mortal Alcmene'},{t:'Enemy', m:'Hera'},{t:'Famous for', m:'the Twelve Labours'},{t:'Roman', m:'Hercules'}]},
    {id:'hero-twelve-labours', term:'The Twelve Labours', en:'Heracles\' penance for King Eurystheus: Nemean lion, Lernaean Hydra, Ceryneian hind, Erymanthian boar, Augean stables, Stymphalian birds, Cretan bull, mares of Diomedes, Hippolyta\'s belt, cattle of Geryon, apples of the Hesperides, Cerberus.', tags:['heroes','stories'],
     memo:'Lion, Hydra, deer, boar, stables, birds, bull, horses, belt, cattle, apples, dog. The first is the lion skin he wears ever after.',
     parts:[{t:'1–4', m:'Nemean lion, Hydra, golden hind, boar'},{t:'5–8', m:'Augean stables, Stymphalian birds, Cretan bull, man-eating mares'},{t:'9–12', m:'Amazon\'s belt, Geryon\'s cattle, golden apples, Cerberus'}]},
    {id:'hero-perseus', term:'Perseus', en:'Hero who beheaded Medusa using a mirrored shield, winged sandals and a cap of invisibility; rescued Andromeda from a sea monster. Founder of Mycenae.', tags:['heroes'],
     memo:'Looked only at the reflection: the mirror trick. Perseus and Andromeda are neighbouring constellations.',
     parts:[{t:'Parents', m:'Zeus (as a shower of gold) and Danaë'},{t:'Gear', m:'mirrored shield from Athena, sandals from Hermes'},{t:'Deeds', m:'killed Medusa, saved Andromeda'}]},
    {id:'hero-theseus', term:'Theseus', en:'Athenian hero who killed the Minotaur in the Labyrinth, escaping with Ariadne\'s thread. Later king of Athens.', tags:['heroes'],
     memo:'Ariadne\'s thread: a "clew" of yarn, which gave English the word "clue".',
     parts:[{t:'Deed', m:'slew the Minotaur on Crete'},{t:'Helper', m:'Ariadne and her thread'},{t:'Flaw', m:'forgot to raise the white sail; his father Aegeus leapt into the sea (the Aegean)'}]},
    {id:'hero-odysseus', term:'Odysseus', en:'King of Ithaca, cleverest of the Greeks; thought of the Trojan Horse. Took ten years to sail home, the story of the Odyssey. Roman: Ulysses.', tags:['heroes','trojan-war'],
     memo:'An odyssey is any long wandering journey. Brains over brawn: the Horse was his idea.',
     parts:[{t:'Home', m:'Ithaca; wife Penelope, son Telemachus'},{t:'Trials', m:'Cyclops, Circe, Sirens, Scylla and Charybdis, Calypso'},{t:'Roman', m:'Ulysses'}]},
    {id:'hero-achilles', term:'Achilles', en:'Greatest Greek warrior at Troy, dipped in the Styx as a baby and invulnerable except his heel. Killed Hector; killed by Paris\'s arrow.', tags:['heroes','trojan-war'],
     memo:'Achilles heel = the one weak spot. His mother Thetis held him by the heel in the Styx.',
     parts:[{t:'Parents', m:'Peleus and the sea nymph Thetis'},{t:'Friend', m:'Patroclus, whose death sent him back to battle'},{t:'Death', m:'arrow to the heel, from Paris'}]},
    {id:'hero-jason', term:'Jason', en:'Leader of the Argonauts, who sailed the Argo to fetch the Golden Fleece with the help of the sorceress Medea.', tags:['heroes'],
     memo:'Argo-nauts = sailors of the Argo (nautical). He later betrayed Medea, and she took terrible revenge.',
     parts:[{t:'Quest', m:'the Golden Fleece in Colchis'},{t:'Ship', m:'the Argo'},{t:'Helper', m:'Medea'}]},
    {id:'hero-hector', term:'Hector', en:'Prince of Troy and its greatest defender; husband of Andromache. Killed by Achilles, who dragged his body around the walls.', tags:['heroes','trojan-war'],
     memo:'The noble one on the losing side. To "hector" someone (bully) is an unfair legacy.',
     parts:[{t:'City', m:'Troy'},{t:'Family', m:'son of Priam, brother of Paris'},{t:'Death', m:'by Achilles, avenging Patroclus'}]},
    {id:'hero-orpheus', term:'Orpheus', en:'Musician whose lyre charmed even stones. Went to the Underworld for his wife Eurydice and lost her by looking back too soon.', tags:['heroes','stories'],
     memo:'Don\'t look back. The one rule, and he broke it a step from daylight.',
     parts:[{t:'Gift', m:'music that moved gods and rocks'},{t:'Wife', m:'Eurydice'},{t:'Rule', m:'do not look back until both are out'}]},

    /* ---------------- MONSTERS & CREATURES ---------------- */
    {id:'mon-medusa', term:'Medusa', en:'Gorgon with snakes for hair whose gaze turned people to stone. Beheaded by Perseus; Pegasus sprang from her blood.', tags:['monsters'],
     memo:'Once beautiful, cursed by Athena. Her face on Athena\'s shield became the standard "evil eye" protector.',
     parts:[{t:'Kind', m:'Gorgon, mortal one of three sisters'},{t:'Power', m:'petrifying gaze'},{t:'Killer', m:'Perseus'}]},
    {id:'mon-minotaur', term:'Minotaur', en:'Half man, half bull, child of Queen Pasiphaë of Crete and a bull. Kept in the Labyrinth and fed Athenian youths until Theseus killed it.', tags:['monsters'],
     memo:'Minos + tauros = "bull of Minos". Labyrinth gives us the word for a maze.',
     parts:[{t:'Home', m:'the Labyrinth built by Daedalus'},{t:'Diet', m:'seven youths and seven maidens from Athens'},{t:'Killer', m:'Theseus'}]},
    {id:'mon-cerberus', term:'Cerberus', en:'Three-headed dog guarding the gates of the Underworld; lets souls in, never out. Heracles\' twelfth labour was to fetch him.', tags:['monsters','underworld'],
     memo:'Three heads for the three-headed doorman. Fluffy in Harry Potter is a Cerberus.',
     parts:[{t:'Job', m:'guard dog of Hades'},{t:'Heads', m:'three'},{t:'Tamed by', m:'Heracles (and Orpheus\'s music)'}]},
    {id:'mon-hydra', term:'Hydra', en:'Many-headed water serpent of Lerna: cut off one head and two grow back. Heracles burned the stumps, his second labour.', tags:['monsters'],
     memo:'hydra = water (hydrate). A "hydra-headed" problem gets worse when you attack it.',
     parts:[{t:'Trick', m:'two heads for every one cut'},{t:'Solution', m:'cauterise each neck, bury the immortal head'},{t:'Bonus', m:'Heracles dipped his arrows in its venom'}]},
    {id:'mon-pegasus', term:'Pegasus', en:'Winged horse born from Medusa\'s blood. Ridden by Bellerophon to kill the Chimera; later a constellation.', tags:['monsters'],
     memo:'The flying horse that came out of a monster: Medusa\'s one good gift.',
     parts:[{t:'Birth', m:'from Medusa\'s severed neck'},{t:'Rider', m:'Bellerophon'},{t:'End', m:'placed among the stars'}]},
    {id:'mon-chimera', term:'Chimera', en:'Fire-breathing monster with a lion\'s head, a goat\'s body and a serpent\'s tail. Killed by Bellerophon on Pegasus.', tags:['monsters'],
     memo:'A chimera is now anything stitched from mismatched parts, including hybrid organisms in biology.',
     parts:[{t:'Parts', m:'lion, goat, snake'},{t:'Breath', m:'fire'},{t:'Killer', m:'Bellerophon'}]},
    {id:'mon-cyclops', term:'Cyclops', en:'One-eyed giant. The Cyclopes forged Zeus\'s thunderbolt; Polyphemus the Cyclops trapped Odysseus, who blinded him and escaped under his sheep.', tags:['monsters'],
     memo:'kyklos (circle) + ops (eye): round-eye. "Nobody" is blinding me, Polyphemus told the others.',
     parts:[{t:'Craft', m:'the elder Cyclopes made the thunderbolt'},{t:'Polyphemus', m:'son of Poseidon, blinded by Odysseus'},{t:'Trick', m:'Odysseus called himself "Nobody"'}]},
    {id:'mon-sirens', term:'Sirens', en:'Creatures whose song lured sailors onto the rocks. Odysseus had himself tied to the mast to hear it; his crew plugged their ears with wax.', tags:['monsters'],
     memo:'A siren song is any irresistible, ruinous lure. The warning siren is named for them.',
     parts:[{t:'Weapon', m:'song'},{t:'Odysseus', m:'bound to the mast, crew with waxed ears'}]},
    {id:'mon-scylla-charybdis', term:'Scylla and Charybdis', en:'Six-headed monster on one side of a strait and a whirlpool on the other. Odysseus had to sail between them and lost six men.', tags:['monsters'],
     memo:'"Between Scylla and Charybdis" = between a rock and a hard place. Choose the lesser evil: the monster, not the whirlpool.',
     parts:[{t:'Scylla', m:'six heads, snatches sailors'},{t:'Charybdis', m:'whirlpool that swallows ships'},{t:'Choice', m:'lose six men rather than the ship'}]},
    {id:'mon-sphinx', term:'Sphinx', en:'Woman-headed lion that strangled anyone who failed her riddle at Thebes. Oedipus answered "man" and she threw herself off a cliff.', tags:['monsters','stories'],
     memo:'The riddle: what walks on four legs, then two, then three? A person: crawling, walking, with a cane.',
     parts:[{t:'Riddle', m:'four legs, two legs, three legs'},{t:'Answer', m:'a human'},{t:'Solved by', m:'Oedipus'}]},
    {id:'mon-centaur', term:'Centaur', en:'Half man, half horse. Mostly wild and drunken, except Chiron, the wise one who taught Achilles, Jason and Asclepius.', tags:['monsters'],
     memo:'Chiron, the good centaur, is the archer in the Sagittarius constellation.',
     parts:[{t:'Form', m:'human torso on a horse body'},{t:'Exception', m:'Chiron, teacher of heroes'}]},

    /* ---------------- PLACES ---------------- */
    {id:'place-olympus', term:'Mount Olympus', en:'Highest mountain in Greece and the home of the gods, where Zeus holds court.', tags:['places'],
     memo:'A real mountain, 2,917 m, in northern Greece. The Olympic Games were at Olympia, a different place in the south.',
     parts:[{t:'What', m:'home of the Twelve Olympians'},{t:'Where', m:'northern Greece, near Thessaloniki'}]},
    {id:'place-underworld', term:'The Underworld', en:'Realm of the dead ruled by Hades. Souls cross the Styx with Charon, pass Cerberus, and go to the Elysian Fields, the Asphodel Meadows or Tartarus.', tags:['places','underworld'],
     memo:'Three destinations: Elysium for heroes, Asphodel for the ordinary, Tartarus for the wicked. Pay Charon or wander the bank for a century.',
     parts:[{t:'Ruler', m:'Hades and Persephone'},{t:'River', m:'the Styx, ferried by Charon'},{t:'Regions', m:'Elysium, Asphodel, Tartarus'}]},
    {id:'place-styx', term:'River Styx', en:'River of the Underworld that the dead cross. Gods swore unbreakable oaths on it; Achilles was dipped in it.', tags:['places','underworld'],
     memo:'The coin on the tongue was Charon\'s fare to cross it. Stygian = dark as the Styx.',
     parts:[{t:'Ferryman', m:'Charon, paid with an obol'},{t:'Oath', m:'a god who swears by the Styx cannot break it'}]},
    {id:'place-tartarus', term:'Tartarus', en:'The deep abyss below the Underworld where the Titans are imprisoned and the wicked are punished.', tags:['places','underworld'],
     memo:'As far below Hades as the earth is below the sky. The maximum-security wing.',
     parts:[{t:'Prisoners', m:'the Titans, Sisyphus, Tantalus'},{t:'Depth', m:'a bronze anvil falls nine days to reach it'}]},
    {id:'place-delphi', term:'Delphi', en:'Sanctuary of Apollo where the Pythia, his priestess, gave prophecies. The "navel of the world"; "Know thyself" was carved at the entrance.', tags:['places'],
     memo:'Delphic = ambiguous, like the oracle\'s answers: "if you cross the river, a great empire will fall." Whose?',
     parts:[{t:'God', m:'Apollo'},{t:'Oracle', m:'the Pythia, seated over a chasm'},{t:'Motto', m:'Know thyself'}]},
    {id:'place-troy', term:'Troy', en:'City in Asia Minor besieged for ten years by the Greeks after Paris took Helen. Fell to the wooden horse.', tags:['places','trojan-war'],
     memo:'A real site in Turkey, dug up by Schliemann in the 1870s. Ilion is its other name, hence the Iliad.',
     parts:[{t:'Where', m:'northwest Turkey, by the Dardanelles'},{t:'King', m:'Priam'},{t:'Fall', m:'the Trojan Horse'}]},

    /* ---------------- STORIES ---------------- */
    {id:'story-pandora', term:'Pandora', en:'The first woman, made by the gods. Opened a jar (not a box) releasing every evil into the world; only Hope stayed inside.', tags:['stories'],
     memo:'pan + dora = "all gifts": every god gave her something. A mistranslation turned her jar into a box.',
     parts:[{t:'Made by', m:'Hephaestus, on Zeus\'s order'},{t:'Jar', m:'all evils escaped'},{t:'Left inside', m:'Hope'}]},
    {id:'story-persephone', term:'Persephone', en:'Daughter of Demeter, abducted by Hades. Ate pomegranate seeds, so she spends part of each year below: her absence is winter.', tags:['stories','underworld'],
     memo:'The seasons explained: six seeds, six months. Roman: Proserpina.',
     parts:[{t:'Parents', m:'Zeus and Demeter'},{t:'Husband', m:'Hades'},{t:'Why winter', m:'Demeter mourns while she is below'}]},
    {id:'story-icarus', term:'Icarus', en:'Son of Daedalus who flew on wings of wax and feathers to escape Crete, went too near the sun, and fell into the sea.', tags:['stories'],
     memo:'Fly too close to the sun: the warning for overreach. Daedalus, the father, made it home.',
     parts:[{t:'Father', m:'Daedalus, the inventor'},{t:'Wings', m:'feathers held by wax'},{t:'Lesson', m:'not too high, not too low'}]},
    {id:'story-narcissus', term:'Narcissus', en:'Beautiful youth who fell in love with his own reflection in a pool and wasted away. The nymph Echo loved him and faded to a voice.', tags:['stories'],
     memo:'Narcissism and the echo both come from this one story.',
     parts:[{t:'Flaw', m:'loved only himself'},{t:'Echo', m:'cursed to repeat others\' last words'},{t:'End', m:'became the narcissus flower'}]},
    {id:'story-midas', term:'King Midas', en:'King granted the golden touch by Dionysus: everything he touched turned to gold, including food and his daughter. Later given donkey ears by Apollo.', tags:['stories'],
     memo:'The Midas touch sounds like luck; in the story it is a curse he begs to lose.',
     parts:[{t:'Wish', m:'the golden touch'},{t:'Problem', m:'food and drink turned to gold'},{t:'Cure', m:'washing in the river Pactolus'}]},
    {id:'story-sisyphus', term:'Sisyphus', en:'King who cheated death twice. Punished in Tartarus to roll a boulder uphill forever; it always rolls back.', tags:['stories','underworld'],
     memo:'A Sisyphean task is endless and pointless. Camus said we must imagine him happy.',
     parts:[{t:'Crime', m:'tricked Thanatos and Hades'},{t:'Punishment', m:'the boulder, forever'}]},
    {id:'story-tantalus', term:'Tantalus', en:'King who served his son to the gods at a feast. Punished to stand in water he can\'t drink under fruit he can\'t reach.', tags:['stories','underworld'],
     memo:'To tantalise is to dangle what cannot be had.',
     parts:[{t:'Crime', m:'tested the gods with a cannibal feast'},{t:'Punishment', m:'eternal hunger and thirst within reach'}]},
    {id:'story-trojan-war', term:'The Trojan War', en:'Ten-year war of the Greeks against Troy after Paris took Helen from Menelaus. Told in the Iliad; ended by the wooden horse.', tags:['stories','trojan-war'],
     memo:'It began with a golden apple "for the fairest": Paris picked Aphrodite, who promised him Helen.',
     parts:[{t:'Cause', m:'the Judgement of Paris, then Helen'},{t:'Leaders', m:'Agamemnon for the Greeks, Priam for Troy'},{t:'End', m:'Odysseus\'s wooden horse'}]},
    {id:'story-trojan-horse', term:'The Trojan Horse', en:'Giant wooden horse left by the Greeks as a "gift". Troy wheeled it inside; the soldiers hidden within opened the gates at night.', tags:['stories','trojan-war'],
     memo:'"Beware of Greeks bearing gifts." A Trojan horse in computing hides malware inside something wanted.',
     parts:[{t:'Idea', m:'Odysseus'},{t:'Warning ignored', m:'Cassandra and Laocoön'},{t:'Result', m:'Troy burned'}]},
    {id:'story-helen', term:'Helen of Troy', en:'Most beautiful woman in the world, wife of Menelaus of Sparta. Her abduction by Paris launched the Trojan War.', tags:['stories','trojan-war'],
     memo:'"The face that launched a thousand ships." Daughter of Zeus, hatched from an egg after he came to Leda as a swan.',
     parts:[{t:'Husband', m:'Menelaus, king of Sparta'},{t:'Taken by', m:'Paris of Troy'},{t:'Mother', m:'Leda'}]},
    {id:'story-oedipus', term:'Oedipus', en:'King of Thebes who, unknowingly, killed his father and married his mother, fulfilling a prophecy he had fled. Blinded himself on learning the truth.', tags:['stories'],
     memo:'Oedipus means "swollen foot": his feet were pinned when he was abandoned as a baby. Freud borrowed the name.',
     parts:[{t:'Prophecy', m:'would kill his father and marry his mother'},{t:'Deed', m:'solved the Sphinx\'s riddle'},{t:'Ending', m:'blinds himself; Jocasta dies'}]},
    {id:'story-arachne', term:'Arachne', en:'Weaver who challenged Athena and won, but mocked the gods in her tapestry. Athena turned her into a spider.', tags:['stories'],
     memo:'Arachnid: every spider is her descendant, still weaving.',
     parts:[{t:'Contest', m:'weaving, against Athena'},{t:'Offence', m:'depicted the gods\' affairs'},{t:'Fate', m:'the first spider'}]},
    {id:'story-golden-fleece', term:'The Golden Fleece', en:'Fleece of a golden ram kept in Colchis, guarded by a dragon. Jason and the Argonauts won it with Medea\'s magic.', tags:['stories'],
     memo:'The ram that carried Phrixus to safety; its fleece became the quest. The ram is the Aries constellation.',
     parts:[{t:'Where', m:'Colchis, on the Black Sea'},{t:'Guard', m:'a sleepless dragon'},{t:'Winner', m:'Jason, with Medea'}]},
    {id:'story-echo-nymphs', term:'Nymphs', en:'Minor nature goddesses: dryads of trees, naiads of springs, nereids of the sea, oreads of mountains.', tags:['stories'],
     memo:'Dryad = drys, oak. Naiad = water. Nereid = daughters of Nereus the sea god (Thetis was one).',
     parts:[{t:'Dryads', m:'trees'},{t:'Naiads', m:'springs and rivers'},{t:'Nereids', m:'the sea'}]},
    {id:'story-muses', term:'The Muses', en:'Nine daughters of Zeus and Mnemosyne (Memory) who inspire the arts: epic poetry, history, music, comedy, tragedy, dance, lyric, hymns, astronomy.', tags:['stories'],
     memo:'Museum = "seat of the Muses". Music, amuse: all from them. Their mother is Memory, because art was recited.',
     parts:[{t:'Mother', m:'Mnemosyne, memory'},{t:'Count', m:'nine'},{t:'Examples', m:'Calliope (epic), Clio (history), Urania (astronomy)'}]},
    {id:'story-fates', term:'The Fates (Moirai)', en:'Three goddesses who control every life: Clotho spins the thread, Lachesis measures it, Atropos cuts it.', tags:['stories'],
     memo:'Spin, measure, cut. Even Zeus does not overrule them. Roman: the Parcae.',
     parts:[{t:'Clotho', m:'spins'},{t:'Lachesis', m:'measures'},{t:'Atropos', m:'cuts (atropine, the deadly nightshade poison, is named for her)'}]},
    {id:'story-nike', term:'Nike', en:'Winged goddess of victory, companion of Athena and Zeus. Often shown crowning winners with a wreath.', tags:['stories'],
     memo:'The shoe brand and the swoosh, which is her wing. The Winged Victory of Samothrace in the Louvre is Nike.',
     parts:[{t:'Domain', m:'victory, in war and sport'},{t:'Roman', m:'Victoria'}]},
    {id:'story-eros', term:'Eros', en:'God of love and desire, son of Aphrodite, with a bow whose arrows make people fall in love. Married Psyche. Roman: Cupid.', tags:['stories'],
     memo:'Erotic from Eros, cupidity from Cupid. Psyche means "soul": love and the soul, together after trials.',
     parts:[{t:'Weapon', m:'gold arrows for love, lead for aversion'},{t:'Wife', m:'Psyche'},{t:'Roman', m:'Cupid'}]},
    {id:'story-pan', term:'Pan', en:'Goat-legged god of shepherds, the wild and rustic music. His sudden shout causes "panic". Plays the pan pipes.', tags:['stories'],
     memo:'Panic is his, and the pan pipes (syrinx). The only god said to have died.',
     parts:[{t:'Form', m:'goat legs and horns'},{t:'Domain', m:'shepherds, wild places'},{t:'Word', m:'panic'}]},
    {id:'story-asclepius', term:'Asclepius', en:'God of medicine, son of Apollo, taught by Chiron. His staff with one snake is the symbol of medicine. Zeus killed him for raising the dead.', tags:['stories'],
     memo:'One snake on a staff = medicine (Asclepius). Two snakes with wings = Hermes, often misused on ambulances.',
     parts:[{t:'Father', m:'Apollo'},{t:'Teacher', m:'Chiron the centaur'},{t:'Symbol', m:'the rod of Asclepius'}]},
    {id:'story-cassandra', term:'Cassandra', en:'Trojan princess given prophecy by Apollo, then cursed never to be believed. Foretold the fall of Troy; nobody listened.', tags:['stories','trojan-war'],
     memo:'A Cassandra is someone whose true warnings are ignored.',
     parts:[{t:'Gift', m:'true prophecy'},{t:'Curse', m:'never believed'},{t:'Fate', m:'taken by Agamemnon, murdered by Clytemnestra'}]},
  ],
};
