/* italian.js — the Conversational Italian deck for /anki.
 *
 * Registered in anki/decks/index.js. Read the header of greek.js for the editing
 * rules: append only, never rename or reuse an id, bump version and updated,
 * run `node anki/deck.test.js` before committing.
 *
 * Latin script, so there is no tr line: term is the main line. Stress is marked
 * in memos where it is not on the second-to-last syllable (perCHÉ, CAffè).
 * MEMOS FOR ITALIAN: lean on English words that came from Latin or Italian
 *   (buono/bonus, grazie/grace, piacere/pleasure, scusi/excuse), the endings
 *   (-o masculine, -a feminine, -i/-e plurals), the verb families (-are/-ere/-ire)
 *   and the few patterns that unlock everything: vorrei (I'd like), posso (can I),
 *   c'è (there is), mi piace (I like, literally "it pleases me").
 * Fields: id, term, en, tags, memo, parts:[{t,m}], note?, ex?{term,en}
 */
window.DECKS = window.DECKS || {};
window.DECKS.italian = {
  id: 'italian',
  name: 'Conversational Italian',
  version: 1,
  updated: '2026-10-09',

  notes: [
    /* ---------------- GREETINGS ---------------- */
    {id:'greet-ciao', term:'Ciao', en:'Hi / Bye', tags:['greetings'], memo:'The one word you already know. Works coming and going, but only with people you would use first names with.',
     parts:[{t:'Ciao', m:'hi, bye (informal)'}], note:'Informal. For strangers, shopkeepers and anyone older use Buongiorno / Buonasera / Arrivederci.'},
    {id:'greet-buongiorno', term:'Buongiorno', en:'Good morning / Good day', tags:['greetings'], memo:'buon = good (bonus), giorno = day (journal, the daily paper). Use it until early afternoon.',
     parts:[{t:'Buon-', m:'good'},{t:'-giorno', m:'day'}], ex:{term:'Buongiorno, un caffè per favore.', en:'Good morning, a coffee please.'}},
    {id:'greet-buonasera', term:'Buonasera', en:'Good evening', tags:['greetings'], memo:'sera = evening, as in "serenade", the evening song. Italians switch to it mid-afternoon.',
     parts:[{t:'Buona-', m:'good (feminine)'},{t:'-sera', m:'evening'}]},
    {id:'greet-buonanotte', term:'Buonanotte', en:'Good night', tags:['greetings'], memo:'notte = night (nocturnal). Only when someone is going to bed.',
     parts:[{t:'Buona-', m:'good'},{t:'-notte', m:'night'}]},
    {id:'greet-salve', term:'Salve', en:'Hello (neutral)', tags:['greetings'], memo:'Latin "salve" = be well, the Roman greeting. Safe when you are unsure between ciao and buongiorno.',
     parts:[{t:'Salve', m:'hello (polite but not stiff)'}]},
    {id:'greet-arrivederci', term:'Arrivederci', en:'Goodbye', tags:['greetings'], memo:'a-ri-veder-ci = "to re-see us", until we see each other again. Vedere = to see (video).',
     parts:[{t:'A', m:'to, until'},{t:'ri-', m:'again'},{t:'veder-', m:'see'},{t:'-ci', m:'us, each other'}], note:'Polite. Very formal: ArrivederLa.'},
    {id:'greet-a-presto', term:'A presto', en:'See you soon', tags:['greetings'], memo:'presto = soon, fast, as in music: play it presto.',
     parts:[{t:'A', m:'until'},{t:'presto', m:'soon'}]},
    {id:'greet-a-dopo', term:'A dopo', en:'See you later', tags:['greetings'], memo:'dopo = after, later. A dopo = until after.',
     parts:[{t:'A', m:'until'},{t:'dopo', m:'later, after'}]},
    {id:'greet-come-stai', term:'Come stai?', en:'How are you? (informal)', tags:['greetings'], memo:'come = how, stai = you stand, from stare: Italians ask how you "stand".',
     parts:[{t:'Come', m:'how'},{t:'stai', m:'you are (stare, informal)'}], ex:{term:'Ciao Marco, come stai?', en:'Hi Marco, how are you?'}},
    {id:'greet-come-sta', term:'Come sta?', en:'How are you? (formal)', tags:['greetings'], memo:'Same as come stai, but with the formal "Lei" verb form: sta. Use it with anyone you call Lei.',
     parts:[{t:'Come', m:'how'},{t:'sta', m:'you are (formal, Lei)'}]},
    {id:'greet-bene-grazie', term:'Bene, grazie. E tu?', en:'Fine, thanks. And you?', tags:['greetings'], memo:'bene = well (benefit), tu = you (thou). Formal: E Lei?',
     parts:[{t:'Bene', m:'well'},{t:'grazie', m:'thanks'},{t:'E', m:'and'},{t:'tu', m:'you (informal)'}]},
    {id:'greet-tutto-bene', term:'Tutto bene?', en:'Everything OK?', tags:['greetings'], memo:'tutto = all (total), bene = well. Also the answer: Tutto bene.',
     parts:[{t:'Tutto', m:'all, everything'},{t:'bene', m:'well'}]},
    {id:'greet-piacere', term:'Piacere', en:'Nice to meet you', tags:['greetings'], memo:'Literally "pleasure", as in "it pleases me". The same root as mi piace (I like).',
     parts:[{t:'Piacere', m:'pleasure'}], ex:{term:'Piacere, sono Sam.', en:'Nice to meet you, I\'m Sam.'}},
    {id:'greet-mi-chiamo', term:'Mi chiamo…', en:'My name is…', tags:['greetings','basics'], memo:'"I call myself…", chiamare = to call (claim). The mi is the reflexive "myself".',
     parts:[{t:'Mi', m:'myself'},{t:'chiamo', m:'I call'}], ex:{term:'Mi chiamo Sam, e tu?', en:'My name is Sam, and you?'}},
    {id:'greet-come-ti-chiami', term:'Come ti chiami?', en:'What\'s your name? (informal)', tags:['greetings','questions'], memo:'"How do you call yourself?" Formal: Come si chiama?',
     parts:[{t:'Come', m:'how'},{t:'ti', m:'yourself'},{t:'chiami', m:'you call'}]},

    /* ---------------- POLITENESS ---------------- */
    {id:'pol-grazie', term:'Grazie', en:'Thank you', tags:['politeness'], memo:'grace, gratitude: grazie. Say GRA-tsyeh, the z is "ts".',
     parts:[{t:'Grazie', m:'thanks'}]},
    {id:'pol-grazie-mille', term:'Grazie mille', en:'Thanks a lot', tags:['politeness'], memo:'"A thousand thanks". mille = thousand (millennium).',
     parts:[{t:'Grazie', m:'thanks'},{t:'mille', m:'a thousand'}]},
    {id:'pol-prego', term:'Prego', en:'You\'re welcome / Please, go ahead', tags:['politeness'], memo:'From pregare, to pray: "I beg you". The reply to grazie, and what a waiter says to mean "go ahead, what would you like".',
     parts:[{t:'Prego', m:'you\'re welcome; go ahead'}], note:'You will hear it constantly: after grazie, when being ushered through a door, when a shopkeeper is ready for you.'},
    {id:'pol-per-favore', term:'Per favore', en:'Please', tags:['politeness'], memo:'"For a favour". Tag it on the end of any request.',
     parts:[{t:'Per', m:'for'},{t:'favore', m:'favour'}]},
    {id:'pol-scusi', term:'Scusi', en:'Excuse me (formal)', tags:['politeness'], memo:'excuse → scusi. The formal form, for strangers. Use it to get attention and to apologise.',
     parts:[{t:'Scusi', m:'excuse me (Lei form)'}], ex:{term:'Scusi, dov\'è la stazione?', en:'Excuse me, where is the station?'}},
    {id:'pol-scusa', term:'Scusa', en:'Sorry / Excuse me (informal)', tags:['politeness'], memo:'Same word, -a ending for tu. Scusa to a friend, scusi to a stranger.',
     parts:[{t:'Scusa', m:'excuse me (tu form)'}]},
    {id:'pol-mi-dispiace', term:'Mi dispiace', en:'I\'m sorry', tags:['politeness'], memo:'"It displeases me": dis- + piacere. For real regret, not for squeezing past someone.',
     parts:[{t:'Mi', m:'to me'},{t:'dis-', m:'un-, dis-'},{t:'-piace', m:'pleases'}]},
    {id:'pol-permesso', term:'Permesso', en:'Excuse me (passing through)', tags:['politeness'], memo:'"Permission?" Said when squeezing through a crowd or entering someone\'s home.',
     parts:[{t:'Permesso', m:'permission, may I'}]},
    {id:'pol-si', term:'Sì', en:'Yes', tags:['politeness','basics'], memo:'With the accent. Without it, si means "oneself".',
     parts:[{t:'Sì', m:'yes'}]},
    {id:'pol-no', term:'No', en:'No', tags:['politeness','basics'], memo:'Same as English. "No, grazie" is the polite refusal.',
     parts:[{t:'No', m:'no'}]},
    {id:'pol-va-bene', term:'Va bene', en:'OK / Alright', tags:['politeness','basics'], memo:'"It goes well." The all-purpose agreement; also a question: Va bene?',
     parts:[{t:'Va', m:'it goes'},{t:'bene', m:'well'}]},
    {id:'pol-certo', term:'Certo', en:'Of course / Sure', tags:['politeness'], memo:'certain → certo.',
     parts:[{t:'Certo', m:'certainly'}]},
    {id:'pol-non-importa', term:'Non importa', en:'It doesn\'t matter', tags:['politeness'], memo:'"Not important." importare = to matter.',
     parts:[{t:'Non', m:'not'},{t:'importa', m:'it matters'}]},
    {id:'pol-salute', term:'Salute!', en:'Cheers! / Bless you!', tags:['politeness'], memo:'"Health!" For a toast and for a sneeze. Cin cin is the other toast.',
     parts:[{t:'Salute', m:'health'}]},
    {id:'pol-buon-appetito', term:'Buon appetito', en:'Enjoy your meal', tags:['politeness','food'], memo:'Said before eating, by everyone, every time. Reply: Grazie, altrettanto (likewise).',
     parts:[{t:'Buon', m:'good'},{t:'appetito', m:'appetite'}]},

    /* ---------------- BASICS ---------------- */
    {id:'basic-non-capisco', term:'Non capisco', en:'I don\'t understand', tags:['basics','survival'], memo:'capire = to understand (capacity: what your head can take). Non in front negates any verb.',
     parts:[{t:'Non', m:'not'},{t:'capisco', m:'I understand'}]},
    {id:'basic-capisco', term:'Capisco', en:'I understand', tags:['basics'], memo:'Same verb, no non. Capito! = got it.',
     parts:[{t:'Capisco', m:'I understand'}]},
    {id:'basic-parla-inglese', term:'Parla inglese?', en:'Do you speak English?', tags:['basics','survival'], memo:'parlare = to speak (parley, parliament). Lei form for strangers: parla. Questions just rise at the end.',
     parts:[{t:'Parla', m:'you speak (formal)'},{t:'inglese', m:'English'}]},
    {id:'basic-non-parlo', term:'Non parlo bene l\'italiano', en:'I don\'t speak Italian well', tags:['basics','survival'], memo:'parlo = I speak. The l\' is "the", used before a vowel.',
     parts:[{t:'Non', m:'not'},{t:'parlo', m:'I speak'},{t:'bene', m:'well'},{t:'l\'', m:'the'},{t:'italiano', m:'Italian'}]},
    {id:'basic-piu-lentamente', term:'Più lentamente, per favore', en:'More slowly, please', tags:['basics','survival'], memo:'più = more (plus), lento = slow (lento in music), -mente = -ly.',
     parts:[{t:'Più', m:'more'},{t:'lenta-', m:'slow'},{t:'-mente', m:'-ly'},{t:'per favore', m:'please'}]},
    {id:'basic-puo-ripetere', term:'Può ripetere?', en:'Can you repeat that?', tags:['basics','survival'], memo:'può = you can (formal, from potere). ripetere = repeat. Informal: Puoi ripetere?',
     parts:[{t:'Può', m:'you can (formal)'},{t:'ripetere', m:'to repeat'}]},
    {id:'basic-lo-so', term:'Lo so', en:'I know', tags:['basics'], memo:'so = I know (sapere), lo = it. "It I know." Non lo so = I don\'t know, the phrase you will use most.',
     parts:[{t:'Lo', m:'it'},{t:'so', m:'I know'}], ex:{term:'Non lo so.', en:'I don\'t know.'}},
    {id:'basic-forse', term:'Forse', en:'Maybe', tags:['basics'], memo:'From Latin "fors" = chance. FOR-seh.',
     parts:[{t:'Forse', m:'maybe'}]},
    {id:'basic-allora', term:'Allora', en:'So… / Well then…', tags:['basics','connectors'], memo:'The Italian "so, then". Starts half of all sentences. Allora, andiamo? = So, shall we go?',
     parts:[{t:'Allora', m:'so, then, well'}]},
    {id:'basic-ecco', term:'Ecco', en:'Here it is / There you go', tags:['basics'], memo:'Latin "ecce" (ecce homo: behold the man). Ecco il conto = here\'s the bill.',
     parts:[{t:'Ecco', m:'here is, behold'}]},
    {id:'basic-niente', term:'Niente', en:'Nothing', tags:['basics'], memo:'Di niente = "of nothing" = you\'re welcome, the casual version of prego.',
     parts:[{t:'Niente', m:'nothing'}], ex:{term:'Di niente!', en:'Don\'t mention it!'}},
    {id:'basic-anche', term:'Anche', en:'Also / too', tags:['basics','connectors'], memo:'Anch\'io = me too (the e drops before io).',
     parts:[{t:'Anche', m:'also'}], ex:{term:'Anch\'io!', en:'Me too!'}},

    /* ---------------- NUMBERS ---------------- */
    {id:'num-uno', term:'uno', en:'one', tags:['numbers'], memo:'uni-, unit. Before a noun it becomes un / una (a, one): un caffè, una birra.',
     parts:[{t:'uno', m:'one'}]},
    {id:'num-due', term:'due', en:'two', tags:['numbers'], memo:'duo, duet. DOO-eh.',
     parts:[{t:'due', m:'two'}]},
    {id:'num-tre', term:'tre', en:'three', tags:['numbers'], memo:'trio, tripod.',
     parts:[{t:'tre', m:'three'}]},
    {id:'num-quattro', term:'quattro', en:'four', tags:['numbers'], memo:'quartet, quarter. Say KWAT-tro with a double t.',
     parts:[{t:'quattro', m:'four'}]},
    {id:'num-cinque', term:'cinque', en:'five', tags:['numbers'], memo:'cinquecento = the 500s, the 1500s in art. CHEEN-kweh.',
     parts:[{t:'cinque', m:'five'}]},
    {id:'num-sei', term:'sei', en:'six', tags:['numbers'], memo:'Same spelling as "you are" (tu sei). Context sorts it out.',
     parts:[{t:'sei', m:'six'}]},
    {id:'num-sette', term:'sette', en:'seven', tags:['numbers'], memo:'September was month seven. SET-teh.',
     parts:[{t:'sette', m:'seven'}]},
    {id:'num-otto', term:'otto', en:'eight', tags:['numbers'], memo:'octopus, October (month eight).',
     parts:[{t:'otto', m:'eight'}]},
    {id:'num-nove', term:'nove', en:'nine', tags:['numbers'], memo:'November, month nine. NO-veh.',
     parts:[{t:'nove', m:'nine'}]},
    {id:'num-dieci', term:'dieci', en:'ten', tags:['numbers'], memo:'decimal, decade. DYEH-chee.',
     parts:[{t:'dieci', m:'ten'}]},
    {id:'num-venti', term:'venti', en:'twenty', tags:['numbers'], memo:'Starbucks "venti" = 20 ounces. ventuno (21), ventidue (22): just glue the digit on.',
     parts:[{t:'venti', m:'twenty'}]},
    {id:'num-trenta', term:'trenta', en:'thirty', tags:['numbers'], memo:'tre + -nta. Then quaranta, cinquanta, sessanta, settanta, ottanta, novanta: all end in -anta.',
     parts:[{t:'tre-', m:'three'},{t:'-nta', m:'-ty'}]},
    {id:'num-cento', term:'cento', en:'a hundred', tags:['numbers'], memo:'cent, century, percent. CHEN-to.',
     parts:[{t:'cento', m:'hundred'}]},
    {id:'num-mille', term:'mille', en:'a thousand', tags:['numbers'], memo:'millennium, mile (a thousand paces). Plural: duemila.',
     parts:[{t:'mille', m:'thousand'}]},
    {id:'num-quanto-costa', term:'Quanto costa?', en:'How much does it cost?', tags:['numbers','shopping'], memo:'quanto = how much (quantity), costa = it costs. Plural: Quanto costano?',
     parts:[{t:'Quanto', m:'how much'},{t:'costa', m:'it costs'}], ex:{term:'Scusi, quanto costa questo?', en:'Excuse me, how much is this?'}},
    {id:'num-euro', term:'Sono dieci euro', en:'That\'s ten euros', tags:['numbers','shopping'], memo:'sono = they are (plural with money). euro never changes: dieci euro.',
     parts:[{t:'Sono', m:'they are'},{t:'dieci', m:'ten'},{t:'euro', m:'euros'}]},

    /* ---------------- FOOD AND DRINK ---------------- */
    {id:'food-caffe', term:'un caffè', en:'a coffee (an espresso)', tags:['food'], memo:'Stress on the è: caf-FÈ. Ordering "a coffee" gets you an espresso, standing at the bar.',
     parts:[{t:'un', m:'a (masculine)'},{t:'caffè', m:'coffee'}], ex:{term:'Un caffè, per favore.', en:'An espresso, please.'}},
    {id:'food-cappuccino', term:'un cappuccino', en:'a cappuccino', tags:['food'], memo:'Named for the Capuchin monks\' brown hoods. Morning only, in Italian eyes.',
     parts:[{t:'un', m:'a'},{t:'cappuccino', m:'cappuccino'}]},
    {id:'food-acqua', term:'acqua', en:'water', tags:['food'], memo:'aqua, aquarium. Naturale = still, frizzante = sparkling.',
     parts:[{t:'acqua', m:'water'}], ex:{term:'Acqua naturale o frizzante?', en:'Still or sparkling water?'}},
    {id:'food-vino', term:'vino', en:'wine', tags:['food'], memo:'vine, vineyard. Rosso = red, bianco = white.',
     parts:[{t:'vino', m:'wine'}], ex:{term:'Un bicchiere di vino rosso.', en:'A glass of red wine.'}},
    {id:'food-birra', term:'una birra', en:'a beer', tags:['food'], memo:'beer with an Italian -a. Feminine, so una.',
     parts:[{t:'una', m:'a (feminine)'},{t:'birra', m:'beer'}]},
    {id:'food-pane', term:'pane', en:'bread', tags:['food'], memo:'Latin panis: pantry, companion (someone you share bread with).',
     parts:[{t:'pane', m:'bread'}]},
    {id:'food-formaggio', term:'formaggio', en:'cheese', tags:['food'], memo:'From "forma", the mould cheese is shaped in. French fromage is the same word.',
     parts:[{t:'formaggio', m:'cheese'}]},
    {id:'food-pasta', term:'la pasta', en:'pasta', tags:['food'], memo:'Also means "pastry" and "dough". A pasticceria sells cakes, not spaghetti.',
     parts:[{t:'la', m:'the (feminine)'},{t:'pasta', m:'pasta'}]},
    {id:'food-pesce', term:'pesce', en:'fish', tags:['food'], memo:'Pisces. PEH-sheh: sc before e is "sh".',
     parts:[{t:'pesce', m:'fish'}]},
    {id:'food-carne', term:'carne', en:'meat', tags:['food'], memo:'carnivore, carnival (farewell to meat).',
     parts:[{t:'carne', m:'meat'}]},
    {id:'food-pollo', term:'pollo', en:'chicken', tags:['food'], memo:'poultry. POL-lo.',
     parts:[{t:'pollo', m:'chicken'}]},
    {id:'food-verdure', term:'verdure', en:'vegetables', tags:['food'], memo:'verde = green: "the greens".',
     parts:[{t:'verd-', m:'green'},{t:'-ure', m:'(plural noun ending)'}]},
    {id:'food-insalata', term:'insalata', en:'salad', tags:['food'], memo:'"Salted": salad comes from the salt in the dressing.',
     parts:[{t:'in-', m:'in'},{t:'-salata', m:'salted'}]},
    {id:'food-gelato', term:'un gelato', en:'an ice cream', tags:['food'], memo:'"Frozen", from gelare, like gelatin. Order by number of flavours: due gusti.',
     parts:[{t:'un', m:'a'},{t:'gelato', m:'ice cream'}], ex:{term:'Un gelato con due gusti, per favore.', en:'An ice cream with two flavours, please.'}},
    {id:'food-dolce', term:'un dolce', en:'a dessert', tags:['food'], memo:'dolce = sweet (la dolce vita). Il dolce is the dessert course.',
     parts:[{t:'un', m:'a'},{t:'dolce', m:'sweet, dessert'}]},
    {id:'food-senza', term:'senza', en:'without', tags:['food','basics'], memo:'Senza glutine, senza zucchero. SEN-tsa.',
     parts:[{t:'senza', m:'without'}], ex:{term:'Un caffè senza zucchero.', en:'A coffee without sugar.'}},
    {id:'food-con', term:'con', en:'with', tags:['food','basics'], memo:'con- as in connect, combine: with.',
     parts:[{t:'con', m:'with'}], ex:{term:'Pasta con pomodoro.', en:'Pasta with tomato.'}},
    {id:'food-buonissimo', term:'Buonissimo!', en:'Delicious!', tags:['food','feelings'], memo:'buono + -issimo (very): "very good". -issimo turns any adjective up to eleven.',
     parts:[{t:'Buon-', m:'good'},{t:'-issimo', m:'very, extremely'}]},
    {id:'food-ho-fame', term:'Ho fame', en:'I\'m hungry', tags:['food','feelings'], memo:'"I have hunger" (famine). Italians have hunger, thirst and years rather than being them.',
     parts:[{t:'Ho', m:'I have'},{t:'fame', m:'hunger'}]},
    {id:'food-ho-sete', term:'Ho sete', en:'I\'m thirsty', tags:['food','feelings'], memo:'"I have thirst". SEH-teh.',
     parts:[{t:'Ho', m:'I have'},{t:'sete', m:'thirst'}]},

    /* ---------------- AT THE RESTAURANT ---------------- */
    {id:'rest-tavolo-due', term:'Un tavolo per due, per favore', en:'A table for two, please', tags:['restaurant'], memo:'tavolo = table (tablet). Swap the number: per tre, per quattro.',
     parts:[{t:'Un', m:'a'},{t:'tavolo', m:'table'},{t:'per', m:'for'},{t:'due', m:'two'},{t:'per favore', m:'please'}]},
    {id:'rest-prenotazione', term:'Ho una prenotazione', en:'I have a reservation', tags:['restaurant'], memo:'prenotare = to pre-note, to book. A nome di Sam = under the name Sam.',
     parts:[{t:'Ho', m:'I have'},{t:'una', m:'a'},{t:'prenotazione', m:'booking'}], ex:{term:'Ho una prenotazione a nome di Sam.', en:'I have a booking under the name Sam.'}},
    {id:'rest-menu', term:'Il menù, per favore', en:'The menu, please', tags:['restaurant'], memo:'Stress on the ù. Also: la carta (the list).',
     parts:[{t:'Il', m:'the (masculine)'},{t:'menù', m:'menu'}]},
    {id:'rest-vorrei', term:'Vorrei…', en:'I would like…', tags:['restaurant','verbs'], memo:'The politest way to order anything. From volere (to want): vor-REI. Then just name the dish.',
     parts:[{t:'Vorrei', m:'I would like'}], ex:{term:'Vorrei una pizza margherita.', en:'I\'d like a margherita pizza.'}},
    {id:'rest-prendo', term:'Prendo…', en:'I\'ll have…', tags:['restaurant','verbs'], memo:'"I take": prendere, like apprehend. Per me = for me.',
     parts:[{t:'Prendo', m:'I take, I\'ll have'}], ex:{term:'Per me, prendo il risotto.', en:'For me, I\'ll have the risotto.'}},
    {id:'rest-cosa-consiglia', term:'Cosa mi consiglia?', en:'What do you recommend?', tags:['restaurant','asking'], memo:'consigliare = to counsel, advise. mi = to me.',
     parts:[{t:'Cosa', m:'what'},{t:'mi', m:'to me'},{t:'consiglia', m:'you advise (formal)'}]},
    {id:'rest-cose', term:'Cos\'è questo?', en:'What is this?', tags:['restaurant','asking'], memo:'cosa + è = cos\'è (what is). questo = this.',
     parts:[{t:'Cos\'', m:'what'},{t:'è', m:'is'},{t:'questo', m:'this'}]},
    {id:'rest-conto', term:'Il conto, per favore', en:'The bill, please', tags:['restaurant'], memo:'conto = account, count. You usually have to ask; it will not come on its own.',
     parts:[{t:'Il', m:'the'},{t:'conto', m:'bill, account'}]},
    {id:'rest-carta', term:'Posso pagare con la carta?', en:'Can I pay by card?', tags:['restaurant','shopping'], memo:'posso = can I (possible), pagare = to pay, carta = card. In contanti = in cash.',
     parts:[{t:'Posso', m:'can I'},{t:'pagare', m:'to pay'},{t:'con', m:'with'},{t:'la carta', m:'the card'}]},
    {id:'rest-coperto', term:'il coperto', en:'the cover charge', tags:['restaurant'], memo:'"The covered (place setting)". A per-person charge for bread and the table; not a tip.',
     parts:[{t:'il', m:'the'},{t:'coperto', m:'cover charge'}]},
    {id:'rest-era-buonissimo', term:'Era buonissimo', en:'It was delicious', tags:['restaurant','food'], memo:'era = it was. The compliment every kitchen wants.',
     parts:[{t:'Era', m:'it was'},{t:'buonissimo', m:'delicious'}]},
    {id:'rest-sono-allergico', term:'Sono allergico a…', en:'I\'m allergic to…', tags:['restaurant','survival'], memo:'allergic → allergico (-a if you are a woman). Alle noci = to nuts.',
     parts:[{t:'Sono', m:'I am'},{t:'allergico', m:'allergic'},{t:'a', m:'to'}], ex:{term:'Sono allergica alle noci.', en:'I\'m allergic to nuts (said by a woman).'}},
    {id:'rest-vegetariano', term:'Sono vegetariano', en:'I\'m vegetarian', tags:['restaurant','food'], memo:'-o for a man, -a for a woman: vegetariana.',
     parts:[{t:'Sono', m:'I am'},{t:'vegetariano', m:'vegetarian'}]},
    {id:'rest-ancora', term:'Ancora un po\', per favore', en:'A little more, please', tags:['restaurant'], memo:'ancora = still, again, more (the anchor holds). un po\' = a bit (un poco).',
     parts:[{t:'Ancora', m:'more, again'},{t:'un po\'', m:'a little'}]},
    {id:'rest-basta', term:'Basta così, grazie', en:'That\'s enough, thanks', tags:['restaurant'], memo:'basta = enough (Basta! = stop). così = like this.',
     parts:[{t:'Basta', m:'enough'},{t:'così', m:'like this'}]},

    /* ---------------- SHOPPING ---------------- */
    {id:'shop-quanto', term:'Quant\'è?', en:'How much is it?', tags:['shopping'], memo:'quanto + è: "how much is". The short form of quanto costa.',
     parts:[{t:'Quant\'', m:'how much'},{t:'è', m:'is'}]},
    {id:'shop-troppo-caro', term:'È troppo caro', en:'It\'s too expensive', tags:['shopping'], memo:'caro = dear, both "expensive" and "beloved" (cara mia). troppo = too much.',
     parts:[{t:'È', m:'it is'},{t:'troppo', m:'too'},{t:'caro', m:'expensive, dear'}]},
    {id:'shop-lo-prendo', term:'Lo prendo', en:'I\'ll take it', tags:['shopping'], memo:'lo = it, prendo = I take. For a feminine thing: La prendo.',
     parts:[{t:'Lo', m:'it'},{t:'prendo', m:'I take'}]},
    {id:'shop-solo-guardo', term:'Sto solo guardando', en:'I\'m just looking', tags:['shopping'], memo:'solo = only (solo), guardare = to look (guard: keep watch). sto + -ando = I am …-ing.',
     parts:[{t:'Sto', m:'I am'},{t:'solo', m:'only'},{t:'guardando', m:'looking'}]},
    {id:'shop-avete', term:'Avete…?', en:'Do you have…?', tags:['shopping','asking'], memo:'avete = you (all) have, what you ask a shop or restaurant as a whole.',
     parts:[{t:'Avete', m:'you (plural) have'}], ex:{term:'Avete una taglia più grande?', en:'Do you have a bigger size?'}},
    {id:'shop-aperto', term:'aperto / chiuso', en:'open / closed', tags:['shopping'], memo:'aperture = opening; chiuso like "close". The sign on the door. Many shops chiuso 1 to 4 pm.',
     parts:[{t:'aperto', m:'open'},{t:'chiuso', m:'closed'}]},
    {id:'shop-scontrino', term:'lo scontrino', en:'the receipt', tags:['shopping'], memo:'From sconto (discount, a deduction): the slip that "accounts" the sale. Keep it; they may ask.',
     parts:[{t:'lo', m:'the (before s + consonant)'},{t:'scontrino', m:'receipt'}]},
    {id:'shop-sconto', term:'C\'è uno sconto?', en:'Is there a discount?', tags:['shopping'], memo:'c\'è = there is (ci è). sconto = discount.',
     parts:[{t:'C\'è', m:'there is'},{t:'uno', m:'a'},{t:'sconto', m:'discount'}]},
    {id:'shop-busta', term:'Una busta, per favore', en:'A bag, please', tags:['shopping'], memo:'busta = bag, envelope. Bags cost a few cents; you will be asked: Vuole una busta?',
     parts:[{t:'Una', m:'a'},{t:'busta', m:'bag'}]},
    {id:'shop-questo-quello', term:'questo / quello', en:'this / that', tags:['shopping','basics'], memo:'questo = this (near), quello = that (far). Point and say it.',
     parts:[{t:'questo', m:'this'},{t:'quello', m:'that'}]},

    /* ---------------- QUESTIONS ---------------- */
    {id:'q-dove', term:'Dove?', en:'Where?', tags:['questions'], memo:'DO-veh. Dov\'è = where is (dove + è).',
     parts:[{t:'Dove', m:'where'}], ex:{term:'Dov\'è il bagno?', en:'Where is the bathroom?'}},
    {id:'q-quando', term:'Quando?', en:'When?', tags:['questions'], memo:'Looks like "when" with a qu. KWAN-do.',
     parts:[{t:'Quando', m:'when'}]},
    {id:'q-perche', term:'Perché?', en:'Why? / Because', tags:['questions','connectors'], memo:'Both question and answer: Perché? Perché sì. per + che = "for what". Stress the é: per-KÉ.',
     parts:[{t:'Per-', m:'for'},{t:'-ché', m:'what'}]},
    {id:'q-come', term:'Come?', en:'How? / Pardon?', tags:['questions'], memo:'Come? on its own means "sorry, what?". Come si dice…? = how do you say…?',
     parts:[{t:'Come', m:'how'}]},
    {id:'q-cosa', term:'Cosa? / Che cosa?', en:'What?', tags:['questions'], memo:'cosa = thing: "what thing?". Che cosa is fuller; cosa alone is fine.',
     parts:[{t:'Che', m:'what'},{t:'cosa', m:'thing'}]},
    {id:'q-chi', term:'Chi?', en:'Who?', tags:['questions'], memo:'KEE. ch is always a hard k in Italian: chi, che, chiesa.',
     parts:[{t:'Chi', m:'who'}]},
    {id:'q-quale', term:'Quale?', en:'Which?', tags:['questions'], memo:'quality: "which kind". Qual è = which is.',
     parts:[{t:'Quale', m:'which'}]},
    {id:'q-quanto', term:'Quanto?', en:'How much?', tags:['questions'], memo:'quantity. Quanti? = how many (plural).',
     parts:[{t:'Quanto', m:'how much'}]},
    {id:'q-che-ore', term:'Che ore sono?', en:'What time is it?', tags:['questions','time'], memo:'"What hours are they?" ore = hours. Answer: Sono le tre = it\'s three.',
     parts:[{t:'Che', m:'what'},{t:'ore', m:'hours'},{t:'sono', m:'are'}]},
    {id:'q-ce', term:'C\'è…?', en:'Is there…?', tags:['questions'], memo:'ci + è = there is. Plural: ci sono. Flat tone = statement, rising = question.',
     parts:[{t:'C\'', m:'there'},{t:'è', m:'is'}], ex:{term:'C\'è una farmacia qui vicino?', en:'Is there a pharmacy near here?'}},

    /* ---------------- ASKING FOR WORDS ---------------- */
    {id:'ask-come-si-dice', term:'Come si dice… in italiano?', en:'How do you say… in Italian?', tags:['asking'], memo:'"How does one say". si = one (impersonal), dice = says (dictate).',
     parts:[{t:'Come', m:'how'},{t:'si', m:'one'},{t:'dice', m:'says'},{t:'in italiano', m:'in Italian'}]},
    {id:'ask-cosa-significa', term:'Cosa significa?', en:'What does it mean?', tags:['asking'], memo:'significare = to signify.',
     parts:[{t:'Cosa', m:'what'},{t:'significa', m:'it means'}]},
    {id:'ask-cosa-vuol-dire', term:'Cosa vuol dire…?', en:'What does… mean?', tags:['asking'], memo:'"What does it want to say": vuol(e) dire = means. Very common.',
     parts:[{t:'Cosa', m:'what'},{t:'vuol', m:'wants to'},{t:'dire', m:'say'}], ex:{term:'Cosa vuol dire "magari"?', en:'What does "magari" mean?'}},
    {id:'ask-come-si-scrive', term:'Come si scrive?', en:'How is it spelled?', tags:['asking'], memo:'scrivere = to write (scribe, script).',
     parts:[{t:'Come', m:'how'},{t:'si', m:'one'},{t:'scrive', m:'writes'}]},
    {id:'ask-puo-scrivere', term:'Me lo può scrivere?', en:'Can you write it down for me?', tags:['asking'], memo:'me lo = it to me, può = you can. Hand them your phone.',
     parts:[{t:'Me', m:'to me'},{t:'lo', m:'it'},{t:'può', m:'you can (formal)'},{t:'scrivere', m:'to write'}]},

    /* ---------------- PRONOUNS AND PEOPLE ---------------- */
    {id:'pro-io', term:'io', en:'I', tags:['pronouns'], memo:'EE-oh. Usually dropped: the verb ending says who. Io sono = sono.',
     parts:[{t:'io', m:'I'}]},
    {id:'pro-tu', term:'tu', en:'you (informal)', tags:['pronouns'], memo:'thou. Friends, family, anyone your age in a casual setting.',
     parts:[{t:'tu', m:'you (one person, informal)'}]},
    {id:'pro-lei', term:'Lei', en:'you (formal) / she', tags:['pronouns'], memo:'Capital Lei = formal you (for strangers, shops, officials); lowercase lei = she. The verb goes in the third person: Lei parla.',
     parts:[{t:'Lei', m:'you (formal); she'}]},
    {id:'pro-lui', term:'lui', en:'he', tags:['pronouns'], memo:'LOO-ee.',
     parts:[{t:'lui', m:'he'}]},
    {id:'pro-noi', term:'noi', en:'we', tags:['pronouns'], memo:'NOY. Verb ending -iamo: andiamo, mangiamo.',
     parts:[{t:'noi', m:'we'}]},
    {id:'pro-voi', term:'voi', en:'you (plural)', tags:['pronouns'], memo:'VOY. Verb ending -ate / -ete / -ite: avete, parlate.',
     parts:[{t:'voi', m:'you all'}]},
    {id:'pro-loro', term:'loro', en:'they', tags:['pronouns'], memo:'LO-ro. Verb ending -ano / -ono: parlano, sono.',
     parts:[{t:'loro', m:'they'}]},
    {id:'pro-mio', term:'il mio / la mia', en:'my', tags:['pronouns'], memo:'Takes the article: il mio caffè, la mia casa. tuo = your, suo = his/her/your (formal).',
     parts:[{t:'il/la', m:'the'},{t:'mio/mia', m:'my (m/f)'}]},
    {id:'pro-signore', term:'signore / signora', en:'sir / madam', tags:['pronouns','politeness'], memo:'Also Mr / Mrs. Signorina for a young woman is dated; signora is safer.',
     parts:[{t:'signore', m:'sir, Mr'},{t:'signora', m:'madam, Mrs'}]},
    {id:'pro-amico', term:'amico / amica', en:'friend', tags:['pronouns'], memo:'amicable, amity. -o male, -a female, amici plural.',
     parts:[{t:'amic-', m:'friend'},{t:'-o/-a', m:'male/female'}]},

    /* ---------------- VERBS ---------------- */
    {id:'verb-essere', term:'Sono', en:'I am', tags:['verbs'], memo:'essere = to be. sono, sei, è, siamo, siete, sono. Note sono = I am and also they are.',
     parts:[{t:'Sono', m:'I am'}], ex:{term:'Sono americano.', en:'I\'m American.'}},
    {id:'verb-e', term:'È', en:'It is / he is / she is', tags:['verbs'], memo:'The accent matters: è = is, e = and. È bello = it\'s beautiful.',
     parts:[{t:'È', m:'is'}]},
    {id:'verb-avere', term:'Ho', en:'I have', tags:['verbs'], memo:'avere = to have. The h is silent: ho sounds like "o". ho, hai, ha, abbiamo, avete, hanno.',
     parts:[{t:'Ho', m:'I have'}], ex:{term:'Ho trent\'anni.', en:'I\'m thirty (I have thirty years).'}},
    {id:'verb-voglio', term:'Voglio', en:'I want', tags:['verbs'], memo:'volere = to want (volition). VOL-yo. Blunt; vorrei is the polite version.',
     parts:[{t:'Voglio', m:'I want'}]},
    {id:'verb-posso', term:'Posso…?', en:'Can I…?', tags:['verbs'], memo:'potere = to be able (potent, possible). Posso entrare? = may I come in?',
     parts:[{t:'Posso', m:'I can, may I'}], ex:{term:'Posso provare?', en:'Can I try it on?'}},
    {id:'verb-devo', term:'Devo', en:'I have to', tags:['verbs'], memo:'dovere = must, to owe (debt, due). Devo andare = I have to go.',
     parts:[{t:'Devo', m:'I must'}]},
    {id:'verb-andare', term:'Vado', en:'I go', tags:['verbs'], memo:'andare = to go, irregular: vado, vai, va, andiamo, andate, vanno. Vado a Roma.',
     parts:[{t:'Vado', m:'I go'}], ex:{term:'Vado a casa.', en:'I\'m going home.'}},
    {id:'verb-andiamo', term:'Andiamo!', en:'Let\'s go!', tags:['verbs'], memo:'The noi form doubles as "let\'s": andiamo, mangiamo (let\'s eat).',
     parts:[{t:'And-', m:'go'},{t:'-iamo', m:'we / let\'s'}]},
    {id:'verb-mangiare', term:'Mangio', en:'I eat', tags:['verbs','food'], memo:'mangiare, as in "manger" and "blancmange". MAN-jo.',
     parts:[{t:'Mangio', m:'I eat'}]},
    {id:'verb-bere', term:'Bevo', en:'I drink', tags:['verbs','food'], memo:'bere = to drink (beverage). Cosa bevi? = what are you drinking?',
     parts:[{t:'Bevo', m:'I drink'}]},
    {id:'verb-parlare', term:'Parlo', en:'I speak', tags:['verbs'], memo:'parlare: the regular -are model. parlo, parli, parla, parliamo, parlate, parlano.',
     parts:[{t:'Parl-', m:'speak'},{t:'-o', m:'I'}]},
    {id:'verb-sapere', term:'So', en:'I know (a fact)', tags:['verbs'], memo:'sapere = to know facts (savvy, sapient). Non so = I don\'t know.',
     parts:[{t:'So', m:'I know'}]},
    {id:'verb-conoscere', term:'Conosco', en:'I know (a person or place)', tags:['verbs'], memo:'conoscere = to be acquainted with (cognition, recognise). Conosco Roma = I know Rome.',
     parts:[{t:'Conosco', m:'I know, I\'m familiar with'}]},
    {id:'verb-mi-piace', term:'Mi piace', en:'I like it', tags:['verbs','feelings'], memo:'"It pleases me". The thing is the subject: mi piace la pizza, mi piacciono le pizze (plural).',
     parts:[{t:'Mi', m:'to me'},{t:'piace', m:'pleases'}], ex:{term:'Mi piace molto!', en:'I like it a lot!'}},
    {id:'verb-non-mi-piace', term:'Non mi piace', en:'I don\'t like it', tags:['verbs','feelings'], memo:'non in front of the whole thing.',
     parts:[{t:'Non', m:'not'},{t:'mi', m:'to me'},{t:'piace', m:'pleases'}]},
    {id:'verb-cerco', term:'Cerco…', en:'I\'m looking for…', tags:['verbs','survival'], memo:'cercare = to search (search, with a c). Cerco la stazione.',
     parts:[{t:'Cerco', m:'I look for'}]},
    {id:'verb-aspetta', term:'Aspetta!', en:'Wait!', tags:['verbs'], memo:'aspettare = to wait (expect). Formal: Aspetti.',
     parts:[{t:'Aspetta', m:'wait (tu)'}]},
    {id:'verb-vieni', term:'Vieni qui', en:'Come here', tags:['verbs'], memo:'venire = to come (venue, advent). qui = here.',
     parts:[{t:'Vieni', m:'come (tu)'},{t:'qui', m:'here'}]},
    {id:'verb-faccio', term:'Faccio', en:'I do / I make', tags:['verbs'], memo:'fare = do, make (fact, factory). FACH-cho. Cosa fai? = what are you doing / what do you do?',
     parts:[{t:'Faccio', m:'I do, I make'}]},

    /* ---------------- TIME ---------------- */
    {id:'time-oggi', term:'oggi', en:'today', tags:['time'], memo:'OD-jee. Latin hodie.',
     parts:[{t:'oggi', m:'today'}]},
    {id:'time-domani', term:'domani', en:'tomorrow', tags:['time'], memo:'A domani = see you tomorrow. Dopodomani = the day after.',
     parts:[{t:'domani', m:'tomorrow'}]},
    {id:'time-ieri', term:'ieri', en:'yesterday', tags:['time'], memo:'YEH-ree. Latin heri.',
     parts:[{t:'ieri', m:'yesterday'}]},
    {id:'time-adesso', term:'adesso', en:'now', tags:['time'], memo:'ad-ESS-o. Ora also means now (and "hour").',
     parts:[{t:'adesso', m:'now'}]},
    {id:'time-dopo', term:'dopo', en:'after / later', tags:['time'], memo:'DO-po. A dopo = see you later.',
     parts:[{t:'dopo', m:'after'}]},
    {id:'time-prima', term:'prima', en:'before / first', tags:['time'], memo:'prime, primary. Prima di mangiare = before eating.',
     parts:[{t:'prima', m:'before, first'}]},
    {id:'time-sempre', term:'sempre', en:'always', tags:['time'], memo:'sempre as in music: always. Per sempre = forever.',
     parts:[{t:'sempre', m:'always'}]},
    {id:'time-mai', term:'mai', en:'never', tags:['time'], memo:'Used with non: Non vado mai = I never go. Mai più = never again.',
     parts:[{t:'mai', m:'never, ever'}]},
    {id:'time-subito', term:'subito', en:'right away', tags:['time'], memo:'SU-bi-to, stress on the first syllable. What a waiter says when he means ten minutes.',
     parts:[{t:'subito', m:'immediately'}]},
    {id:'time-mattina', term:'la mattina', en:'the morning', tags:['time'], memo:'matins, the morning prayer. Di mattina = in the morning.',
     parts:[{t:'la', m:'the'},{t:'mattina', m:'morning'}]},
    {id:'time-sera', term:'la sera', en:'the evening', tags:['time'], memo:'From buonasera. Stasera = tonight (questa sera).',
     parts:[{t:'la', m:'the'},{t:'sera', m:'evening'}], ex:{term:'Stasera mangiamo fuori.', en:'Tonight we eat out.'}},
    {id:'time-settimana', term:'la settimana', en:'the week', tags:['time'], memo:'sette = seven: the seven-day. Fine settimana = weekend (fine = end).',
     parts:[{t:'la', m:'the'},{t:'settimana', m:'week'}]},
    {id:'time-minuto', term:'un minuto', en:'a minute', tags:['time'], memo:'Un momento and un attimo (an instant) do the same job.',
     parts:[{t:'un', m:'a'},{t:'minuto', m:'minute'}]},
    {id:'time-a-che-ora', term:'A che ora?', en:'At what time?', tags:['time','questions'], memo:'a = at, che = what, ora = hour. A che ora apre? = what time does it open?',
     parts:[{t:'A', m:'at'},{t:'che', m:'what'},{t:'ora', m:'hour'}]},

    /* ---------------- PLACES AND GETTING AROUND ---------------- */
    {id:'place-dove-bagno', term:'Dov\'è il bagno?', en:'Where is the bathroom?', tags:['places','survival'], memo:'bagno = bath, bathroom (BAN-yo). Also: la toilette, i servizi.',
     parts:[{t:'Dov\'', m:'where'},{t:'è', m:'is'},{t:'il', m:'the'},{t:'bagno', m:'bathroom'}]},
    {id:'place-stazione', term:'la stazione', en:'the station', tags:['places'], memo:'station with a -zione ending: -tion is -zione in Italian (informazione, prenotazione).',
     parts:[{t:'la', m:'the'},{t:'stazione', m:'station'}]},
    {id:'place-aeroporto', term:'l\'aeroporto', en:'the airport', tags:['places'], memo:'a-e-ro-PORT-o: say every vowel.',
     parts:[{t:'l\'', m:'the'},{t:'aeroporto', m:'airport'}]},
    {id:'place-albergo', term:'l\'albergo', en:'the hotel', tags:['places'], memo:'Hotel works too, but albergo is the Italian word (from the same root as "harbour", a shelter).',
     parts:[{t:'l\'', m:'the'},{t:'albergo', m:'hotel'}]},
    {id:'place-farmacia', term:'la farmacia', en:'the pharmacy', tags:['places','survival'], memo:'pharmacy with an f, stress on -CI-a: far-ma-CHEE-a. Look for the green cross.',
     parts:[{t:'la', m:'the'},{t:'farmacia', m:'pharmacy'}]},
    {id:'place-supermercato', term:'il supermercato', en:'the supermarket', tags:['places','shopping'], memo:'mercato = market (merchant). Super + mercato.',
     parts:[{t:'il', m:'the'},{t:'super-', m:'super'},{t:'-mercato', m:'market'}]},
    {id:'place-piazza', term:'la piazza', en:'the square', tags:['places'], memo:'plaza, place. PYAT-tsa. Every town has one; meet there.',
     parts:[{t:'la', m:'the'},{t:'piazza', m:'square'}]},
    {id:'place-chiesa', term:'la chiesa', en:'the church', tags:['places'], memo:'KYEH-za. From Greek ekklesia (ecclesiastical).',
     parts:[{t:'la', m:'the'},{t:'chiesa', m:'church'}]},
    {id:'place-spiaggia', term:'la spiaggia', en:'the beach', tags:['places'], memo:'SPYAD-ja. Andiamo in spiaggia = let\'s go to the beach.',
     parts:[{t:'la', m:'the'},{t:'spiaggia', m:'beach'}]},
    {id:'place-casa', term:'a casa', en:'at home / home', tags:['places'], memo:'casa = house (casino was originally a little house). A casa = at home, to home.',
     parts:[{t:'a', m:'at, to'},{t:'casa', m:'home'}]},
    {id:'place-sinistra-destra', term:'a sinistra / a destra', en:'to the left / to the right', tags:['places','survival'], memo:'sinister = left (the unlucky side), dexterous = right-handed. Sempre dritto = straight ahead.',
     parts:[{t:'a sinistra', m:'to the left'},{t:'a destra', m:'to the right'}], ex:{term:'Sempre dritto, poi a destra.', en:'Straight ahead, then right.'}},
    {id:'place-vicino-lontano', term:'vicino / lontano', en:'near / far', tags:['places'], memo:'vicinity = near; lontano like "long way". È lontano? = is it far?',
     parts:[{t:'vicino', m:'near'},{t:'lontano', m:'far'}]},
    {id:'place-biglietto', term:'un biglietto', en:'a ticket', tags:['places','survival'], memo:'bil-YET-to, like French billet. Un biglietto per Firenze, per favore. Validate it before boarding.',
     parts:[{t:'un', m:'a'},{t:'biglietto', m:'ticket'}], ex:{term:'Un biglietto per Firenze, per favore.', en:'A ticket to Florence, please.'}},
    {id:'place-binario', term:'il binario', en:'the platform', tags:['places'], memo:'bi-nario = the two rails. Da quale binario? = from which platform?',
     parts:[{t:'il', m:'the'},{t:'binario', m:'platform, track'}]},

    /* ---------------- FEELINGS ---------------- */
    {id:'feel-sono-stanco', term:'Sono stanco', en:'I\'m tired', tags:['feelings'], memo:'stanco: think "stagnant". -a for a woman: stanca.',
     parts:[{t:'Sono', m:'I am'},{t:'stanco', m:'tired'}]},
    {id:'feel-sono-contento', term:'Sono contento', en:'I\'m happy / glad', tags:['feelings'], memo:'content. Felice = happy in a bigger sense.',
     parts:[{t:'Sono', m:'I am'},{t:'contento', m:'glad'}]},
    {id:'feel-ho-caldo', term:'Ho caldo / Ho freddo', en:'I\'m hot / I\'m cold', tags:['feelings'], memo:'"I have heat / cold". caldo looks like cold but means hot (scald). freddo = frigid.',
     parts:[{t:'Ho', m:'I have'},{t:'caldo', m:'heat'},{t:'freddo', m:'cold'}]},
    {id:'feel-ho-sonno', term:'Ho sonno', en:'I\'m sleepy', tags:['feelings'], memo:'"I have sleep". sonno = sleep (somnolent).',
     parts:[{t:'Ho', m:'I have'},{t:'sonno', m:'sleepiness'}]},
    {id:'feel-che-bello', term:'Che bello!', en:'How lovely!', tags:['feelings'], memo:'che + adjective = how …! Che buono (food), che bella (feminine thing), che peccato (what a pity).',
     parts:[{t:'Che', m:'what, how'},{t:'bello', m:'beautiful'}]},
    {id:'feel-mi-dispiace-tanto', term:'Che peccato', en:'What a pity', tags:['feelings'], memo:'peccato = sin (peccadillo). "What a sin!"',
     parts:[{t:'Che', m:'what a'},{t:'peccato', m:'sin, pity'}]},
    {id:'feel-magari', term:'Magari!', en:'If only! / I wish!', tags:['feelings'], memo:'From Greek makari (blessed). The hopeful "maybe": Vieni? Magari! = are you coming? I wish!',
     parts:[{t:'Magari', m:'if only, maybe'}]},
    {id:'feel-boh', term:'Boh', en:'Dunno', tags:['feelings','basics'], memo:'The shrug, as a word. Not for formal settings.',
     parts:[{t:'Boh', m:'no idea'}]},

    /* ---------------- SURVIVAL ---------------- */
    {id:'surv-aiuto', term:'Aiuto!', en:'Help!', tags:['survival'], memo:'a-YOO-to. aiutare = to help (aid).',
     parts:[{t:'Aiuto', m:'help'}]},
    {id:'surv-mi-sono-perso', term:'Mi sono perso', en:'I\'m lost', tags:['survival'], memo:'"I have lost myself". -a for a woman: persa.',
     parts:[{t:'Mi', m:'myself'},{t:'sono', m:'I am (have)'},{t:'perso', m:'lost'}]},
    {id:'surv-sto-male', term:'Sto male', en:'I feel ill', tags:['survival'], memo:'sto = I am (stare), male = badly (malady). Sto bene = I\'m well.',
     parts:[{t:'Sto', m:'I am (state)'},{t:'male', m:'badly'}]},
    {id:'surv-medico', term:'Ho bisogno di un medico', en:'I need a doctor', tags:['survival'], memo:'"I have need of". ho bisogno di = I need (anything). medico = doctor (medic).',
     parts:[{t:'Ho', m:'I have'},{t:'bisogno', m:'need'},{t:'di', m:'of'},{t:'un medico', m:'a doctor'}]},
    {id:'surv-polizia', term:'Chiami la polizia', en:'Call the police', tags:['survival'], memo:'chiamare = to call. 112 is the emergency number.',
     parts:[{t:'Chiami', m:'call (formal)'},{t:'la polizia', m:'the police'}]},
    {id:'surv-ho-perso', term:'Ho perso il passaporto', en:'I\'ve lost my passport', tags:['survival'], memo:'ho perso = I have lost. il portafoglio = wallet, il telefono = phone.',
     parts:[{t:'Ho perso', m:'I have lost'},{t:'il', m:'the (my)'},{t:'passaporto', m:'passport'}]},
    {id:'surv-attenzione', term:'Attenzione!', en:'Watch out!', tags:['survival'], memo:'attention, with -zione. On signs and from anyone about to collide with you.',
     parts:[{t:'Attenzione', m:'attention, careful'}]},

    /* ---------------- CONNECTORS ---------------- */
    {id:'con-e', term:'e', en:'and', tags:['connectors'], memo:'No accent = and. With the accent, è = is.',
     parts:[{t:'e', m:'and'}]},
    {id:'con-ma', term:'ma', en:'but', tags:['connectors'], memo:'Short and blunt. Sì, ma… = yes, but…',
     parts:[{t:'ma', m:'but'}]},
    {id:'con-o', term:'o', en:'or', tags:['connectors'], memo:'Just o. Caffè o tè? = coffee or tea?',
     parts:[{t:'o', m:'or'}]},
    {id:'con-perche', term:'perché', en:'because', tags:['connectors'], memo:'Same word as "why". Non vengo perché sono stanco.',
     parts:[{t:'perché', m:'because'}]},
    {id:'con-poi', term:'poi', en:'then / afterwards', tags:['connectors'], memo:'POY. Prima… poi… = first… then…',
     parts:[{t:'poi', m:'then'}]},
    {id:'con-quindi', term:'quindi', en:'so / therefore', tags:['connectors'], memo:'KWIN-dee. The logical "so"; allora is the conversational one.',
     parts:[{t:'quindi', m:'therefore'}]},
    {id:'con-pero', term:'però', en:'however / though', tags:['connectors'], memo:'Stress the ò. A softer, often sentence-final "but": È caro, però.',
     parts:[{t:'però', m:'however'}]},
    {id:'con-molto', term:'molto', en:'very / a lot', tags:['connectors','basics'], memo:'multi-. Molto bene, molto buono, grazie molto.',
     parts:[{t:'molto', m:'very, much'}]},
    {id:'con-un-po', term:'un po\'', en:'a little', tags:['connectors','basics'], memo:'Short for un poco (paucity). Parlo un po\' di italiano.',
     parts:[{t:'un', m:'a'},{t:'po\'', m:'bit'}], ex:{term:'Parlo un po\' di italiano.', en:'I speak a little Italian.'}},
    {id:'con-troppo', term:'troppo', en:'too much', tags:['connectors','basics'], memo:'French trop. Troppo caro, troppo caldo. Also slang for "really": troppo bello.',
     parts:[{t:'troppo', m:'too, too much'}]},
  ],
};
