/* japanese.js — the Conversational Japanese deck for /anki.
 *
 * Registered in anki/decks/index.js. Read the header of greek.js for the editing
 * rules: append only, never rename or reuse an id, bump version and updated,
 * run `node anki/deck.test.js` before committing.
 *
 * TRANSLITERATION: Hepburn romaji. Long vowels with macrons (ō ū ē), "n" before
 * a vowel written n' (e.g. kin'en). Particles as said: は→wa, を→o, へ→e.
 * Fields: id, term (Japanese script), tr (romaji), en, tags, note?, ex?{term,tr,en}
 */
window.DECKS = window.DECKS || {};
window.DECKS.japanese = {
  id: 'japanese',
  name: 'Conversational Japanese',
  version: 1,
  updated: '2026-10-01',

  notes: [
    /* ---------------- GREETINGS ---------------- */
    {id:'greet-ohayou', term:'おはようございます', tr:'ohayō gozaimasu', en:'Good morning', tags:['greetings'],
     note:'With friends drop ございます: おはよう (ohayō).'},
    {id:'greet-konnichiwa', term:'こんにちは', tr:'konnichiwa', en:'Hello / Good afternoon', tags:['greetings'],
     note:'Written with は but said "wa".'},
    {id:'greet-konbanwa', term:'こんばんは', tr:'konbanwa', en:'Good evening', tags:['greetings']},
    {id:'greet-oyasumi', term:'おやすみなさい', tr:'oyasumi nasai', en:'Good night', tags:['greetings'],
     note:'Casual: おやすみ (oyasumi).'},
    {id:'greet-sayounara', term:'さようなら', tr:'sayōnara', en:'Goodbye', tags:['greetings'],
     note:'Sounds final. Friends say じゃあね or またね.'},
    {id:'greet-jaa-ne', term:'じゃあね', tr:'jā ne', en:'See you (casual)', tags:['greetings']},
    {id:'greet-mata-ne', term:'またね', tr:'mata ne', en:'See you later', tags:['greetings'],
     ex:{term:'また明日。', tr:'mata ashita.', en:'See you tomorrow.'}},
    {id:'greet-ogenki', term:'お元気ですか', tr:'o-genki desu ka', en:'How are you?', tags:['greetings'],
     note:'Less routine than in English. Used after a while apart.'},
    {id:'greet-genki-desu', term:'元気です', tr:'genki desu', en:'I\'m fine', tags:['greetings']},
    {id:'greet-hajimemashite', term:'はじめまして', tr:'hajimemashite', en:'Nice to meet you (first meeting)', tags:['greetings'],
     ex:{term:'はじめまして、サムです。', tr:'hajimemashite, Samu desu.', en:'Nice to meet you, I\'m Sam.'}},
    {id:'greet-yoroshiku', term:'よろしくお願いします', tr:'yoroshiku onegai shimasu', en:'Please treat me well', tags:['greetings','politeness'],
     note:'No English equivalent. Closes an introduction or a request.'},
    {id:'greet-ittekimasu', term:'いってきます', tr:'ittekimasu', en:'I\'m off (leaving home)', tags:['greetings'],
     note:'Reply: いってらっしゃい (itterasshai).'},
    {id:'greet-tadaima', term:'ただいま', tr:'tadaima', en:'I\'m home', tags:['greetings'],
     note:'Reply: おかえり (okaeri).'},

    /* ---------------- POLITENESS ---------------- */
    {id:'pol-arigatou', term:'ありがとうございます', tr:'arigatō gozaimasu', en:'Thank you', tags:['politeness'],
     ex:{term:'どうもありがとうございます。', tr:'dōmo arigatō gozaimasu.', en:'Thank you very much.'}},
    {id:'pol-dou-itashimashite', term:'どういたしまして', tr:'dō itashimashite', en:'You\'re welcome', tags:['politeness']},
    {id:'pol-sumimasen', term:'すみません', tr:'sumimasen', en:'Excuse me / Sorry', tags:['politeness'],
     note:'The all-purpose word: get attention, apologise, or thank someone for their trouble.'},
    {id:'pol-gomen', term:'ごめんなさい', tr:'gomen nasai', en:'I\'m sorry', tags:['politeness'],
     note:'Casual: ごめん (gomen).'},
    {id:'pol-onegai', term:'お願いします', tr:'onegai shimasu', en:'Please (requesting)', tags:['politeness'],
     ex:{term:'水をお願いします。', tr:'mizu o onegai shimasu.', en:'Water, please.'}},
    {id:'pol-kudasai', term:'ください', tr:'kudasai', en:'Please give me', tags:['politeness'],
     ex:{term:'これをください。', tr:'kore o kudasai.', en:'This one, please.'}},
    {id:'pol-itadakimasu', term:'いただきます', tr:'itadakimasu', en:'Said before eating', tags:['politeness','food'],
     note:'Literally "I humbly receive".'},
    {id:'pol-gochisousama', term:'ごちそうさまでした', tr:'gochisōsama deshita', en:'Said after eating', tags:['politeness','food'],
     note:'Thanks for the meal, to the cook or the restaurant.'},
    {id:'pol-shitsurei', term:'失礼します', tr:'shitsurei shimasu', en:'Excuse me (entering or leaving)', tags:['politeness']},
    {id:'pol-kanpai', term:'乾杯', tr:'kanpai', en:'Cheers', tags:['politeness','food']},

    /* ---------------- BASICS ---------------- */
    {id:'bas-hai', term:'はい', tr:'hai', en:'Yes', tags:['basics'],
     note:'Also "I\'m listening". Not always agreement.'},
    {id:'bas-iie', term:'いいえ', tr:'iie', en:'No', tags:['basics'],
     note:'Softer refusals are common: ちょっと… (chotto...).'},
    {id:'bas-daijoubu', term:'大丈夫です', tr:'daijōbu desu', en:'It\'s OK / I\'m fine', tags:['basics'],
     note:'Also "no thanks", with a small hand wave.'},
    {id:'bas-wakarimashita', term:'わかりました', tr:'wakarimashita', en:'Understood / Got it', tags:['basics']},
    {id:'bas-wakarimasen', term:'わかりません', tr:'wakarimasen', en:'I don\'t understand / I don\'t know', tags:['basics','survival']},
    {id:'bas-ii-desu-ne', term:'いいですね', tr:'ii desu ne', en:'That\'s nice', tags:['basics']},
    {id:'bas-sugoi', term:'すごい', tr:'sugoi', en:'Amazing / Wow', tags:['basics']},
    {id:'bas-chotto', term:'ちょっと', tr:'chotto', en:'A little / A bit', tags:['basics'],
     note:'Also a soft no: ちょっと… (chotto...)',
     ex:{term:'ちょっと待ってください。', tr:'chotto matte kudasai.', en:'Please wait a moment.'}},
    {id:'bas-totemo', term:'とても', tr:'totemo', en:'Very', tags:['basics']},
    {id:'bas-tabun', term:'たぶん', tr:'tabun', en:'Maybe / Probably', tags:['basics']},
    {id:'bas-mochiron', term:'もちろん', tr:'mochiron', en:'Of course', tags:['basics']},

    /* ---------------- NUMBERS ---------------- */
    {id:'num-ichi', term:'一', tr:'ichi', en:'One', tags:['numbers'],
     note:'Counting: いち、に、さん、よん、ご、ろく、なな、はち、きゅう、じゅう.'},
    {id:'num-ni', term:'二', tr:'ni', en:'Two', tags:['numbers']},
    {id:'num-san', term:'三', tr:'san', en:'Three', tags:['numbers']},
    {id:'num-yon', term:'四', tr:'yon', en:'Four', tags:['numbers'],
     note:'Also し (shi), avoided because it sounds like "death".'},
    {id:'num-go', term:'五', tr:'go', en:'Five', tags:['numbers']},
    {id:'num-roku', term:'六', tr:'roku', en:'Six', tags:['numbers']},
    {id:'num-nana', term:'七', tr:'nana', en:'Seven', tags:['numbers'],
     note:'Also しち (shichi).'},
    {id:'num-hachi', term:'八', tr:'hachi', en:'Eight', tags:['numbers']},
    {id:'num-kyuu', term:'九', tr:'kyū', en:'Nine', tags:['numbers'],
     note:'Also く (ku).'},
    {id:'num-juu', term:'十', tr:'jū', en:'Ten', tags:['numbers']},
    {id:'num-hyaku', term:'百', tr:'hyaku', en:'One hundred', tags:['numbers']},
    {id:'num-sen', term:'千', tr:'sen', en:'One thousand', tags:['numbers'],
     ex:{term:'千円', tr:'sen en', en:'1,000 yen'}},
    {id:'num-hitotsu', term:'ひとつ', tr:'hitotsu', en:'One (thing)', tags:['numbers','food'],
     note:'The general counter: ひとつ、ふたつ、みっつ. Use it when ordering.',
     ex:{term:'ビールをふたつ。', tr:'bīru o futatsu.', en:'Two beers.'}},

    /* ---------------- QUESTION WORDS ---------------- */
    {id:'q-nani', term:'何', tr:'nani', en:'What?', tags:['questions'],
     note:'Becomes なん (nan) before です.',
     ex:{term:'これは何ですか。', tr:'kore wa nan desu ka.', en:'What is this?'}},
    {id:'q-doko', term:'どこ', tr:'doko', en:'Where?', tags:['questions'],
     ex:{term:'トイレはどこですか。', tr:'toire wa doko desu ka.', en:'Where is the toilet?'}},
    {id:'q-itsu', term:'いつ', tr:'itsu', en:'When?', tags:['questions']},
    {id:'q-doushite', term:'どうして', tr:'dōshite', en:'Why?', tags:['questions'],
     note:'なぜ (naze) is the same, a bit more formal.'},
    {id:'q-dou', term:'どう', tr:'dō', en:'How?', tags:['questions'],
     ex:{term:'どうですか。', tr:'dō desu ka.', en:'How is it?'}},
    {id:'q-dare', term:'誰', tr:'dare', en:'Who?', tags:['questions']},
    {id:'q-ikura', term:'いくら', tr:'ikura', en:'How much?', tags:['questions','shopping'],
     ex:{term:'いくらですか。', tr:'ikura desu ka.', en:'How much is it?'}},
    {id:'q-dore', term:'どれ', tr:'dore', en:'Which one?', tags:['questions']},
    {id:'q-ka', term:'か', tr:'ka', en:'(question marker)', tags:['questions'],
     note:'Ends a sentence to make it a question. No rising tone needed.',
     ex:{term:'日本人ですか。', tr:'nihonjin desu ka.', en:'Are you Japanese?'}},

    /* ---------------- PRONOUNS ---------------- */
    {id:'pro-watashi', term:'私', tr:'watashi', en:'I', tags:['pronouns'],
     note:'Usually dropped. Men also say 僕 (boku) casually.'},
    {id:'pro-anata', term:'あなた', tr:'anata', en:'You', tags:['pronouns'],
     note:'Avoid with people you know. Use their name + さん instead.'},
    {id:'pro-kare', term:'彼', tr:'kare', en:'He', tags:['pronouns'],
     note:'Also "boyfriend".'},
    {id:'pro-kanojo', term:'彼女', tr:'kanojo', en:'She', tags:['pronouns'],
     note:'Also "girlfriend".'},
    {id:'pro-watashitachi', term:'私たち', tr:'watashitachi', en:'We', tags:['pronouns']},
    {id:'pro-kore', term:'これ', tr:'kore', en:'This (near me)', tags:['pronouns']},
    {id:'pro-sore', term:'それ', tr:'sore', en:'That (near you)', tags:['pronouns']},
    {id:'pro-are', term:'あれ', tr:'are', en:'That (over there)', tags:['pronouns']},
    {id:'pro-no', term:'の', tr:'no', en:'\'s (possession)', tags:['pronouns'],
     ex:{term:'私の名前', tr:'watashi no namae', en:'My name'}},
    {id:'pro-san', term:'さん', tr:'san', en:'Mr / Ms (after a name)', tags:['pronouns','politeness'],
     note:'Never put it on your own name.'},

    /* ---------------- TIME ---------------- */
    {id:'time-kyou', term:'今日', tr:'kyō', en:'Today', tags:['time']},
    {id:'time-ashita', term:'明日', tr:'ashita', en:'Tomorrow', tags:['time']},
    {id:'time-kinou', term:'昨日', tr:'kinō', en:'Yesterday', tags:['time']},
    {id:'time-ima', term:'今', tr:'ima', en:'Now', tags:['time']},
    {id:'time-ato-de', term:'後で', tr:'ato de', en:'Later', tags:['time'],
     ex:{term:'また後で。', tr:'mata ato de.', en:'See you later.'}},
    {id:'time-nanji', term:'何時ですか', tr:'nanji desu ka', en:'What time is it?', tags:['time','questions']},
    {id:'time-asa', term:'朝', tr:'asa', en:'Morning', tags:['time']},
    {id:'time-yoru', term:'夜', tr:'yoru', en:'Night / Evening', tags:['time']},
    {id:'time-getsuyoubi', term:'月曜日', tr:'getsuyōbi', en:'Monday', tags:['time'],
     note:'Days: 月火水木金土日 + 曜日 (yōbi).'},
    {id:'time-kinyoubi', term:'金曜日', tr:'kin\'yōbi', en:'Friday', tags:['time']},
    {id:'time-doyoubi', term:'土曜日', tr:'doyōbi', en:'Saturday', tags:['time']},
    {id:'time-nichiyoubi', term:'日曜日', tr:'nichiyōbi', en:'Sunday', tags:['time']},
    {id:'time-shuumatsu', term:'週末', tr:'shūmatsu', en:'Weekend', tags:['time']},

    /* ---------------- FOOD & ORDERING ---------------- */
    {id:'food-mizu', term:'水', tr:'mizu', en:'Water', tags:['food'],
     ex:{term:'お水をください。', tr:'o-mizu o kudasai.', en:'Water, please.'}},
    {id:'food-ocha', term:'お茶', tr:'ocha', en:'Tea (green)', tags:['food']},
    {id:'food-koohii', term:'コーヒー', tr:'kōhī', en:'Coffee', tags:['food']},
    {id:'food-biiru', term:'ビール', tr:'bīru', en:'Beer', tags:['food'],
     ex:{term:'ビールをふたつください。', tr:'bīru o futatsu kudasai.', en:'Two beers, please.'}},
    {id:'food-gohan', term:'ご飯', tr:'gohan', en:'Rice / A meal', tags:['food']},
    {id:'food-oishii', term:'おいしい', tr:'oishii', en:'Delicious', tags:['food'],
     ex:{term:'とてもおいしいです。', tr:'totemo oishii desu.', en:'It\'s very tasty.'}},
    {id:'food-okaikei', term:'お会計をお願いします', tr:'o-kaikei o onegai shimasu', en:'The bill, please', tags:['food'],
     note:'Crossing your index fingers in an X also asks for the bill.'},
    {id:'food-menyuu', term:'メニューをください', tr:'menyū o kudasai', en:'The menu, please', tags:['food']},
    {id:'food-osusume', term:'おすすめは何ですか', tr:'osusume wa nan desu ka', en:'What do you recommend?', tags:['food']},
    {id:'food-onaka-suita', term:'お腹が空きました', tr:'onaka ga sukimashita', en:'I\'m hungry', tags:['food','feelings'],
     note:'Casual: お腹すいた (onaka suita).'},
    {id:'food-nodo-kawaita', term:'喉が渇きました', tr:'nodo ga kawakimashita', en:'I\'m thirsty', tags:['food','feelings']},
    {id:'food-nuki', term:'抜きで', tr:'nuki de', en:'Without', tags:['food'],
     ex:{term:'砂糖抜きで。', tr:'satō nuki de.', en:'Without sugar.'}},
    {id:'food-futari', term:'二人です', tr:'futari desu', en:'Table for two', tags:['food'],
     note:'Said at the door. One person: 一人 (hitori).'},
    {id:'food-mochikaeri', term:'持ち帰り', tr:'mochikaeri', en:'Takeaway', tags:['food'],
     note:'Eat in: 店内で (tennai de).'},

    /* ---------------- PLACES & DIRECTIONS ---------------- */
    {id:'place-wa-doko', term:'〜はどこですか', tr:'... wa doko desu ka', en:'Where is ...?', tags:['places','questions'],
     ex:{term:'駅はどこですか。', tr:'eki wa doko desu ka.', en:'Where is the station?'}},
    {id:'place-hidari', term:'左', tr:'hidari', en:'Left', tags:['places']},
    {id:'place-migi', term:'右', tr:'migi', en:'Right', tags:['places']},
    {id:'place-massugu', term:'まっすぐ', tr:'massugu', en:'Straight ahead', tags:['places']},
    {id:'place-koko', term:'ここ', tr:'koko', en:'Here', tags:['places']},
    {id:'place-asoko', term:'あそこ', tr:'asoko', en:'Over there', tags:['places']},
    {id:'place-chikai', term:'近い', tr:'chikai', en:'Near', tags:['places']},
    {id:'place-tooi', term:'遠い', tr:'tōi', en:'Far', tags:['places']},
    {id:'place-eki', term:'駅', tr:'eki', en:'Station', tags:['places']},
    {id:'place-toire', term:'トイレ', tr:'toire', en:'Toilet', tags:['places'],
     note:'Politer: お手洗い (o-tearai).'},
    {id:'place-kuukou', term:'空港', tr:'kūkō', en:'Airport', tags:['places']},
    {id:'place-konbini', term:'コンビニ', tr:'konbini', en:'Convenience store', tags:['places']},

    /* ---------------- SHOPPING & MONEY ---------------- */
    {id:'shop-ikura', term:'いくらですか', tr:'ikura desu ka', en:'How much is it?', tags:['shopping']},
    {id:'shop-takai', term:'高い', tr:'takai', en:'Expensive', tags:['shopping'],
     note:'Also "tall".'},
    {id:'shop-yasui', term:'安い', tr:'yasui', en:'Cheap', tags:['shopping']},
    {id:'shop-kaado', term:'カードは使えますか', tr:'kādo wa tsukaemasu ka', en:'Can I pay by card?', tags:['shopping']},
    {id:'shop-genkin', term:'現金', tr:'genkin', en:'Cash', tags:['shopping']},
    {id:'shop-okane', term:'お金', tr:'okane', en:'Money', tags:['shopping']},
    {id:'shop-en', term:'円', tr:'en', en:'Yen', tags:['shopping']},
    {id:'shop-kore-kudasai', term:'これをください', tr:'kore o kudasai', en:'I\'ll take this one', tags:['shopping']},
    {id:'shop-miteru-dake', term:'見ているだけです', tr:'mite iru dake desu', en:'Just looking', tags:['shopping']},
    {id:'shop-fukuro', term:'袋', tr:'fukuro', en:'Bag', tags:['shopping'],
     note:'At the till: 袋はいりますか (need a bag?). Say 大丈夫です for no.'},

    /* ---------------- FEELINGS & SMALL TALK ---------------- */
    {id:'feel-ureshii', term:'嬉しい', tr:'ureshii', en:'Happy / Glad', tags:['feelings']},
    {id:'feel-tsukareta', term:'疲れました', tr:'tsukaremashita', en:'I\'m tired', tags:['feelings']},
    {id:'feel-atsui', term:'暑いですね', tr:'atsui desu ne', en:'It\'s hot, isn\'t it', tags:['feelings','time'],
     note:'ね (ne) invites agreement. Small talk starts here.'},
    {id:'feel-samui', term:'寒いですね', tr:'samui desu ne', en:'It\'s cold, isn\'t it', tags:['feelings','time']},
    {id:'feel-suki', term:'好きです', tr:'suki desu', en:'I like it', tags:['feelings','verbs'],
     ex:{term:'日本が好きです。', tr:'nihon ga suki desu.', en:'I like Japan.'}},
    {id:'feel-kirai', term:'嫌いです', tr:'kirai desu', en:'I dislike it', tags:['feelings','verbs'],
     note:'Strong. Softer: あまり好きじゃないです (amari suki ja nai desu).'},
    {id:'feel-tanoshii', term:'楽しい', tr:'tanoshii', en:'Fun', tags:['feelings']},
    {id:'feel-ganbatte', term:'頑張って', tr:'ganbatte', en:'Good luck / Do your best', tags:['feelings']},
    {id:'feel-otsukare', term:'お疲れ様です', tr:'otsukaresama desu', en:'Thanks for your hard work', tags:['feelings','politeness'],
     note:'Said constantly at work and when parting with colleagues.'},

    /* ---------------- VERBS (polite present) ---------------- */
    {id:'verb-tabemasu', term:'食べます', tr:'tabemasu', en:'I eat', tags:['verbs'],
     note:'Polite present. The same form works for every person.'},
    {id:'verb-nomimasu', term:'飲みます', tr:'nomimasu', en:'I drink', tags:['verbs']},
    {id:'verb-ikimasu', term:'行きます', tr:'ikimasu', en:'I go', tags:['verbs'],
     ex:{term:'東京に行きます。', tr:'tōkyō ni ikimasu.', en:'I\'m going to Tokyo.'}},
    {id:'verb-kimasu', term:'来ます', tr:'kimasu', en:'I come', tags:['verbs']},
    {id:'verb-mimasu', term:'見ます', tr:'mimasu', en:'I see / I watch', tags:['verbs']},
    {id:'verb-hanashimasu', term:'話します', tr:'hanashimasu', en:'I speak', tags:['verbs'],
     ex:{term:'日本語を少し話します。', tr:'nihongo o sukoshi hanashimasu.', en:'I speak a little Japanese.'}},
    {id:'verb-wakarimasu', term:'わかります', tr:'wakarimasu', en:'I understand', tags:['verbs']},
    {id:'verb-shitte-imasu', term:'知っています', tr:'shitte imasu', en:'I know', tags:['verbs']},
    {id:'verb-arimasu', term:'あります', tr:'arimasu', en:'There is (things) / I have', tags:['verbs'],
     ex:{term:'時間がありますか。', tr:'jikan ga arimasu ka.', en:'Do you have time?'}},
    {id:'verb-imasu', term:'います', tr:'imasu', en:'There is (people, animals)', tags:['verbs']},
    {id:'verb-dekimasu', term:'できます', tr:'dekimasu', en:'I can / It\'s possible', tags:['verbs']},
    {id:'verb-hoshii', term:'欲しいです', tr:'hoshii desu', en:'I want (a thing)', tags:['verbs'],
     ex:{term:'水が欲しいです。', tr:'mizu ga hoshii desu.', en:'I want water.'}},
    {id:'verb-tai', term:'〜たいです', tr:'...tai desu', en:'I want to (do)', tags:['verbs'],
     ex:{term:'食べたいです。', tr:'tabetai desu.', en:'I want to eat.'}},
    {id:'verb-masen', term:'〜ません', tr:'...masen', en:'(negative) don\'t', tags:['verbs'],
     ex:{term:'食べません。', tr:'tabemasen.', en:'I don\'t eat.'}},
    {id:'verb-mashita', term:'〜ました', tr:'...mashita', en:'(past) did', tags:['verbs'],
     ex:{term:'食べました。', tr:'tabemashita.', en:'I ate.'}},
    {id:'verb-desu', term:'です', tr:'desu', en:'is / am / are', tags:['verbs'],
     ex:{term:'サムです。', tr:'Samu desu.', en:'I\'m Sam.'}},

    /* ---------------- SURVIVAL ---------------- */
    {id:'surv-eigo', term:'英語を話せますか', tr:'eigo o hanasemasu ka', en:'Do you speak English?', tags:['survival']},
    {id:'surv-nihongo-dekimasen', term:'日本語ができません', tr:'nihongo ga dekimasen', en:'I can\'t speak Japanese', tags:['survival']},
    {id:'surv-yukkuri', term:'ゆっくり話してください', tr:'yukkuri hanashite kudasai', en:'Please speak slowly', tags:['survival']},
    {id:'surv-mou-ichido', term:'もう一度お願いします', tr:'mō ichido onegai shimasu', en:'Once more, please', tags:['survival']},
    {id:'surv-nihongo-de', term:'日本語で何と言いますか', tr:'nihongo de nan to iimasu ka', en:'How do you say it in Japanese?', tags:['survival']},
    {id:'surv-dou-iu-imi', term:'どういう意味ですか', tr:'dō iu imi desu ka', en:'What does it mean?', tags:['survival']},
    {id:'surv-tasukete', term:'助けて', tr:'tasukete', en:'Help!', tags:['survival']},
    {id:'surv-daijoubu-desu-ka', term:'大丈夫ですか', tr:'daijōbu desu ka', en:'Are you OK?', tags:['survival']},
    {id:'surv-michi-ni-mayoimashita', term:'道に迷いました', tr:'michi ni mayoimashita', en:'I\'m lost', tags:['survival']},

    /* ---------------- CONNECTORS ---------------- */
    {id:'con-to', term:'と', tr:'to', en:'And (between nouns)', tags:['connectors'],
     ex:{term:'パンと水', tr:'pan to mizu', en:'Bread and water'}},
    {id:'con-soshite', term:'そして', tr:'soshite', en:'And then', tags:['connectors']},
    {id:'con-demo', term:'でも', tr:'demo', en:'But', tags:['connectors']},
    {id:'con-kara', term:'から', tr:'kara', en:'Because / From', tags:['connectors'],
     ex:{term:'高いから。', tr:'takai kara.', en:'Because it\'s expensive.'}},
    {id:'con-mo', term:'も', tr:'mo', en:'Also / Too', tags:['connectors'],
     ex:{term:'私も。', tr:'watashi mo.', en:'Me too.'}},
    {id:'con-ka-or', term:'か (または)', tr:'ka (mata wa)', en:'Or', tags:['connectors'],
     ex:{term:'お茶かコーヒー', tr:'ocha ka kōhī', en:'Tea or coffee'}},
    {id:'con-jaa', term:'じゃあ', tr:'jā', en:'Well then', tags:['connectors']},
    {id:'con-moshi', term:'もし', tr:'moshi', en:'If', tags:['connectors']},
    {id:'con-eeto', term:'えーと', tr:'ēto', en:'Um...', tags:['connectors'],
     note:'The filler while you think. Also あの (ano).'},
  ],
};
