/* japanese.js — the Conversational Japanese deck for /anki.
 *
 * Registered in anki/decks/index.js. Read the header of greek.js for the editing
 * rules: append only, never rename or reuse an id, bump version and updated,
 * run `node anki/deck.test.js` before committing.
 *
 * MEMOS FOR JAPANESE: lean on kanji meanings (今日 now-day), English loanwords in
 *   katakana, the particles (は wa topic, を o object, が ga subject, に ni to, で de by,
 *   の no 's, か ka ?), the -masu family (-masen not, -mashita did, -tai want to), desu,
 *   and the ko/so/a/do set. Parts split stem + ending and list every particle.
 *
 * TRANSLITERATION: Hepburn romaji. Long vowels with macrons (ō ū ē), "n" before
 * a vowel written n' (e.g. kin'en). Particles as said: は→wa, を→o, へ→e.
 * Fields: id, term (Japanese script), tr (romaji), en, tags, note?, ex?{term,tr,en}
 */
window.DECKS = window.DECKS || {};
window.DECKS.japanese = {
  id: 'japanese',
  name: 'Conversational Japanese',
  version: 2,
  updated: '2026-10-01',

  notes: [
    /* ---------------- GREETINGS ---------------- */
    {id:'greet-ohayou', term:'おはようございます', tr:'ohayō gozaimasu', en:'Good morning', memo:'ohayō sounds like \'Ohio\'. Say \'Ohio, gozaimasu\' in the morning. gozaimasu is the polite tail you add to be formal.',
     parts:[{t:'おはよう', tr:'ohayō', m:'early (honorific form of hayai)'}, {t:'ございます', tr:'gozaimasu', m:'polite \'is\''}],
     tags:['greetings'],
     note:'With friends drop ございます: おはよう (ohayō).'},
    {id:'greet-konnichiwa', term:'こんにちは', tr:'konnichiwa', en:'Hello / Good afternoon', memo:'konnichi = this day, wa = as for: \'as for today...\', the start of a greeting that was never finished.',
     parts:[{t:'今日', tr:'konnichi', m:'this day'}, {t:'は', tr:'wa', m:'topic marker (as for)'}],
     tags:['greetings'],
     note:'Written with は but said "wa".'},
    {id:'greet-konbanwa', term:'こんばんは', tr:'konbanwa', en:'Good evening', memo:'konban = this evening (ban = evening), wa = as for. Same shape as konnichiwa, swap day for evening.',
     parts:[{t:'今晩', tr:'konban', m:'this evening'}, {t:'は', tr:'wa', m:'topic marker'}],
     tags:['greetings']},
    {id:'greet-oyasumi', term:'おやすみなさい', tr:'oyasumi nasai', en:'Good night', memo:'o- = honorific, yasumi = rest (yasumu = to rest), nasai = please do. \'Please rest.\'',
     parts:[{t:'お', tr:'o', m:'honorific prefix'}, {t:'やすみ', tr:'yasumi', m:'rest'}, {t:'なさい', tr:'nasai', m:'please do (soft command)'}],
     tags:['greetings'],
     note:'Casual: おやすみ (oyasumi).'},
    {id:'greet-sayounara', term:'さようなら', tr:'sayōnara', en:'Goodbye', memo:'sayō = so, that way + nara = if: \'if that is so...\', the start of a farewell. Think \'so you\'re going? Alright\'.',
     parts:[{t:'さよう', tr:'sayō', m:'so, like that'}, {t:'なら', tr:'nara', m:'if, in that case'}],
     tags:['greetings'],
     note:'Sounds final. Friends say じゃあね or またね.'},
    {id:'greet-jaa-ne', term:'じゃあね', tr:'jā ne', en:'See you (casual)', memo:'jā = well then (from de wa), ne = right? \'Well then, yeah?\' The ne tag asks for agreement.',
     parts:[{t:'じゃあ', tr:'jā', m:'well then'}, {t:'ね', tr:'ne', m:'right? (agreement tag)'}],
     tags:['greetings']},
    {id:'greet-mata-ne', term:'またね', tr:'mata ne', en:'See you later', memo:'mata = again, ne = right? \'Again, yeah?\' = see you. mata ashita = again tomorrow.',
     parts:[{t:'また', tr:'mata', m:'again'}, {t:'ね', tr:'ne', m:'right?'}],
     tags:['greetings'],
     ex:{term:'また明日。', tr:'mata ashita.', en:'See you tomorrow.'}},
    {id:'greet-ogenki', term:'お元気ですか', tr:'o-genki desu ka', en:'How are you?', memo:'o- honorific + genki = energy, health (gen = origin, ki = spirit, as in \'ki\' energy). desu ka = is it? \'Is your spirit well?\'',
     parts:[{t:'お', tr:'o', m:'honorific'}, {t:'元気', tr:'genki', m:'health, energy (ki = spirit)'}, {t:'です', tr:'desu', m:'is'}, {t:'か', tr:'ka', m:'question marker'}],
     tags:['greetings'],
     note:'Less routine than in English. Used after a while apart.'},
    {id:'greet-genki-desu', term:'元気です', tr:'genki desu', en:'I\'m fine', memo:'genki = energetic, desu = am. Drop the o- when talking about yourself: honorifics are for others.',
     parts:[{t:'元気', tr:'genki', m:'well, energetic'}, {t:'です', tr:'desu', m:'am, is'}],
     tags:['greetings']},
    {id:'greet-hajimemashite', term:'はじめまして', tr:'hajimemashite', en:'Nice to meet you (first meeting)', memo:'hajime = beginning (hajimeru = to begin), -mashite = polite \'doing\'. \'For the first time\', nice to meet you.',
     parts:[{t:'はじめ', tr:'hajime', m:'beginning, first time'}, {t:'まして', tr:'mashite', m:'polite -ing (connective of -masu)'}],
     tags:['greetings'],
     ex:{term:'はじめまして、サムです。', tr:'hajimemashite, Samu desu.', en:'Nice to meet you, I\'m Sam.'}},
    {id:'greet-yoroshiku', term:'よろしくお願いします', tr:'yoroshiku onegai shimasu', en:'Please treat me well', memo:'yoroshii = good, fine; yoroshiku = \'in a good way\'; onegai shimasu = I request. \'Please deal with me well.\'',
     parts:[{t:'よろしく', tr:'yoroshiku', m:'well, favourably'}, {t:'お願い', tr:'onegai', m:'request, wish'}, {t:'します', tr:'shimasu', m:'I do (polite)'}],
     tags:['greetings','politeness'],
     note:'No English equivalent. Closes an introduction or a request.'},
    {id:'greet-ittekimasu', term:'いってきます', tr:'ittekimasu', en:'I\'m off (leaving home)', memo:'itte = going (iku = go) + kimasu = I come: \'I go and come (back)\'. The itterasshai reply = \'go and come back\'.',
     parts:[{t:'いって', tr:'itte', m:'go and... (from iku)'}, {t:'きます', tr:'kimasu', m:'I come (polite)'}],
     tags:['greetings'],
     note:'Reply: いってらっしゃい (itterasshai).'},
    {id:'greet-tadaima', term:'ただいま', tr:'tadaima', en:'I\'m home', memo:'tada = just, ima = now: \'just now\' (I returned). Say it the moment you walk in. Reply: okaeri, \'return\'.',
     parts:[{t:'ただ', tr:'tada', m:'just, only'}, {t:'いま', tr:'ima', m:'now'}],
     tags:['greetings'],
     note:'Reply: おかえり (okaeri).'},

    /* ---------------- POLITENESS ---------------- */
    {id:'pol-arigatou', term:'ありがとうございます', tr:'arigatō gozaimasu', en:'Thank you', memo:'arigatai = hard to exist, rare, so precious: \'this is rare\', thank you. gozaimasu makes it polite, as with ohayō.',
     parts:[{t:'ありがとう', tr:'arigatō', m:'thankful (from \'rare, precious\')'}, {t:'ございます', tr:'gozaimasu', m:'polite \'is\''}],
     tags:['politeness'],
     ex:{term:'どうもありがとうございます。', tr:'dōmo arigatō gozaimasu.', en:'Thank you very much.'}},
    {id:'pol-dou-itashimashite', term:'どういたしまして', tr:'dō itashimashite', en:'You\'re welcome', memo:'dō = how, itashimashite = humble \'did\': \'how could I have (done anything)?\' = don\'t mention it.',
     parts:[{t:'どう', tr:'dō', m:'how'}, {t:'いたしまして', tr:'itashimashite', m:'humbly doing (from itasu = do)'}],
     tags:['politeness']},
    {id:'pol-sumimasen', term:'すみません', tr:'sumimasen', en:'Excuse me / Sorry', memo:'sumu = to be settled; sumimasen = \'it is not settled\': my debt to you is unpaid. Apology and thanks in one. -masen = not.',
     parts:[{t:'すみ', tr:'sumi', m:'settle, finish (sumu)'}, {t:'ません', tr:'masen', m:'not (polite negative)'}],
     tags:['politeness'],
     note:'The all-purpose word: get attention, apologise, or thank someone for their trouble.'},
    {id:'pol-gomen', term:'ごめんなさい', tr:'gomen nasai', en:'I\'m sorry', memo:'go- honorific + men = pardon, exemption (as in menkyo, licence) + nasai = please: \'please pardon\'.',
     parts:[{t:'ご', tr:'go', m:'honorific prefix'}, {t:'めん', tr:'men', m:'pardon, exemption'}, {t:'なさい', tr:'nasai', m:'please do'}],
     tags:['politeness'],
     note:'Casual: ごめん (gomen).'},
    {id:'pol-onegai', term:'お願いします', tr:'onegai shimasu', en:'Please (requesting)', memo:'o- + negai = wish (negau = to wish) + shimasu = I do: \'I make a wish\', please. The polite request to a person.',
     parts:[{t:'お', tr:'o', m:'honorific'}, {t:'願い', tr:'negai', m:'wish, request'}, {t:'します', tr:'shimasu', m:'I do (polite)'}],
     tags:['politeness'],
     ex:{term:'水をお願いします。', tr:'mizu o onegai shimasu.', en:'Water, please.'}},
    {id:'pol-kudasai', term:'ください', tr:'kudasai', en:'Please give me', memo:'kudasaru = to give down (to me): kudasai = \'give me, please\'. Attach to a noun with o: mizu o kudasai.',
     parts:[{t:'ください', tr:'kudasai', m:'please give (me)'}],
     tags:['politeness'],
     ex:{term:'これをください。', tr:'kore o kudasai.', en:'This one, please.'}},
    {id:'pol-itadakimasu', term:'いただきます', tr:'itadakimasu', en:'Said before eating', memo:'itadaku = to receive humbly (literally \'to put on the head\'). -masu polite. \'I humbly receive\' before eating.',
     parts:[{t:'いただき', tr:'itadaki', m:'receive humbly'}, {t:'ます', tr:'masu', m:'polite present'}],
     tags:['politeness','food'],
     note:'Literally "I humbly receive".'},
    {id:'pol-gochisousama', term:'ごちそうさまでした', tr:'gochisōsama deshita', en:'Said after eating', memo:'go- + chisō = a feast (literally \'running around\' to prepare it) + sama = honoured, deshita = was. \'It was a feast.\'',
     parts:[{t:'ご', tr:'go', m:'honorific'}, {t:'ちそう', tr:'chisō', m:'feast, treat'}, {t:'さま', tr:'sama', m:'honoured (as in -sama)'}, {t:'でした', tr:'deshita', m:'was (polite past of desu)'}],
     tags:['politeness','food'],
     note:'Thanks for the meal, to the cook or the restaurant.'},
    {id:'pol-shitsurei', term:'失礼します', tr:'shitsurei shimasu', en:'Excuse me (entering or leaving)', memo:'shitsu = lose + rei = courtesy: \'I lose manners\'. shimasu = I do. Said when you intrude or leave: \'excuse my rudeness\'.',
     parts:[{t:'失', tr:'shitsu', m:'lose'}, {t:'礼', tr:'rei', m:'courtesy, manners'}, {t:'します', tr:'shimasu', m:'I do'}],
     tags:['politeness']},
    {id:'pol-kanpai', term:'乾杯', tr:'kanpai', en:'Cheers', memo:'kan = dry + pai = cup: \'dry the cup!\', bottoms up. Chinese ganbei is the same two characters.',
     parts:[{t:'乾', tr:'kan', m:'dry'}, {t:'杯', tr:'pai', m:'cup'}],
     tags:['politeness','food']},

    /* ---------------- BASICS ---------------- */
    {id:'bas-hai', term:'はい', tr:'hai', en:'Yes', memo:'hai = yes, also \'here\' and \'I\'m listening\'. Think \'hi, yes\'. One quick syllable, like English \'high\'.',
     parts:[{t:'はい', tr:'hai', m:'yes'}],
     tags:['basics'],
     note:'Also "I\'m listening". Not always agreement.'},
    {id:'bas-iie', term:'いいえ', tr:'iie', en:'No', memo:'iie = no, said ee-eh with a dip. Japanese prefers softer refusals, so iie is rarer than you expect.',
     parts:[{t:'いいえ', tr:'iie', m:'no'}],
     tags:['basics'],
     note:'Softer refusals are common: ちょっと… (chotto...).'},
    {id:'bas-daijoubu', term:'大丈夫です', tr:'daijōbu desu', en:'It\'s OK / I\'m fine', memo:'dai = big + jō = sturdy + bu = man: \'a big sturdy man\' = safe, fine. desu = is. \'It\'s all good.\'',
     parts:[{t:'大', tr:'dai', m:'big'}, {t:'丈夫', tr:'jōbu', m:'sturdy, robust'}, {t:'です', tr:'desu', m:'is'}],
     tags:['basics'],
     note:'Also "no thanks", with a small hand wave.'},
    {id:'bas-wakarimashita', term:'わかりました', tr:'wakarimashita', en:'Understood / Got it', memo:'wakaru = to understand + -mashita = polite past: \'I have understood\', got it.',
     parts:[{t:'わかり', tr:'wakari', m:'understand (wakaru)'}, {t:'ました', tr:'mashita', m:'did (polite past)'}],
     tags:['basics']},
    {id:'bas-wakarimasen', term:'わかりません', tr:'wakarimasen', en:'I don\'t understand / I don\'t know', memo:'wakaru + -masen = polite not: \'I do not understand\'. -masu yes, -masen no, -mashita did.',
     parts:[{t:'わかり', tr:'wakari', m:'understand'}, {t:'ません', tr:'masen', m:'not (polite negative)'}],
     tags:['basics','survival']},
    {id:'bas-ii-desu-ne', term:'いいですね', tr:'ii desu ne', en:'That\'s nice', memo:'ii = good, desu = is, ne = isn\'t it? \'Good, isn\'t it.\' The ne tag turns a statement into shared agreement.',
     parts:[{t:'いい', tr:'ii', m:'good'}, {t:'です', tr:'desu', m:'is'}, {t:'ね', tr:'ne', m:'isn\'t it? (agreement tag)'}],
     tags:['basics']},
    {id:'bas-sugoi', term:'すごい', tr:'sugoi', en:'Amazing / Wow', memo:'sugoi = amazing, originally \'dreadful\'. Think \'sue-goy, wow!\'. The all-purpose exclamation.',
     parts:[{t:'すごい', tr:'sugoi', m:'amazing, wow'}],
     tags:['basics']},
    {id:'bas-chotto', term:'ちょっと', tr:'chotto', en:'A little / A bit', memo:'chotto = a little, a moment. Also the polite no: \'chotto...\' with a trailing voice means \'that\'s a bit...\'.',
     parts:[{t:'ちょっと', tr:'chotto', m:'a little, a moment'}],
     tags:['basics'],
     note:'Also a soft no: ちょっと… (chotto...)',
     ex:{term:'ちょっと待ってください。', tr:'chotto matte kudasai.', en:'Please wait a moment.'}},
    {id:'bas-totemo', term:'とても', tr:'totemo', en:'Very', memo:'totemo = very. Think \'totally\'. Goes before adjectives: totemo oishii.',
     parts:[{t:'とても', tr:'totemo', m:'very'}],
     tags:['basics']},
    {id:'bas-tabun', term:'たぶん', tr:'tabun', en:'Maybe / Probably', memo:'ta = many + bun = part: \'in many parts\' = probably. Think \'ta-bun, there\'s a good portion of chance\'.',
     parts:[{t:'た', tr:'ta', m:'many'}, {t:'ぶん', tr:'bun', m:'part, portion'}],
     tags:['basics']},
    {id:'bas-mochiron', term:'もちろん', tr:'mochiron', en:'Of course', memo:'mochi = hold + ron = argument: \'no argument to hold\' = of course. Think \'mochi, of course!\'.',
     parts:[{t:'もち', tr:'mochi', m:'hold (motsu)'}, {t:'ろん', tr:'ron', m:'argument, discussion'}],
     tags:['basics']},

    /* ---------------- NUMBERS ---------------- */
    {id:'num-ichi', term:'一', tr:'ichi', en:'One', memo:'ichi = one. \'Itchy\' one finger. One horizontal stroke: 一.',
     parts:[{t:'一', tr:'ichi', m:'one'}],
     tags:['numbers'],
     note:'Counting: いち、に、さん、よん、ご、ろく、なな、はち、きゅう、じゅう.'},
    {id:'num-ni', term:'二', tr:'ni', en:'Two', memo:'ni = two. Two strokes: 二. \'Knee\' has two in it: two knees.',
     parts:[{t:'二', tr:'ni', m:'two'}],
     tags:['numbers']},
    {id:'num-san', term:'三', tr:'san', en:'Three', memo:'san = three. Three strokes: 三. Not the san of Mr/Ms, same sound only.',
     parts:[{t:'三', tr:'san', m:'three'}],
     tags:['numbers']},
    {id:'num-yon', term:'四', tr:'yon', en:'Four', memo:'yon = four, said instead of shi because shi also means death. Think \'yawn\' at 4am.',
     parts:[{t:'四', tr:'yon', m:'four'}],
     tags:['numbers'],
     note:'Also し (shi), avoided because it sounds like "death".'},
    {id:'num-go', term:'五', tr:'go', en:'Five', memo:'go = five. \'Five, go!\' as in a countdown.',
     parts:[{t:'五', tr:'go', m:'five'}],
     tags:['numbers']},
    {id:'num-roku', term:'六', tr:'roku', en:'Six', memo:'roku = six. Think \'rock you\', six strings on a guitar.',
     parts:[{t:'六', tr:'roku', m:'six'}],
     tags:['numbers']},
    {id:'num-nana', term:'七', tr:'nana', en:'Seven', memo:'nana = seven, said instead of shichi which sounds like ichi. Think \'Nana is seventy\'.',
     parts:[{t:'七', tr:'nana', m:'seven'}],
     tags:['numbers'],
     note:'Also しち (shichi).'},
    {id:'num-hachi', term:'八', tr:'hachi', en:'Eight', memo:'hachi = eight. Think \'hatch eight eggs\'. The famous dog Hachikō was the eighth pup.',
     parts:[{t:'八', tr:'hachi', m:'eight'}],
     tags:['numbers']},
    {id:'num-kyuu', term:'九', tr:'kyū', en:'Nine', memo:'kyū = nine. Think \'cue\' ball, nine-ball pool.',
     parts:[{t:'九', tr:'kyū', m:'nine'}],
     tags:['numbers'],
     note:'Also く (ku).'},
    {id:'num-juu', term:'十', tr:'jū', en:'Ten', memo:'jū = ten, the cross 十. \'Jew-ten\': think of the ten commandments.',
     parts:[{t:'十', tr:'jū', m:'ten'}],
     tags:['numbers']},
    {id:'num-hyaku', term:'百', tr:'hyaku', en:'One hundred', memo:'hyaku = hundred. Think \'hyah-koo\': a hundred hikers. 百 is 一 over 白 (white).',
     parts:[{t:'百', tr:'hyaku', m:'hundred'}],
     tags:['numbers']},
    {id:'num-sen', term:'千', tr:'sen', en:'One thousand', memo:'sen = thousand. sen en = 1000 yen, the small note. Think \'a thousand sent\'.',
     parts:[{t:'千', tr:'sen', m:'thousand'}],
     tags:['numbers'],
     ex:{term:'千円', tr:'sen en', en:'1,000 yen'}},
    {id:'num-hitotsu', term:'ひとつ', tr:'hitotsu', en:'One (thing)', memo:'hito-tsu, futa-tsu, mit-tsu: the native counting words for things. hito is also person; \'one person-thing\'.',
     parts:[{t:'ひと', tr:'hito', m:'one (native number)'}, {t:'つ', tr:'tsu', m:'general counter for things'}],
     tags:['numbers','food'],
     note:'The general counter: ひとつ、ふたつ、みっつ. Use it when ordering.',
     ex:{term:'ビールをふたつ。', tr:'bīru o futatsu.', en:'Two beers.'}},

    /* ---------------- QUESTION WORDS ---------------- */
    {id:'q-nani', term:'何', tr:'nani', en:'What?', memo:'nani = what. \'Nani?!\' is the anime shout. Before desu it shortens to nan: nan desu ka.',
     parts:[{t:'何', tr:'nani', m:'what'}],
     tags:['questions'],
     note:'Becomes なん (nan) before です.',
     ex:{term:'これは何ですか。', tr:'kore wa nan desu ka.', en:'What is this?'}},
    {id:'q-doko', term:'どこ', tr:'doko', en:'Where?', memo:'doko = where. The do- words are questions: doko where, dore which, dō how, dare who.',
     parts:[{t:'どこ', tr:'doko', m:'where (do- = question)'}],
     tags:['questions'],
     ex:{term:'トイレはどこですか。', tr:'toire wa doko desu ka.', en:'Where is the toilet?'}},
    {id:'q-itsu', term:'いつ', tr:'itsu', en:'When?', memo:'itsu = when. Think \'it\'s... when?\'.',
     parts:[{t:'いつ', tr:'itsu', m:'when'}],
     tags:['questions']},
    {id:'q-doushite', term:'どうして', tr:'dōshite', en:'Why?', memo:'dō = how + shite = doing: \'doing how?\' = why. Another do- question word.',
     parts:[{t:'どう', tr:'dō', m:'how'}, {t:'して', tr:'shite', m:'doing (from suru)'}],
     tags:['questions'],
     note:'なぜ (naze) is the same, a bit more formal.'},
    {id:'q-dou', term:'どう', tr:'dō', en:'How?', memo:'dō = how. \'Dough, how?\' dō desu ka = how is it?',
     parts:[{t:'どう', tr:'dō', m:'how'}],
     tags:['questions'],
     ex:{term:'どうですか。', tr:'dō desu ka.', en:'How is it?'}},
    {id:'q-dare', term:'誰', tr:'dare', en:'Who?', memo:'dare = who. Think \'who dares?\'. da-re, two syllables.',
     parts:[{t:'誰', tr:'dare', m:'who'}],
     tags:['questions']},
    {id:'q-ikura', term:'いくら', tr:'ikura', en:'How much?', memo:'ikura = how much. Also the word for salmon roe, which is pricey: \'how much for the ikura?\'.',
     parts:[{t:'いくら', tr:'ikura', m:'how much'}],
     tags:['questions','shopping'],
     ex:{term:'いくらですか。', tr:'ikura desu ka.', en:'How much is it?'}},
    {id:'q-dore', term:'どれ', tr:'dore', en:'Which one?', memo:'dore = which one (of several). Same do- family; ends in -re like kore, sore, are.',
     parts:[{t:'どれ', tr:'dore', m:'which one'}],
     tags:['questions']},
    {id:'q-ka', term:'か', tr:'ka', en:'(question marker)', memo:'ka at the end of any sentence makes it a question. No word order change, no rising tone needed. Think \'ka = ?\'.',
     parts:[{t:'か', tr:'ka', m:'question marker (= ?)'}],
     tags:['questions'],
     note:'Ends a sentence to make it a question. No rising tone needed.',
     ex:{term:'日本人ですか。', tr:'nihonjin desu ka.', en:'Are you Japanese?'}},

    /* ---------------- PRONOUNS ---------------- */
    {id:'pro-watashi', term:'私', tr:'watashi', en:'I', memo:'watashi = I, the private self (the kanji 私 means private). Men say boku casually; watashi is safe for everyone.',
     parts:[{t:'私', tr:'watashi', m:'I (private self)'}],
     tags:['pronouns'],
     note:'Usually dropped. Men also say 僕 (boku) casually.'},
    {id:'pro-anata', term:'あなた', tr:'anata', en:'You', memo:'anata = you, but Japanese avoids it: use the person\'s name + san. Think \'an outer\' person.',
     parts:[{t:'あなた', tr:'anata', m:'you'}],
     tags:['pronouns'],
     note:'Avoid with people you know. Use their name + さん instead.'},
    {id:'pro-kare', term:'彼', tr:'kare', en:'He', memo:'kare = he. Think \'care about him\'. Also \'boyfriend\', so use with care.',
     parts:[{t:'彼', tr:'kare', m:'he, boyfriend'}],
     tags:['pronouns'],
     note:'Also "boyfriend".'},
    {id:'pro-kanojo', term:'彼女', tr:'kanojo', en:'She', memo:'kano = that + jo = woman: \'that woman\' = she, also girlfriend. jo is the jo of joshi (girl).',
     parts:[{t:'彼', tr:'kano', m:'that'}, {t:'女', tr:'jo', m:'woman'}],
     tags:['pronouns'],
     note:'Also "girlfriend".'},
    {id:'pro-watashitachi', term:'私たち', tr:'watashitachi', en:'We', memo:'watashi + tachi: -tachi makes people plural. watashitachi we, kodomotachi children.',
     parts:[{t:'私', tr:'watashi', m:'I'}, {t:'たち', tr:'tachi', m:'plural for people'}],
     tags:['pronouns']},
    {id:'pro-kore', term:'これ', tr:'kore', en:'This (near me)', memo:'ko-re = this (near me). The ko/so/a/do system: ko near me, so near you, a over there, do question.',
     parts:[{t:'こ', tr:'ko', m:'near me'}, {t:'れ', tr:'re', m:'thing'}],
     tags:['pronouns']},
    {id:'pro-sore', term:'それ', tr:'sore', en:'That (near you)', memo:'so-re = that near you. so = your side. sore desu = that\'s it.',
     parts:[{t:'そ', tr:'so', m:'near you'}, {t:'れ', tr:'re', m:'thing'}],
     tags:['pronouns']},
    {id:'pro-are', term:'あれ', tr:'are', en:'That (over there)', memo:'a-re = that over there, far from both. Said \'ah-re\', not like English \'are\'.',
     parts:[{t:'あ', tr:'a', m:'over there'}, {t:'れ', tr:'re', m:'thing'}],
     tags:['pronouns']},
    {id:'pro-no', term:'の', tr:'no', en:'\'s (possession)', memo:'no = \'s, links owner to thing: watashi no namae = my name. Think \'no\' as the apostrophe-s.',
     parts:[{t:'の', tr:'no', m:'possessive link (\'s, of)'}],
     tags:['pronouns'],
     ex:{term:'私の名前', tr:'watashi no namae', en:'My name'}},
    {id:'pro-san', term:'さん', tr:'san', en:'Mr / Ms (after a name)', memo:'san after a name = Mr, Ms, Mrs, all in one. Never on yourself. Think \'san = sir/ma\'am\'.',
     parts:[{t:'さん', tr:'san', m:'Mr / Ms (polite name suffix)'}],
     tags:['pronouns','politeness'],
     note:'Never put it on your own name.'},

    /* ---------------- TIME ---------------- */
    {id:'time-kyou', term:'今日', tr:'kyō', en:'Today', memo:'kyō = today, written 今日 \'now-day\', the same kanji as konnichi(wa) read a second way.',
     parts:[{t:'今日', tr:'kyō', m:'today (now-day)'}],
     tags:['time']},
    {id:'time-ashita', term:'明日', tr:'ashita', en:'Tomorrow', memo:'ashita = tomorrow, 明日 \'bright-day\', the day that is coming. Think \'ah, she\'ll come tomorrow\'.',
     parts:[{t:'明日', tr:'ashita', m:'tomorrow (bright-day)'}],
     tags:['time']},
    {id:'time-kinou', term:'昨日', tr:'kinō', en:'Yesterday', memo:'kinō = yesterday, 昨日 \'previous-day\'. Think \'key-no\', the day already locked.',
     parts:[{t:'昨日', tr:'kinō', m:'yesterday (previous-day)'}],
     tags:['time']},
    {id:'time-ima', term:'今', tr:'ima', en:'Now', memo:'ima = now, the ima of tadaima (\'just now\'). 今 alone.',
     parts:[{t:'今', tr:'ima', m:'now'}],
     tags:['time']},
    {id:'time-ato-de', term:'後で', tr:'ato de', en:'Later', memo:'ato = after, behind + de = at: \'at after\' = later. mata ato de = again later.',
     parts:[{t:'後', tr:'ato', m:'after, behind'}, {t:'で', tr:'de', m:'at (time or place marker)'}],
     tags:['time'],
     ex:{term:'また後で。', tr:'mata ato de.', en:'See you later.'}},
    {id:'time-nanji', term:'何時ですか', tr:'nanji desu ka', en:'What time is it?', memo:'nan = what + ji = o\'clock (hour): \'what o\'clock?\'. ji also counts hours: ichi-ji one o\'clock.',
     parts:[{t:'何', tr:'nan', m:'what'}, {t:'時', tr:'ji', m:'o\'clock, hour'}, {t:'です', tr:'desu', m:'is'}, {t:'か', tr:'ka', m:'question marker'}],
     tags:['time','questions']},
    {id:'time-asa', term:'朝', tr:'asa', en:'Morning', memo:'asa = morning. Think \'as a morning person\'. asagohan = breakfast (morning rice).',
     parts:[{t:'朝', tr:'asa', m:'morning'}],
     tags:['time']},
    {id:'time-yoru', term:'夜', tr:'yoru', en:'Night / Evening', memo:'yoru = night. Think \'yore\', the dark of old nights. 夜.',
     parts:[{t:'夜', tr:'yoru', m:'night'}],
     tags:['time']},
    {id:'time-getsuyoubi', term:'月曜日', tr:'getsuyōbi', en:'Monday', memo:'getsu = moon + yōbi = weekday: moon-day, like English Monday. The weekdays follow sun, moon, fire, water, wood, metal, earth.',
     parts:[{t:'月', tr:'getsu', m:'moon'}, {t:'曜日', tr:'yōbi', m:'day of the week'}],
     tags:['time'],
     note:'Days: 月火水木金土日 + 曜日 (yōbi).'},
    {id:'time-kinyoubi', term:'金曜日', tr:'kin\'yōbi', en:'Friday', memo:'kin = gold, metal + yōbi: metal-day = Friday (Venus day in the planet system).',
     parts:[{t:'金', tr:'kin', m:'gold, metal'}, {t:'曜日', tr:'yōbi', m:'day of the week'}],
     tags:['time']},
    {id:'time-doyoubi', term:'土曜日', tr:'doyōbi', en:'Saturday', memo:'do = earth, soil + yōbi: earth-day = Saturday (Saturn day).',
     parts:[{t:'土', tr:'do', m:'earth, soil'}, {t:'曜日', tr:'yōbi', m:'day of the week'}],
     tags:['time']},
    {id:'time-nichiyoubi', term:'日曜日', tr:'nichiyōbi', en:'Sunday', memo:'nichi = sun, day + yōbi: sun-day. Exactly English Sunday.',
     parts:[{t:'日', tr:'nichi', m:'sun, day'}, {t:'曜日', tr:'yōbi', m:'day of the week'}],
     tags:['time']},
    {id:'time-shuumatsu', term:'週末', tr:'shūmatsu', en:'Weekend', memo:'shū = week + matsu = end: week-end, piece for piece.',
     parts:[{t:'週', tr:'shū', m:'week'}, {t:'末', tr:'matsu', m:'end'}],
     tags:['time']},

    /* ---------------- FOOD & ORDERING ---------------- */
    {id:'food-mizu', term:'水', tr:'mizu', en:'Water', memo:'mizu = water. Think \'Mizu-no\' (the sports brand): water-field. o-mizu when ordering.',
     parts:[{t:'水', tr:'mizu', m:'water'}],
     tags:['food'],
     ex:{term:'お水をください。', tr:'o-mizu o kudasai.', en:'Water, please.'}},
    {id:'food-ocha', term:'お茶', tr:'ocha', en:'Tea (green)', memo:'o- honorific + cha = tea (the same cha as in chai and China tea). Tea is so respected it gets the o-.',
     parts:[{t:'お', tr:'o', m:'honorific'}, {t:'茶', tr:'cha', m:'tea (cha, chai)'}],
     tags:['food']},
    {id:'food-koohii', term:'コーヒー', tr:'kōhī', en:'Coffee', memo:'kōhī = coffee, borrowed from Dutch koffie. Katakana words are mostly English or Dutch in disguise.',
     parts:[{t:'コーヒー', tr:'kōhī', m:'coffee (loanword)'}],
     tags:['food']},
    {id:'food-biiru', term:'ビール', tr:'bīru', en:'Beer', memo:'bīru = beer, from Dutch bier. Katakana, so you can already read it.',
     parts:[{t:'ビール', tr:'bīru', m:'beer (loanword)'}],
     tags:['food'],
     ex:{term:'ビールをふたつください。', tr:'bīru o futatsu kudasai.', en:'Two beers, please.'}},
    {id:'food-gohan', term:'ご飯', tr:'gohan', en:'Rice / A meal', memo:'go- honorific + han = cooked rice. Rice is the meal, so gohan also means a meal: asagohan, hirugohan, bangohan.',
     parts:[{t:'ご', tr:'go', m:'honorific'}, {t:'飯', tr:'han', m:'cooked rice, meal'}],
     tags:['food']},
    {id:'food-oishii', term:'おいしい', tr:'oishii', en:'Delicious', memo:'oishii = delicious. Think \'oh-ee-she\' said with a happy sigh. -ii ending = adjective.',
     parts:[{t:'おいし', tr:'oishi', m:'tasty'}, {t:'い', tr:'i', m:'adjective ending'}],
     tags:['food'],
     ex:{term:'とてもおいしいです。', tr:'totemo oishii desu.', en:'It\'s very tasty.'}},
    {id:'food-okaikei', term:'お会計をお願いします', tr:'o-kaikei o onegai shimasu', en:'The bill, please', memo:'o- + kaikei = accounting, the bill (kei = calculate, as in keisan). o onegai shimasu = please.',
     parts:[{t:'お', tr:'o', m:'honorific'}, {t:'会計', tr:'kaikei', m:'bill, accounting'}, {t:'を', tr:'o', m:'object marker'}, {t:'お願いします', tr:'onegai shimasu', m:'please'}],
     tags:['food'],
     note:'Crossing your index fingers in an X also asks for the bill.'},
    {id:'food-menyuu', term:'メニューをください', tr:'menyū o kudasai', en:'The menu, please', memo:'menyū = menu, a loanword. o = object marker, kudasai = please give. \'Menu, please give.\'',
     parts:[{t:'メニュー', tr:'menyū', m:'menu (loanword)'}, {t:'を', tr:'o', m:'object marker'}, {t:'ください', tr:'kudasai', m:'please give'}],
     tags:['food']},
    {id:'food-osusume', term:'おすすめは何ですか', tr:'osusume wa nan desu ka', en:'What do you recommend?', memo:'o- + susume = recommendation (susumeru = to recommend, push forward). wa nan desu ka = as for it, what is it?',
     parts:[{t:'お', tr:'o', m:'honorific'}, {t:'すすめ', tr:'susume', m:'recommendation'}, {t:'は', tr:'wa', m:'topic marker'}, {t:'何', tr:'nan', m:'what'}, {t:'ですか', tr:'desu ka', m:'is it?'}],
     tags:['food']},
    {id:'food-onaka-suita', term:'お腹が空きました', tr:'onaka ga sukimashita', en:'I\'m hungry', memo:'onaka = stomach (o- + naka = inside), ga = subject, sukimashita = became empty. \'Stomach became empty.\'',
     parts:[{t:'お腹', tr:'onaka', m:'stomach (inside)'}, {t:'が', tr:'ga', m:'subject marker'}, {t:'空き', tr:'suki', m:'become empty'}, {t:'ました', tr:'mashita', m:'did (polite past)'}],
     tags:['food','feelings'],
     note:'Casual: お腹すいた (onaka suita).'},
    {id:'food-nodo-kawaita', term:'喉が渇きました', tr:'nodo ga kawakimashita', en:'I\'m thirsty', memo:'nodo = throat, ga = subject, kawakimashita = dried. \'Throat has dried.\' Same shape as onaka ga sukimashita.',
     parts:[{t:'喉', tr:'nodo', m:'throat'}, {t:'が', tr:'ga', m:'subject marker'}, {t:'渇き', tr:'kawaki', m:'dry up'}, {t:'ました', tr:'mashita', m:'did (polite past)'}],
     tags:['food','feelings']},
    {id:'food-nuki', term:'抜きで', tr:'nuki de', en:'Without', memo:'nuki = pulled out (nuku = pull out), de = by means of: \'with X pulled out\'. satō nuki de = sugar out.',
     parts:[{t:'抜き', tr:'nuki', m:'removed, without'}, {t:'で', tr:'de', m:'by, with (manner marker)'}],
     tags:['food'],
     ex:{term:'砂糖抜きで。', tr:'satō nuki de.', en:'Without sugar.'}},
    {id:'food-futari', term:'二人です', tr:'futari desu', en:'Table for two', memo:'futa = two (native) + ri = person counter: two people. hitori one, futari two, then san-nin, yo-nin.',
     parts:[{t:'二', tr:'futa', m:'two (native number)'}, {t:'人', tr:'ri', m:'person (counter)'}, {t:'です', tr:'desu', m:'is (we are)'}],
     tags:['food'],
     note:'Said at the door. One person: 一人 (hitori).'},
    {id:'food-mochikaeri', term:'持ち帰り', tr:'mochikaeri', en:'Takeaway', memo:'mochi = hold (motsu) + kaeri = return (kaeru): \'hold and go home\' = takeaway.',
     parts:[{t:'持ち', tr:'mochi', m:'hold, carry'}, {t:'帰り', tr:'kaeri', m:'go home, return'}],
     tags:['food'],
     note:'Eat in: 店内で (tennai de).'},

    /* ---------------- PLACES & DIRECTIONS ---------------- */
    {id:'place-wa-doko', term:'〜はどこですか', tr:'... wa doko desu ka', en:'Where is ...?', memo:'X wa doko desu ka: \'as for X, where is it?\'. wa marks the topic, doko = where, desu ka = is it?',
     parts:[{t:'〜は', tr:'wa', m:'as for (topic marker)'}, {t:'どこ', tr:'doko', m:'where'}, {t:'です', tr:'desu', m:'is'}, {t:'か', tr:'ka', m:'question marker'}],
     tags:['places','questions'],
     ex:{term:'駅はどこですか。', tr:'eki wa doko desu ka.', en:'Where is the station?'}},
    {id:'place-hidari', term:'左', tr:'hidari', en:'Left', memo:'hidari = left. Think \'he dares to go left\'. 左.',
     parts:[{t:'左', tr:'hidari', m:'left'}],
     tags:['places']},
    {id:'place-migi', term:'右', tr:'migi', en:'Right', memo:'migi = right. Think \'me gee, right!\'. 右.',
     parts:[{t:'右', tr:'migi', m:'right'}],
     tags:['places']},
    {id:'place-massugu', term:'まっすぐ', tr:'massugu', en:'Straight ahead', memo:'massugu = straight. Think \'mass-sugar\' poured in a straight line. The doubled s is a tiny pause.',
     parts:[{t:'まっすぐ', tr:'massugu', m:'straight'}],
     tags:['places']},
    {id:'place-koko', term:'ここ', tr:'koko', en:'Here', memo:'ko-ko = here. The ko of kore (near me) + ko = place. soko there, asoko over there, doko where.',
     parts:[{t:'こ', tr:'ko', m:'near me'}, {t:'こ', tr:'ko', m:'place'}],
     tags:['places']},
    {id:'place-asoko', term:'あそこ', tr:'asoko', en:'Over there', memo:'a-soko = over there, far from both. The a- of are (that over there).',
     parts:[{t:'あ', tr:'a', m:'over there (far)'}, {t:'そこ', tr:'soko', m:'place'}],
     tags:['places']},
    {id:'place-chikai', term:'近い', tr:'chikai', en:'Near', memo:'chikai = near. Think \'chick-eye\', close enough to see. -i adjective.',
     parts:[{t:'近', tr:'chika', m:'near'}, {t:'い', tr:'i', m:'adjective ending'}],
     tags:['places']},
    {id:'place-tooi', term:'遠い', tr:'tōi', en:'Far', memo:'tōi = far. Long ō, as if stretching into the distance: tō-i.',
     parts:[{t:'遠', tr:'tō', m:'far'}, {t:'い', tr:'i', m:'adjective ending'}],
     tags:['places']},
    {id:'place-eki', term:'駅', tr:'eki', en:'Station', memo:'eki = station. Think \'ekk-y\', the station where trains stop. 駅.',
     parts:[{t:'駅', tr:'eki', m:'station'}],
     tags:['places']},
    {id:'place-toire', term:'トイレ', tr:'toire', en:'Toilet', memo:'toire = toilet, an English loan with Japanese sounds (no l, no final t).',
     parts:[{t:'トイレ', tr:'toire', m:'toilet (loanword)'}],
     tags:['places'],
     note:'Politer: お手洗い (o-tearai).'},
    {id:'place-kuukou', term:'空港', tr:'kūkō', en:'Airport', memo:'kū = sky, air (as in kūki, air) + kō = port, harbour: sky-port. Like \'airport\', piece for piece.',
     parts:[{t:'空', tr:'kū', m:'sky, air'}, {t:'港', tr:'kō', m:'port, harbour'}],
     tags:['places']},
    {id:'place-konbini', term:'コンビニ', tr:'konbini', en:'Convenience store', memo:'konbini = convenience store, clipped from English \'convenience\'. 7-Eleven, Lawson, FamilyMart.',
     parts:[{t:'コンビニ', tr:'konbini', m:'convenience store (loanword)'}],
     tags:['places']},

    /* ---------------- SHOPPING & MONEY ---------------- */
    {id:'shop-ikura', term:'いくらですか', tr:'ikura desu ka', en:'How much is it?', memo:'ikura = how much + desu ka = is it? Point at the thing: kore wa ikura desu ka.',
     parts:[{t:'いくら', tr:'ikura', m:'how much'}, {t:'です', tr:'desu', m:'is'}, {t:'か', tr:'ka', m:'question marker'}],
     tags:['shopping']},
    {id:'shop-takai', term:'高い', tr:'takai', en:'Expensive', memo:'takai = high, so also expensive and tall. Think \'take a high price\'.',
     parts:[{t:'高', tr:'taka', m:'high, expensive'}, {t:'い', tr:'i', m:'adjective ending'}],
     tags:['shopping'],
     note:'Also "tall".'},
    {id:'shop-yasui', term:'安い', tr:'yasui', en:'Cheap', memo:'yasui = cheap, also easy. Think \'yes, we can afford it\'.',
     parts:[{t:'安', tr:'yasu', m:'cheap, peaceful'}, {t:'い', tr:'i', m:'adjective ending'}],
     tags:['shopping']},
    {id:'shop-kaado', term:'カードは使えますか', tr:'kādo wa tsukaemasu ka', en:'Can I pay by card?', memo:'kādo = card (loanword), wa = as for, tsukaemasu = can be used (tsukau = use), ka = ? \'As for card, usable?\'',
     parts:[{t:'カード', tr:'kādo', m:'card (loanword)'}, {t:'は', tr:'wa', m:'topic marker'}, {t:'使え', tr:'tsukae', m:'can use'}, {t:'ます', tr:'masu', m:'polite present'}, {t:'か', tr:'ka', m:'question marker'}],
     tags:['shopping']},
    {id:'shop-genkin', term:'現金', tr:'genkin', en:'Cash', memo:'gen = present, actual + kin = gold, money: \'actual money\' = cash. kin is the kin of kin\'yōbi.',
     parts:[{t:'現', tr:'gen', m:'present, actual'}, {t:'金', tr:'kin', m:'gold, money'}],
     tags:['shopping']},
    {id:'shop-okane', term:'お金', tr:'okane', en:'Money', memo:'o- + kane = metal, money. Money gets an honorific. \'Oh, kane (cash)\'.',
     parts:[{t:'お', tr:'o', m:'honorific'}, {t:'金', tr:'kane', m:'money, metal'}],
     tags:['shopping']},
    {id:'shop-en', term:'円', tr:'en', en:'Yen', memo:'en = yen; the y came from old romanisation. The kanji 円 means circle, a round coin.',
     parts:[{t:'円', tr:'en', m:'yen (circle)'}],
     tags:['shopping']},
    {id:'shop-kore-kudasai', term:'これをください', tr:'kore o kudasai', en:'I\'ll take this one', memo:'kore = this, o = object marker, kudasai = please give. Point and say it: the one phrase that buys anything.',
     parts:[{t:'これ', tr:'kore', m:'this'}, {t:'を', tr:'o', m:'object marker'}, {t:'ください', tr:'kudasai', m:'please give'}],
     tags:['shopping']},
    {id:'shop-miteru-dake', term:'見ているだけです', tr:'mite iru dake desu', en:'Just looking', memo:'mite iru = am looking (miru = see), dake = only, desu = is. \'Only looking.\'',
     parts:[{t:'見ている', tr:'mite iru', m:'am looking (miru)'}, {t:'だけ', tr:'dake', m:'only'}, {t:'です', tr:'desu', m:'is'}],
     tags:['shopping']},
    {id:'shop-fukuro', term:'袋', tr:'fukuro', en:'Bag', memo:'fukuro = bag. Think \'fuku-row\' of shopping bags. The till asks fukuro wa? (bag?).',
     parts:[{t:'袋', tr:'fukuro', m:'bag'}],
     tags:['shopping'],
     note:'At the till: 袋はいりますか (need a bag?). Say 大丈夫です for no.'},

    /* ---------------- FEELINGS & SMALL TALK ---------------- */
    {id:'feel-ureshii', term:'嬉しい', tr:'ureshii', en:'Happy / Glad', memo:'ureshii = glad. Think \'ooh-rare-she\' is glad. -ii adjective. Said on receiving something.',
     parts:[{t:'嬉し', tr:'ureshi', m:'glad, happy'}, {t:'い', tr:'i', m:'adjective ending'}],
     tags:['feelings']},
    {id:'feel-tsukareta', term:'疲れました', tr:'tsukaremashita', en:'I\'m tired', memo:'tsukareru = to get tired; -mashita = did: \'I got tired\'. Think \'tsu-ka-re-ta\', sounds like a tired sigh.',
     parts:[{t:'疲れ', tr:'tsukare', m:'get tired'}, {t:'ました', tr:'mashita', m:'did (polite past)'}],
     tags:['feelings']},
    {id:'feel-atsui', term:'暑いですね', tr:'atsui desu ne', en:'It\'s hot, isn\'t it', memo:'atsui = hot (weather). Think \'ah, it\'s wee hot\'. desu ne = is, isn\'t it: the small-talk tag.',
     parts:[{t:'暑', tr:'atsu', m:'hot (weather)'}, {t:'い', tr:'i', m:'adjective ending'}, {t:'です', tr:'desu', m:'is'}, {t:'ね', tr:'ne', m:'isn\'t it?'}],
     tags:['feelings','time'],
     note:'ね (ne) invites agreement. Small talk starts here.'},
    {id:'feel-samui', term:'寒いですね', tr:'samui desu ne', en:'It\'s cold, isn\'t it', memo:'samui = cold (weather). Think \'Sam, you\'re cold\'. Same desu ne tag as atsui.',
     parts:[{t:'寒', tr:'samu', m:'cold (weather)'}, {t:'い', tr:'i', m:'adjective ending'}, {t:'です', tr:'desu', m:'is'}, {t:'ね', tr:'ne', m:'isn\'t it?'}],
     tags:['feelings','time']},
    {id:'feel-suki', term:'好きです', tr:'suki desu', en:'I like it', memo:'suki = liked, desu = is. Things are \'liked\' rather than you liking them: nihon ga suki desu, with ga marking the thing.',
     parts:[{t:'好き', tr:'suki', m:'liked, fond of'}, {t:'です', tr:'desu', m:'is'}],
     tags:['feelings','verbs'],
     ex:{term:'日本が好きです。', tr:'nihon ga suki desu.', en:'I like Japan.'}},
    {id:'feel-kirai', term:'嫌いです', tr:'kirai desu', en:'I dislike it', memo:'kirai = disliked (kirau = to hate). Mirror of suki, same desu. Strong; soften with amari ... ja nai.',
     parts:[{t:'嫌い', tr:'kirai', m:'disliked'}, {t:'です', tr:'desu', m:'is'}],
     tags:['feelings','verbs'],
     note:'Strong. Softer: あまり好きじゃないです (amari suki ja nai desu).'},
    {id:'feel-tanoshii', term:'楽しい', tr:'tanoshii', en:'Fun', memo:'tanoshii = fun, enjoyable. Think \'tah-no-she\' having fun. -ii adjective, like oishii and ureshii.',
     parts:[{t:'楽し', tr:'tanoshi', m:'fun, enjoyable'}, {t:'い', tr:'i', m:'adjective ending'}],
     tags:['feelings']},
    {id:'feel-ganbatte', term:'頑張って', tr:'ganbatte', en:'Good luck / Do your best', memo:'ganbaru = to persevere; -tte is the request form: \'persevere!\'. Think \'gun-bar-tay\': hold the bar.',
     parts:[{t:'頑張っ', tr:'ganbat', m:'persevere, do your best'}, {t:'て', tr:'te', m:'request form (please...)'}],
     tags:['feelings']},
    {id:'feel-otsukare', term:'お疲れ様です', tr:'otsukaresama desu', en:'Thanks for your hard work', memo:'o- + tsukare = tiredness (tsukareta) + sama = honoured + desu: \'honoured tiredness\', thanks for the effort.',
     parts:[{t:'お', tr:'o', m:'honorific'}, {t:'疲れ', tr:'tsukare', m:'tiredness'}, {t:'様', tr:'sama', m:'honoured'}, {t:'です', tr:'desu', m:'is'}],
     tags:['feelings','politeness'],
     note:'Said constantly at work and when parting with colleagues.'},

    /* ---------------- VERBS (polite present) ---------------- */
    {id:'verb-tabemasu', term:'食べます', tr:'tabemasu', en:'I eat', memo:'tabe = eat (taberu) + masu = polite present. -masu is the ending to learn: it never changes for I, you, they.',
     parts:[{t:'食べ', tr:'tabe', m:'eat'}, {t:'ます', tr:'masu', m:'polite present'}],
     tags:['verbs'],
     note:'Polite present. The same form works for every person.'},
    {id:'verb-nomimasu', term:'飲みます', tr:'nomimasu', en:'I drink', memo:'nomi = drink (nomu) + masu. Think \'no-me, I drink\'. nomimono = drinks.',
     parts:[{t:'飲み', tr:'nomi', m:'drink'}, {t:'ます', tr:'masu', m:'polite present'}],
     tags:['verbs']},
    {id:'verb-ikimasu', term:'行きます', tr:'ikimasu', en:'I go', memo:'iki = go (iku) + masu. The iki of ittekimasu. X ni ikimasu = go to X; ni marks the destination.',
     parts:[{t:'行き', tr:'iki', m:'go'}, {t:'ます', tr:'masu', m:'polite present'}],
     tags:['verbs'],
     ex:{term:'東京に行きます。', tr:'tōkyō ni ikimasu.', en:'I\'m going to Tokyo.'}},
    {id:'verb-kimasu', term:'来ます', tr:'kimasu', en:'I come', memo:'ki = come (kuru) + masu. The kimasu of ittekimasu: \'go and come\'.',
     parts:[{t:'来', tr:'ki', m:'come'}, {t:'ます', tr:'masu', m:'polite present'}],
     tags:['verbs']},
    {id:'verb-mimasu', term:'見ます', tr:'mimasu', en:'I see / I watch', memo:'mi = see, look (miru) + masu. The mi of mite iru dake (just looking).',
     parts:[{t:'見', tr:'mi', m:'see, watch'}, {t:'ます', tr:'masu', m:'polite present'}],
     tags:['verbs']},
    {id:'verb-hanashimasu', term:'話します', tr:'hanashimasu', en:'I speak', memo:'hanashi = speak (hanasu) + masu. hanashi is also \'a story, a talk\'.',
     parts:[{t:'話し', tr:'hanashi', m:'speak, talk'}, {t:'ます', tr:'masu', m:'polite present'}],
     tags:['verbs'],
     ex:{term:'日本語を少し話します。', tr:'nihongo o sukoshi hanashimasu.', en:'I speak a little Japanese.'}},
    {id:'verb-wakarimasu', term:'わかります', tr:'wakarimasu', en:'I understand', memo:'wakari = understand (wakaru) + masu. The root of wakarimashita and wakarimasen.',
     parts:[{t:'わかり', tr:'wakari', m:'understand'}, {t:'ます', tr:'masu', m:'polite present'}],
     tags:['verbs']},
    {id:'verb-shitte-imasu', term:'知っています', tr:'shitte imasu', en:'I know', memo:'shitte = knowing (shiru) + imasu = am: \'am in a state of knowing\'. Knowledge is a state, so it uses -te imasu.',
     parts:[{t:'知って', tr:'shitte', m:'knowing (shiru)'}, {t:'います', tr:'imasu', m:'am (ongoing state)'}],
     tags:['verbs']},
    {id:'verb-arimasu', term:'あります', tr:'arimasu', en:'There is (things) / I have', memo:'arimasu = exists, for things. X ga arimasu = there is X, I have X. ga marks what exists.',
     parts:[{t:'あり', tr:'ari', m:'exist (things)'}, {t:'ます', tr:'masu', m:'polite present'}],
     tags:['verbs'],
     ex:{term:'時間がありますか。', tr:'jikan ga arimasu ka.', en:'Do you have time?'}},
    {id:'verb-imasu', term:'います', tr:'imasu', en:'There is (people, animals)', memo:'imasu = exists, for living things. arimasu for objects, imasu for people and animals.',
     parts:[{t:'い', tr:'i', m:'exist (living things)'}, {t:'ます', tr:'masu', m:'polite present'}],
     tags:['verbs']},
    {id:'verb-dekimasu', term:'できます', tr:'dekimasu', en:'I can / It\'s possible', memo:'deki = can, be done (dekiru) + masu. nihongo ga dekimasu = Japanese is doable for me.',
     parts:[{t:'でき', tr:'deki', m:'can, be able'}, {t:'ます', tr:'masu', m:'polite present'}],
     tags:['verbs']},
    {id:'verb-hoshii', term:'欲しいです', tr:'hoshii desu', en:'I want (a thing)', memo:'hoshii = wanted, desired, an adjective. X ga hoshii desu = X is wanted. For things only; for actions use -tai.',
     parts:[{t:'欲し', tr:'hoshi', m:'wanted, desired'}, {t:'い', tr:'i', m:'adjective ending'}, {t:'です', tr:'desu', m:'is'}],
     tags:['verbs'],
     ex:{term:'水が欲しいです。', tr:'mizu ga hoshii desu.', en:'I want water.'}},
    {id:'verb-tai', term:'〜たいです', tr:'...tai desu', en:'I want to (do)', memo:'Replace -masu with -tai: tabemasu → tabetai = want to eat. -tai then acts like an -i adjective. Think \'tie\' to the action.',
     parts:[{t:'〜たい', tr:'tai', m:'want to (replaces -masu)'}, {t:'です', tr:'desu', m:'is'}],
     tags:['verbs'],
     ex:{term:'食べたいです。', tr:'tabetai desu.', en:'I want to eat.'}},
    {id:'verb-masen', term:'〜ません', tr:'...masen', en:'(negative) don\'t', memo:'-masu → -masen for not. tabemasu I eat, tabemasen I don\'t. The sen of sumimasen.',
     parts:[{t:'〜ません', tr:'masen', m:'not (polite negative)'}],
     tags:['verbs'],
     ex:{term:'食べません。', tr:'tabemasen.', en:'I don\'t eat.'}},
    {id:'verb-mashita', term:'〜ました', tr:'...mashita', en:'(past) did', memo:'-masu → -mashita for did. tabemashita I ate, wakarimashita I understood.',
     parts:[{t:'〜ました', tr:'mashita', m:'did (polite past)'}],
     tags:['verbs'],
     ex:{term:'食べました。', tr:'tabemashita.', en:'I ate.'}},
    {id:'verb-desu', term:'です', tr:'desu', en:'is / am / are', memo:'desu = is, am, are. Goes at the end: Samu desu = I\'m Sam. Think \'this\'. Past: deshita.',
     parts:[{t:'です', tr:'desu', m:'is / am / are (polite)'}],
     tags:['verbs'],
     ex:{term:'サムです。', tr:'Samu desu.', en:'I\'m Sam.'}},

    /* ---------------- SURVIVAL ---------------- */
    {id:'surv-eigo', term:'英語を話せますか', tr:'eigo o hanasemasu ka', en:'Do you speak English?', memo:'ei = England, English + go = language. o = object, hanasemasu = can speak (potential of hanasu), ka = ?',
     parts:[{t:'英語', tr:'eigo', m:'English (England-language)'}, {t:'を', tr:'o', m:'object marker'}, {t:'話せ', tr:'hanase', m:'can speak'}, {t:'ます', tr:'masu', m:'polite present'}, {t:'か', tr:'ka', m:'question marker'}],
     tags:['survival']},
    {id:'surv-nihongo-dekimasen', term:'日本語ができません', tr:'nihongo ga dekimasen', en:'I can\'t speak Japanese', memo:'nihon = Japan + go = language; ga = subject; dekimasen = cannot (dekimasu + -masen).',
     parts:[{t:'日本語', tr:'nihongo', m:'Japanese (Japan-language)'}, {t:'が', tr:'ga', m:'subject marker'}, {t:'でき', tr:'deki', m:'can'}, {t:'ません', tr:'masen', m:'not'}],
     tags:['survival']},
    {id:'surv-yukkuri', term:'ゆっくり話してください', tr:'yukkuri hanashite kudasai', en:'Please speak slowly', memo:'yukkuri = slowly, at ease; hanashite = speak (request form) + kudasai = please. \'Speak slowly, please.\'',
     parts:[{t:'ゆっくり', tr:'yukkuri', m:'slowly'}, {t:'話して', tr:'hanashite', m:'speak (request form)'}, {t:'ください', tr:'kudasai', m:'please'}],
     tags:['survival']},
    {id:'surv-mou-ichido', term:'もう一度お願いします', tr:'mō ichido onegai shimasu', en:'Once more, please', memo:'mō = more, again + ichi = one + do = time: \'one more time\'. onegai shimasu = please.',
     parts:[{t:'もう', tr:'mō', m:'more, again'}, {t:'一度', tr:'ichido', m:'one time'}, {t:'お願いします', tr:'onegai shimasu', m:'please'}],
     tags:['survival']},
    {id:'surv-nihongo-de', term:'日本語で何と言いますか', tr:'nihongo de nan to iimasu ka', en:'How do you say it in Japanese?', memo:'nihongo de = in Japanese (de = by means of), nan to = what (quote), iimasu ka = do you say? \'In Japanese, say what?\'',
     parts:[{t:'日本語', tr:'nihongo', m:'Japanese'}, {t:'で', tr:'de', m:'in, by means of'}, {t:'何', tr:'nan', m:'what'}, {t:'と', tr:'to', m:'quote marker'}, {t:'言い', tr:'ii', m:'say (iu)'}, {t:'ますか', tr:'masu ka', m:'polite + ?'}],
     tags:['survival']},
    {id:'surv-dou-iu-imi', term:'どういう意味ですか', tr:'dō iu imi desu ka', en:'What does it mean?', memo:'dō iu = what kind of (how-say) + imi = meaning + desu ka. \'What kind of meaning is it?\'',
     parts:[{t:'どういう', tr:'dō iu', m:'what kind of'}, {t:'意味', tr:'imi', m:'meaning'}, {t:'ですか', tr:'desu ka', m:'is it?'}],
     tags:['survival']},
    {id:'surv-tasukete', term:'助けて', tr:'tasukete', en:'Help!', memo:'tasukeru = to help, save; -te = request. Think \'task-ay-tay\': help with the task! Shout it.',
     parts:[{t:'助け', tr:'tasuke', m:'help, save'}, {t:'て', tr:'te', m:'request form'}],
     tags:['survival']},
    {id:'surv-daijoubu-desu-ka', term:'大丈夫ですか', tr:'daijōbu desu ka', en:'Are you OK?', memo:'daijōbu = OK + desu ka = is it? The question version: \'are you OK?\'. Answer with daijōbu desu.',
     parts:[{t:'大丈夫', tr:'daijōbu', m:'OK, fine'}, {t:'です', tr:'desu', m:'is'}, {t:'か', tr:'ka', m:'question marker'}],
     tags:['survival']},
    {id:'surv-michi-ni-mayoimashita', term:'道に迷いました', tr:'michi ni mayoimashita', en:'I\'m lost', memo:'michi = road, ni = in, mayoimashita = got lost (mayou = wander, be lost). \'I got lost in the road.\'',
     parts:[{t:'道', tr:'michi', m:'road, way'}, {t:'に', tr:'ni', m:'in, at'}, {t:'迷い', tr:'mayoi', m:'get lost, wander'}, {t:'ました', tr:'mashita', m:'did (polite past)'}],
     tags:['survival']},

    /* ---------------- CONNECTORS ---------------- */
    {id:'con-to', term:'と', tr:'to', en:'And (between nouns)', memo:'to = and, between nouns only: pan to mizu. Also the quote marker (nan to iimasu). Think \'to-gether\'.',
     parts:[{t:'と', tr:'to', m:'and (between nouns)'}],
     tags:['connectors'],
     ex:{term:'パンと水', tr:'pan to mizu', en:'Bread and water'}},
    {id:'con-soshite', term:'そして', tr:'soshite', en:'And then', memo:'soshite = and then, joining sentences. so = that + shite = doing: \'doing that, then...\'.',
     parts:[{t:'そして', tr:'soshite', m:'and then'}],
     tags:['connectors']},
    {id:'con-demo', term:'でも', tr:'demo', en:'But', memo:'demo = but, at the start of a sentence. Think \'demo, but...\' as in \'demo version, but\'.',
     parts:[{t:'でも', tr:'demo', m:'but'}],
     tags:['connectors']},
    {id:'con-kara', term:'から', tr:'kara', en:'Because / From', memo:'kara = from, and \'because\' after a reason: takai kara = because it\'s expensive. Think \'from that cause\'.',
     parts:[{t:'から', tr:'kara', m:'because / from'}],
     tags:['connectors'],
     ex:{term:'高いから。', tr:'takai kara.', en:'Because it\'s expensive.'}},
    {id:'con-mo', term:'も', tr:'mo', en:'Also / Too', memo:'mo = also, too. Replaces wa or ga: watashi mo = me too. Think \'mo\' = more of the same.',
     parts:[{t:'も', tr:'mo', m:'also, too'}],
     tags:['connectors'],
     ex:{term:'私も。', tr:'watashi mo.', en:'Me too.'}},
    {id:'con-ka-or', term:'か (または)', tr:'ka (mata wa)', en:'Or', memo:'ka between nouns = or: ocha ka kōhī. The same ka as the question marker: \'tea? coffee?\'. mata wa is the formal or.',
     parts:[{t:'か', tr:'ka', m:'or (between nouns)'}, {t:'または', tr:'mata wa', m:'or (formal)'}],
     tags:['connectors'],
     ex:{term:'お茶かコーヒー', tr:'ocha ka kōhī', en:'Tea or coffee'}},
    {id:'con-jaa', term:'じゃあ', tr:'jā', en:'Well then', memo:'jā = well then, contracted from de wa. Starts a decision: jā, ikimashō (well then, let\'s go).',
     parts:[{t:'じゃあ', tr:'jā', m:'well then'}],
     tags:['connectors']},
    {id:'con-moshi', term:'もし', tr:'moshi', en:'If', memo:'moshi = if, placed at the start; the verb ending (-tara) does the real work. Think \'moshi moshi\' on the phone: \'if you can hear me\'.',
     parts:[{t:'もし', tr:'moshi', m:'if'}],
     tags:['connectors']},
    {id:'con-eeto', term:'えーと', tr:'ēto', en:'Um...', memo:'ēto = um, the filler. Stretch the e while you think: \'eh-toh\'. ano works too.',
     parts:[{t:'えーと', tr:'ēto', m:'um... (filler)'}],
     tags:['connectors'],
     note:'The filler while you think. Also あの (ano).'},
  ],
};
