window.TRACKS=[
{
"id": "10517614",
"t": "Tame Impala, ZHU - My Life (Brian Cid Remix)",
"g": "Melodic House & Techno",
"bpm": 120,
"key": "Cmin",
"cam": "5A",
"len": "7:12",
"u": "https://soundeo.com/track/tame-impala-zhu-my-life-brian-cid-remix-10517614.html",
"src": "soundeo",
"grp": "B",
"note": "",
"dl": null,
"set": 1,
"artist": "Tame Impala"
},
{
"id": "8974589",
"t": "RUFUS - You Were Right (Nora En Pure Remix)",
"g": "Tech House",
"bpm": 122,
"key": "Ebmaj",
"cam": "5B",
"len": "5:34",
"u": "https://soundeo.com/track/rufus-you-were-right-nora-en-pure-remix-8974589.html",
"src": "soundeo",
"grp": "A",
"note": "",
"dl": null,
"set": 2,
"artist": "RÜFÜS DU SOL"
},
{
"id": "14855633",
"t": "RÜFÜS DU SOL - Be With You (Booka Shade Remix)",
"g": "Tech House",
"bpm": 122,
"key": "Cmin",
"cam": "5A",
"len": "7:14",
"u": "https://soundeo.com/track/ruefues-du-sol-be-with-you-booka-shade-remix-14855633.html",
"src": "soundeo",
"grp": "A",
"note": "",
"dl": null,
"set": 3,
"artist": "RÜFÜS DU SOL"
},
{
"id": "10454347",
"t": "Tame Impala, ZHU - My Life (Kyle Watson Remix)",
"g": "Tech House",
"bpm": 123,
"key": "Cmin",
"cam": "5A",
"len": "5:43",
"u": "https://soundeo.com/track/tame-impala-zhu-my-life-kyle-watson-remix-10454347.html",
"src": "soundeo",
"grp": "A",
"note": "",
"dl": null,
"set": 4,
"artist": "Tame Impala"
},
{
"id": "5442586",
"t": "GoldFish, Emily Bruce - Choose Your Own Adventure (Kyle Watson Remix)",
"g": "Deep House",
"bpm": 124,
"key": "Cmin",
"cam": "5A",
"len": "6:13",
"u": "https://soundeo.com/track/goldfish-emily-bruce-choose-your-own-adventure-kyle-watson-remix-5442586.html",
"src": "soundeo",
"grp": "B",
"note": "",
"dl": null,
"set": 5,
"artist": "GoldFish"
},
{
"id": "16072320",
"t": "Louis The Child, Royal & the Serpent - Talk (Bleu Clair Remix)",
"g": "Dance / Pop",
"bpm": 126,
"key": "Gmin",
"cam": "6A",
"len": "4:23",
"u": "https://soundeo.com/track/louis-the-child-bleu-clair-royal-the-serpent-talk-bleu-clair-remix-16072320.html",
"src": "soundeo",
"grp": "B",
"note": "",
"dl": null,
"set": 6,
"artist": "Louis The Child"
},
{
"id": "13958096",
"t": "GRiZ, Wreckno - Medusa (J. Worra Remix)",
"g": "Tech House",
"bpm": 124,
"key": "Dmin",
"cam": "7A",
"len": "4:26",
"u": "https://soundeo.com/track/griz-wreckno-medusa-j-worra-remix-13958096.html",
"src": "soundeo",
"grp": "A",
"note": "",
"dl": null,
"set": 7,
"artist": "GRiZ"
},
{
"id": "13994311",
"t": "CloZee - Neon Jungle (Lane 8 Remix)",
"g": "Melodic House & Techno",
"bpm": 124,
"key": "Fmaj",
"cam": "7B",
"len": "4:09",
"u": "https://soundeo.com/track/clozee-neon-jungle-lane-8-remix-13994311.html",
"src": "soundeo",
"grp": "B",
"note": "",
"dl": null,
"set": 8,
"artist": "CloZee"
},
{
"id": "1786406",
"t": "GoldFish, Sakhile Moleshe - We Come Together (Shaun Duvet & Softserve's Remix)",
"g": "Deep House",
"bpm": 125,
"key": "Cmaj",
"cam": "8B",
"len": "6:43",
"u": "https://soundeo.com/track/goldfish-sakhile-moleshe-we-come-together-shaun-duvet-softserve-s-remix-1786406.html",
"src": "soundeo",
"grp": "B",
"note": "",
"dl": null,
"set": 9,
"artist": "GoldFish"
},
{
"id": "15772455",
"t": "Florence + The Machine - My Love (MEDUZA Extended Remix)",
"g": "Dance / Pop",
"bpm": 125,
"key": "Amin",
"cam": "8A",
"len": "7:13",
"u": "https://soundeo.com/track/florence-the-machine-meduza-my-love-meduza-extended-remix-15772455.html",
"src": "soundeo",
"grp": "B",
"note": "",
"dl": null,
"set": 10,
"artist": "Florence + The Machine"
},
{
"id": "3966725",
"t": "Kanye West / Common / Malik Yusef / JV - Wouldn't You Like to Ride (KitSch 2.0 & Stephane B Remix)",
"g": "Tech House",
"bpm": 126,
"key": "Amin",
"cam": "8A",
"len": "7:05",
"u": "https://soundeo.com/track/jv-common-malik-yusef-kanye-west-wouldn-t-you-like-to-ride-s-s-remixes-kitsch-2-0-stephane-b-remix-3966725.html",
"src": "soundeo",
"grp": "A",
"note": "",
"dl": false,
"set": 11,
"artist": "Kanye West"
},
{
"id": "16443693",
"t": "Gorillaz, Tame Impala, Bootie Brown - New Gold (Dom Dolla Remix Extended)",
"g": "Tech House",
"bpm": 127,
"key": "Emin",
"cam": "9A",
"len": "6:03",
"u": "https://soundeo.com/track/bootie-brown-tame-impala-gorillaz-new-gold-feat-tame-impala-and-bootie-brown-dom-dolla-remix-extended-16443693.html",
"src": "soundeo",
"grp": "A",
"note": "",
"dl": null,
"set": 12,
"artist": "Tame Impala"
},
{
"id": "1485153",
"t": "Florence And The Machine - Drumming Song (Boy 8-Bit Remix)",
"g": "Tech House",
"bpm": 128,
"key": "Emin",
"cam": "9A",
"len": "6:31",
"u": "https://soundeo.com/track/florence-and-the-machine-drumming-song-boy-8-bit-remix-1485153.html",
"src": "soundeo",
"grp": "A",
"note": "",
"dl": null,
"set": 13,
"artist": "Florence + The Machine"
},
{
"id": "3722683",
"t": "Florence & The Machine - Spectrum (Taito Tikaro & Flavio Zarza Remix)",
"g": "Progressive House",
"bpm": 128,
"key": "Bmin",
"cam": "10A",
"len": "7:25",
"u": "https://soundeo.com/track/florence-the-machine-spectrum-taito-tikaro-and-flavio-zarza-remix-3722683.html",
"src": "soundeo",
"grp": "B",
"note": "",
"dl": null,
"set": 14,
"artist": "Florence + The Machine"
},
{
"id": "7113836",
"t": "Florence + The Machine - Spectrum (Say My Name) (Calvin Harris Remix)",
"g": "Deep House",
"bpm": 126,
"key": "Bmin",
"cam": "10A",
"len": "6:13",
"u": "https://soundeo.com/track/florence-the-machine-spectrum-say-my-name-calvin-harris-remix-7113836.html",
"src": "soundeo",
"grp": "B",
"note": "",
"dl": null,
"set": 15,
"artist": "Florence + The Machine"
},
{
"id": "583998",
"t": "Kid Cudi - Day 'N' Nite (Crookers Remix)",
"g": "Electro House",
"bpm": 130,
"key": "Bmin",
"cam": "10A",
"len": "4:42",
"u": "https://soundeo.com/track/kid-cudi-day-n-nite-crookers-remix-583998.html",
"src": "soundeo",
"grp": "B",
"note": "",
"dl": null,
"set": 16,
"artist": "Kid Cudi"
},
{
"id": "9437047",
"t": "GRiZ - Before I Go feat. Leo Napier (AC Slater Remix)",
"g": "UK Garage / Bassline",
"bpm": 130,
"key": "Dmaj",
"cam": "10B",
"len": "4:14",
"u": "https://soundeo.com/track/griz-before-i-go-feat-leo-napier-ac-slater-remix-9437047.html",
"src": "soundeo",
"grp": "B",
"note": "",
"dl": null,
"set": 17,
"artist": "GRiZ"
},
{
"id": "1597758",
"t": "GoldFish - Get Busy Living (Heds Remix)",
"g": "Tech House",
"bpm": 127,
"key": "Bbmin",
"cam": "3A",
"len": "6:25",
"u": "https://soundeo.com/track/goldfish-get-busy-living-heds-remix-1597758.html",
"src": "soundeo",
"grp": "A",
"note": "",
"dl": null,
"set": 18,
"artist": "GoldFish"
},
{
"id": "6845055",
"t": "Florence + The Machine - Queen Of Peace (Hot Chip Remix)",
"g": "House",
"bpm": 126,
"key": "Bbmin",
"cam": "3A",
"len": "6:25",
"u": "https://soundeo.com/track/florence-the-machine-queen-of-peace-hot-chip-remix-6845055.html",
"src": "soundeo",
"grp": "B",
"note": "",
"dl": null,
"set": 19,
"artist": "Florence + The Machine"
},
{
"id": "872326",
"t": "GoldFish - Hold Tight (Shaun Duvet & SoftServe's Chop Suey Edit)",
"g": "Tech House",
"bpm": 127,
"key": "Fmin",
"cam": "4A",
"len": "6:21",
"u": "https://soundeo.com/track/goldfish-hold-tight-shaun-duvet-softserve-s-chop-suey-edit-872326.html",
"src": "soundeo",
"grp": "A",
"note": "",
"dl": null,
"set": 20,
"artist": "GoldFish"
},
{
"id": "16604698",
"t": "Plus Beat'Z - Californication",
"g": "Tech House",
"bpm": 127,
"key": "Fmin",
"cam": "4A",
"len": "5:40",
"u": "https://soundeo.com/track/plus-beat-z-californication-original-mix-16604698.html",
"src": "soundeo",
"grp": "C",
"note": "RHCP cover, unverified",
"dl": null,
"set": 21,
"artist": "Red Hot Chili Peppers"
},
{
"id": "23291041",
"t": "Tame Impala - Loser (Fcukers Remix)",
"g": "Dance / Pop",
"bpm": 128,
"key": "Fmin",
"cam": "4A",
"len": "4:27",
"u": "https://soundeo.com/track/tame-impala-fcukers-loser-fcukers-remix-23291041.html",
"src": "soundeo",
"grp": "B",
"note": "",
"dl": null,
"set": 22,
"artist": "Tame Impala"
},
{
"id": "9760377",
"t": "GoldFish - This Is How It Goes (Timmy Trumpet Mix)",
"g": "House",
"bpm": 128,
"key": "Fmin",
"cam": "4A",
"len": "7:12",
"u": "https://soundeo.com/track/goldfish-this-is-how-it-goes-timmy-trumpet-mix-9760377.html",
"src": "soundeo",
"grp": "B",
"note": "",
"dl": null,
"set": 23,
"artist": "GoldFish"
},
{
"id": "1796842",
"t": "The Cube Guys - Baba O'Riley (Prok & Fitch Vocal Remix)",
"g": "Tech House",
"bpm": 128,
"key": "Fmaj",
"cam": "7B",
"len": "7:46",
"u": "https://soundeo.com/track/the-cube-guys-baba-o-riley-prok-fitch-vocal-remix-1796842.html",
"src": "soundeo",
"grp": "C",
"note": "cover of The Who",
"dl": null,
"set": 24,
"artist": "The Who"
},
{
"id": "17159580",
"t": "Ratatat, Kid Cudi, MGMT - Pursuit Of Happiness (Extended Steve Aoki Remix)",
"g": "Electro House",
"bpm": 128,
"key": "Cmaj",
"cam": "8B",
"len": "6:13",
"u": "https://soundeo.com/track/ratatat-kid-cudi-mgmt-pursuit-of-happiness-extended-steve-aoki-remix-17159580.html",
"src": "soundeo",
"grp": "B",
"note": "",
"dl": null,
"set": 25,
"artist": "Kid Cudi"
},
{
"id": "18970887",
"t": "Odd Mob, Sofi Tukker - Bread (Odd Mob Extended Remix)",
"g": "Tech House",
"bpm": 130,
"key": "Amin",
"cam": "8A",
"len": "4:25",
"u": "https://soundeo.com/track/odd-mob-sofi-tukker-bread-odd-mob-extended-remix-18970887.html",
"src": "soundeo",
"grp": "A",
"note": "",
"dl": true,
"set": 26,
"artist": "Sofi Tukker"
},
{
"id": "8974590",
"t": "RUFUS - You Were Right (Catz 'N Dogz Remix)",
"g": "Tech House",
"bpm": 122,
"key": "Bbmin",
"cam": "3A",
"len": "5:41",
"u": "https://soundeo.com/track/rufus-you-were-right-catz-n-dogz-remix-8974590.html",
"src": "soundeo",
"grp": "A",
"note": "",
"dl": null,
"set": null,
"artist": "RÜFÜS DU SOL"
},
{
"id": "8974591",
"t": "RUFUS - You Were Right (Braxton Remix)",
"g": "Tech House",
"bpm": 122,
"key": "Abmin",
"cam": "1A",
"len": "6:52",
"u": "https://soundeo.com/track/rufus-you-were-right-braxton-remix-8974591.html",
"src": "soundeo",
"grp": "A",
"note": "",
"dl": null,
"set": null,
"artist": "RÜFÜS DU SOL"
},
{
"id": "7096709",
"t": "RÜFÜS DU SOL - Only You (Doc Link's Liberate Mix)",
"g": "Tech House",
"bpm": 126,
"key": "Ebmin",
"cam": "2A",
"len": "6:51",
"u": "https://soundeo.com/track/ruefues-du-sol-only-you-doc-link-s-liberate-mix-7096709.html",
"src": "soundeo",
"grp": "A",
"note": "",
"dl": null,
"set": null,
"artist": "RÜFÜS DU SOL"
},
{
"id": "10959111",
"t": "The Knocks, Sofi Tukker - Brazilian Soul (Walker & Royce Remix)",
"g": "Tech House",
"bpm": 126,
"key": "Ebmaj",
"cam": "5B",
"len": "5:39",
"u": "https://soundeo.com/track/the-knocks-sofi-tukker-brazilian-soul-feat-sofi-tukker-walker-royce-remix-10959111.html",
"src": "soundeo",
"grp": "A",
"note": "",
"dl": true,
"set": null,
"artist": "Sofi Tukker"
},
{
"id": "3966729",
"t": "Kanye West / Common / Malik Yusef / JV - Wouldn't You Like to Ride (The House Moguls Remix)",
"g": "Tech House",
"bpm": 126,
"key": "Amaj",
"cam": "11B",
"len": "7:13",
"u": "https://soundeo.com/track/jv-common-malik-yusef-kanye-west-wouldn-t-you-like-to-ride-s-s-remixes-the-house-moguls-remix-3966729.html",
"src": "soundeo",
"grp": "A",
"note": "",
"dl": false,
"set": null,
"artist": "Kanye West"
},
{
"id": "4235316",
"t": "Kanye West / Common / Malik Yusef / JV - Wouldn't You Like To Ride (Fast Eddie Off The Block S&S Remix)",
"g": "Tech House",
"bpm": 126,
"key": "Amaj",
"cam": "11B",
"len": "5:06",
"u": "https://soundeo.com/track/jv-dj-fast-eddie-common-malik-yusef-kanye-west-wouldn-t-you-like-to-ride-s-s-remixes-fast-eddie-off-the-block-s-s-remix-4235316.html",
"src": "soundeo",
"grp": "A",
"note": "",
"dl": false,
"set": null,
"artist": "Kanye West"
},
{
"id": "10968491",
"t": "The Knocks, Sofi Tukker - Brazilian Soul (Walker & Royce Extended Mix)",
"g": "Tech House",
"bpm": null,
"key": "",
"cam": "",
"len": "",
"u": "https://soundeo.com/track/the-knocks-sofi-tukker-brazilian-soul-feat-sofi-tukker-walker-royce-extended-mix-10968491.html",
"src": "soundeo",
"grp": "A",
"note": "extended version",
"dl": true,
"set": null,
"artist": "Sofi Tukker"
},
{
"id": "8197671",
"t": "Kai, Flume - Never Be Like You (Disclosure Remix)",
"g": "House",
"bpm": 120,
"key": "Dmaj",
"cam": "10B",
"len": "6:11",
"u": "https://soundeo.com/track/kai-flume-never-be-like-you-disclosure-remix-8197671.html",
"src": "soundeo",
"grp": "B",
"note": "",
"dl": null,
"set": null,
"artist": "Flume"
},
{
"id": "16537258",
"t": "RÜFÜS DU SOL - Like an Animal (Isaac Tichauer Remix)",
"g": "Deep House",
"bpm": 120,
"key": "Dmin",
"cam": "7A",
"len": "7:28",
"u": "https://soundeo.com/track/ruefues-du-sol-like-an-animal-isaac-tichauer-remix-16537258.html",
"src": "soundeo",
"grp": "B",
"note": "",
"dl": null,
"set": null,
"artist": "RÜFÜS DU SOL"
},
{
"id": "7394703",
"t": "Sofi Tukker - Drinkee (Addal Remix)",
"g": "Deep House",
"bpm": 120,
"key": "Amaj",
"cam": "11B",
"len": "4:58",
"u": "https://soundeo.com/track/sofi-tukker-drinkee-addal-remix-7394703.html",
"src": "soundeo",
"grp": "B",
"note": "",
"dl": true,
"set": null,
"artist": "Sofi Tukker"
},
{
"id": "18778844",
"t": "Justice, Tame Impala - Neverender (Rampa Remix)",
"g": "Afro House",
"bpm": 120,
"key": "Dbmin",
"cam": "12A",
"len": "6:24",
"u": "https://soundeo.com/track/justice-rampa-tame-impala-keinemusik-neverender-rampa-remix-18778844.html",
"src": "soundeo",
"grp": "B",
"note": "",
"dl": null,
"set": null,
"artist": "Tame Impala"
},
{
"id": "18778843",
"t": "Justice, Tame Impala - Neverender (Kaytranada Remix)",
"g": "Afro House",
"bpm": 120,
"key": "Emaj",
"cam": "12B",
"len": "4:45",
"u": "https://soundeo.com/track/justice-tame-impala-kaytranada-neverender-kaytranada-remix-18778843.html",
"src": "soundeo",
"grp": "B",
"note": "",
"dl": null,
"set": null,
"artist": "Tame Impala"
},
{
"id": "7988458",
"t": "Paul McCartney & Wings vs Timo Maas & James Teej - Nineteen Hundred And Eighty Five (Tim Green Remix)",
"g": "Deep House",
"bpm": 120,
"key": "Abmaj",
"cam": "4B",
"len": "8:49",
"u": "https://soundeo.com/track/timo-maas-james-teej-wings-paul-mccartney-nineteen-hundred-and-eighty-five-paul-mccartney-wings-vs-timo-maas-james-teej-tim-green-remix-tim-green-remix-7988458.html",
"src": "soundeo",
"grp": "B",
"note": "",
"dl": null,
"set": null,
"artist": "Paul McCartney"
},
{
"id": "5074020",
"t": "Tame Impala - Be Above It (Erol Alkan Rework)",
"g": "Techno (Peak Time)",
"bpm": 120,
"key": "Gmaj",
"cam": "9B",
"len": "7:43",
"u": "https://soundeo.com/track/tame-impala-be-above-it-erol-alkan-rework-5074020.html",
"src": "soundeo",
"grp": "B",
"note": "",
"dl": null,
"set": null,
"artist": "Tame Impala"
},
{
"id": "16537257",
"t": "RÜFÜS DU SOL - Like an Animal (Dom Dolla Remix)",
"g": "House",
"bpm": 122,
"key": "Abmin",
"cam": "1A",
"len": "5:21",
"u": "https://soundeo.com/track/ruefues-du-sol-like-an-animal-dom-dolla-remix-16537257.html",
"src": "soundeo",
"grp": "B",
"note": "",
"dl": null,
"set": null,
"artist": "RÜFÜS DU SOL"
},
{
"id": "14855636",
"t": "RÜFÜS DU SOL - Be With You (Sondrio Remix)",
"g": "House",
"bpm": 122,
"key": "Cmin",
"cam": "5A",
"len": "5:35",
"u": "https://soundeo.com/track/ruefues-du-sol-be-with-you-sondrio-remix-14855636.html",
"src": "soundeo",
"grp": "B",
"note": "",
"dl": null,
"set": null,
"artist": "RÜFÜS DU SOL"
},
{
"id": "11335334",
"t": "Florence + The Machine - Hunger (Claptone Remix)",
"g": "House",
"bpm": 122,
"key": "Fmaj",
"cam": "7B",
"len": "5:16",
"u": "https://soundeo.com/track/florence-the-machine-hunger-11335334.html",
"src": "soundeo",
"grp": "B",
"note": "",
"dl": null,
"set": null,
"artist": "Florence + The Machine"
},
{
"id": "10517613",
"t": "Tame Impala, ZHU - My Life (Blond:ish Remix)",
"g": "Melodic House & Techno",
"bpm": 122,
"key": "Cmin",
"cam": "5A",
"len": "6:59",
"u": "https://soundeo.com/track/tame-impala-zhu-my-life-blond-ish-remix-10517613.html",
"src": "soundeo",
"grp": "B",
"note": "",
"dl": null,
"set": null,
"artist": "Tame Impala"
},
{
"id": "7382532",
"t": "RÜFÜS DU SOL - Like an Animal (Luca Guerrieri Remix)",
"g": "House",
"bpm": 123,
"key": "Amin",
"cam": "8A",
"len": "5:36",
"u": "https://soundeo.com/track/ruefues-du-sol-like-an-animal-luca-guerrieri-remix-7382532.html",
"src": "soundeo",
"grp": "B",
"note": "",
"dl": null,
"set": null,
"artist": "RÜFÜS DU SOL"
},
{
"id": "11901716",
"t": "RÜFÜS DU SOL - Lost in My Mind (Justin Martin Remix)",
"g": "House",
"bpm": 123,
"key": "Ebmin",
"cam": "2A",
"len": "7:33",
"u": "https://soundeo.com/track/ruefues-du-sol-lost-in-my-mind-justin-martin-remix-11901716.html",
"src": "soundeo",
"grp": "B",
"note": "",
"dl": null,
"set": null,
"artist": "RÜFÜS DU SOL"
},
{
"id": "20235298",
"t": "Lady Gaga, Ariana Grande - Rain On Me (Purple Disco Machine Remix)",
"g": "Pop",
"bpm": 123,
"key": "Dbmin",
"cam": "12A",
"len": "6:34",
"u": "https://soundeo.com/track/purple-disco-machine-lady-gaga-ariana-grande-rain-on-me-purple-disco-machine-remix-20235298.html",
"src": "soundeo",
"grp": "B",
"note": "",
"dl": null,
"set": null,
"artist": "Ariana Grande"
},
{
"id": "8304220",
"t": "Florence + The Machine - Spectrum (Maya Jane Coles Remix)",
"g": "Deep House",
"bpm": 123,
"key": "Bmin",
"cam": "10A",
"len": "5:00",
"u": "https://soundeo.com/track/florence-the-machine-spectrum-maya-jane-coles-remix-8304220.html",
"src": "soundeo",
"grp": "B",
"note": "",
"dl": null,
"set": null,
"artist": "Florence + The Machine"
},
{
"id": "14855634",
"t": "RÜFÜS DU SOL - Be With You (Friend Within Remix)",
"g": "House",
"bpm": 124,
"key": "Cmin",
"cam": "5A",
"len": "6:31",
"u": "https://soundeo.com/track/ruefues-du-sol-be-with-you-friend-within-remix-14855634.html",
"src": "soundeo",
"grp": "B",
"note": "",
"dl": null,
"set": null,
"artist": "RÜFÜS DU SOL"
},
{
"id": "13958093",
"t": "GRiZ, Wreckno - Medusa (Giolì & Assia Remix)",
"g": "Future House",
"bpm": 124,
"key": "Gmin",
"cam": "6A",
"len": "3:02",
"u": "https://soundeo.com/track/griz-wreckno-medusa-gioli-assia-remix-13958093.html",
"src": "soundeo",
"grp": "B",
"note": "",
"dl": null,
"set": null,
"artist": "GRiZ"
},
{
"id": "19223725",
"t": "Sofi Tukker - Throw Some Ass (ForgiveMeTommy! Remix)",
"g": "Bass House",
"bpm": 124,
"key": "Ebmaj",
"cam": "5B",
"len": "4:24",
"u": "https://soundeo.com/track/sofi-tukker-forgivemetommy-throw-some-ass-forgivemetommy-remix-19223725.html",
"src": "soundeo",
"grp": "B",
"note": "",
"dl": true,
"set": null,
"artist": "Sofi Tukker"
},
{
"id": "11310197",
"t": "Raye, Louis The Child - Breaking News (Westend Remix)",
"g": "Bass House",
"bpm": 124,
"key": "Ebmin",
"cam": "2A",
"len": "4:11",
"u": "https://soundeo.com/track/raye-louis-the-child-breaking-news-11310197.html",
"src": "soundeo",
"grp": "B",
"note": "",
"dl": null,
"set": null,
"artist": "Louis The Child"
},
{
"id": "22088464",
"t": "Boys Noize, Tame Impala, JENNIE - Dracula (JENNIE Remix - Boys Noize Disko Version)",
"g": "Dance / Pop",
"bpm": 124,
"key": "Bbmin",
"cam": "3A",
"len": "4:00",
"u": "https://soundeo.com/track/boys-noize-tame-impala-jennie-dracula-jennie-remix-boys-noize-disko-version-22088464.html",
"src": "soundeo",
"grp": "B",
"note": "",
"dl": null,
"set": null,
"artist": "Tame Impala"
},
{
"id": "19273662",
"t": "Sofi Tukker - Purple Hat (Adam Sellouk & Doriann Extended Remix)",
"g": "Melodic House & Techno",
"bpm": 125,
"key": "Amaj",
"cam": "11B",
"len": "5:30",
"u": "https://soundeo.com/track/sofi-tukker-doriann-adam-sellouk-purple-hat-adam-sellouk-and-doriann-extended-remix-19273662.html",
"src": "soundeo",
"grp": "B",
"note": "",
"dl": true,
"set": null,
"artist": "Sofi Tukker"
},
{
"id": "8093112",
"t": "Icona Pop, Louis The Child - Weekend (Redlight Remix)",
"g": "House",
"bpm": 125,
"key": "Abmin",
"cam": "1A",
"len": "6:09",
"u": "https://soundeo.com/track/icona-pop-louis-the-child-weekend-redlight-remix-8093112.html",
"src": "soundeo",
"grp": "B",
"note": "",
"dl": null,
"set": null,
"artist": "Louis The Child"
},
{
"id": "11627691",
"t": "RÜFÜS DU SOL - Underwater (Willaris. K Remix)",
"g": "House",
"bpm": 126,
"key": "F#min",
"cam": "11A",
"len": "9:06",
"u": "https://soundeo.com/track/ruefues-du-sol-underwater-willaris-k-remix-11627691.html",
"src": "soundeo",
"grp": "B",
"note": "",
"dl": null,
"set": null,
"artist": "RÜFÜS DU SOL"
},
{
"id": "18666204",
"t": "RÜFÜS DU SOL - Lately (Adam Ten & Mita Gami Remix)",
"g": "Deep House",
"bpm": 126,
"key": "Dbmin",
"cam": "12A",
"len": "3:36",
"u": "https://soundeo.com/track/ruefues-du-sol-lately-adam-ten-mita-gami-remix-18666204.html",
"src": "soundeo",
"grp": "B",
"note": "",
"dl": null,
"set": null,
"artist": "RÜFÜS DU SOL"
},
{
"id": "14113896",
"t": "Sofi Tukker, Charlie Barker - Good Time Girl (Benny Benassi & BB Team Remix)",
"g": "House",
"bpm": 126,
"key": "Ebmaj",
"cam": "5B",
"len": "2:55",
"u": "https://soundeo.com/track/sofi-tukker-charlie-barker-good-time-girl-benny-benassi-bb-team-remix-14113896.html",
"src": "soundeo",
"grp": "B",
"note": "",
"dl": true,
"set": null,
"artist": "Sofi Tukker"
},
{
"id": "14426267",
"t": "CloZee, Sauvane - Air (Enamour Remix)",
"g": "House",
"bpm": 126,
"key": "Fmin",
"cam": "4A",
"len": "4:11",
"u": "https://soundeo.com/track/clozee-sauvane-air-enamour-remix-14426267.html",
"src": "soundeo",
"grp": "B",
"note": "",
"dl": null,
"set": null,
"artist": "CloZee"
},
{
"id": "21126964",
"t": "Kanye West / Common / Malik Yusef - Wouldn't You Like to Ride (Steve Silk Hurley & DJ Skip Ride To The House Remix)",
"g": "House",
"bpm": 126,
"key": "Amaj",
"cam": "11B",
"len": "4:58",
"u": "https://soundeo.com/track/malik-yusef-wouldn-t-you-like-to-ride-feat-kanye-west-common-jv-steve-silk-hurley-dj-skip-ride-to-the-house-remix-21126964.html",
"src": "soundeo",
"grp": "B",
"note": "",
"dl": false,
"set": null,
"artist": "Kanye West"
},
{
"id": "8183552",
"t": "Ariana Grande - Into You (3LAU Extended Remix)",
"g": "Dance / Pop",
"bpm": 126,
"key": "Amaj",
"cam": "11B",
"len": "4:17",
"u": "https://soundeo.com/track/ariana-grande-into-you-3lau-extended-remix-8183552.html",
"src": "soundeo",
"grp": "B",
"note": "",
"dl": null,
"set": null,
"artist": "Ariana Grande"
},
{
"id": "18270850",
"t": "Foster The People, Louis The Child - Every Color (Dombresky Remix)",
"g": "Future House",
"bpm": 127,
"key": "Dmin",
"cam": "7A",
"len": "3:21",
"u": "https://soundeo.com/track/foster-the-people-louis-the-child-every-color-dombresky-remix-18270850.html",
"src": "soundeo",
"grp": "B",
"note": "",
"dl": null,
"set": null,
"artist": "Louis The Child"
},
{
"id": "7113798",
"t": "Florence + The Machine - You've Got The Love (Mark Knight Remix)",
"g": "Deep House",
"bpm": 128,
"key": "Ebmin",
"cam": "2A",
"len": "8:06",
"u": "https://soundeo.com/track/florence-the-machine-youve-got-the-love-mark-knight-remix-7113798.html",
"src": "soundeo",
"grp": "B",
"note": "",
"dl": null,
"set": null,
"artist": "Florence + The Machine"
},
{
"id": "4485254",
"t": "Red Hot Chili Peppers - Otherside (Third Party Remix)",
"g": "Big Room",
"bpm": 128,
"key": "Cmaj",
"cam": "8B",
"len": "5:56",
"u": "https://soundeo.com/track/red-hot-chili-peppers-third-party-otherside-third-party-remix-4485254.html",
"src": "soundeo",
"grp": "B",
"note": "",
"dl": null,
"set": null,
"artist": "Red Hot Chili Peppers"
},
{
"id": "21679028",
"t": "Sofi Tukker - BOBA (Extended Mix)",
"g": "Tech House",
"bpm": null,
"key": "",
"cam": "",
"len": "",
"u": "https://soundeo.com/track/sofi-tukker-boba-extended-mix-21679028.html",
"src": "soundeo",
"grp": "B",
"note": "Sofi Tukker original",
"dl": true,
"set": null,
"artist": "Sofi Tukker"
},
{
"id": "19631582",
"t": "Nonô, Sofi Tukker - Pick Up The Phone (Original Mix)",
"g": "Tech House",
"bpm": null,
"key": "",
"cam": "",
"len": "",
"u": "https://soundeo.com/track/nono-sofi-tukker-pick-up-the-phone-original-mix-19631582.html",
"src": "soundeo",
"grp": "B",
"note": "Sofi Tukker original",
"dl": true,
"set": null,
"artist": "Sofi Tukker"
},
{
"id": "5623689",
"t": "Francois Bresez - Hey Jude",
"g": "Tech House",
"bpm": 120,
"key": "Cmin",
"cam": "5A",
"len": "8:31",
"u": "https://soundeo.com/track/francois-bresez-hey-jude-original-mix-5623689.html",
"src": "soundeo",
"grp": "C",
"note": "Beatles cover, unverified",
"dl": null,
"set": null,
"artist": "The Beatles"
},
{
"id": "16021987",
"t": "Doctor Boom, Chris Khaos - Street Spirit",
"g": "Tech House",
"bpm": 124,
"key": "Fmin",
"cam": "4A",
"len": "5:02",
"u": "https://soundeo.com/track/doctor-boom-chris-khaos-street-spirit-original-mix-16021987.html",
"src": "soundeo",
"grp": "C",
"note": "Radiohead cover, unverified",
"dl": null,
"set": null,
"artist": "Radiohead"
},
{
"id": "18098114",
"t": "Goodman - You've Got the Love (Extended Mix)",
"g": "Tech House",
"bpm": 125,
"key": "Ebmin",
"cam": "2A",
"len": "4:39",
"u": "https://soundeo.com/track/goodman-you-ve-got-the-love-extended-mix-18098114.html",
"src": "soundeo",
"grp": "C",
"note": "Florence/Candi Staton cover, unverified",
"dl": null,
"set": null,
"artist": "Florence + The Machine"
},
{
"id": "23065507",
"t": "Chanelo, Vitto (ITA) - Let It Happen",
"g": "Tech House",
"bpm": 125,
"key": "Dmaj",
"cam": "10B",
"len": "6:48",
"u": "https://soundeo.com/track/chanelo-vitto-ita-let-it-happen-original-mix-23065507.html",
"src": "soundeo",
"grp": "C",
"note": "Tame Impala cover, unverified",
"dl": null,
"set": null,
"artist": "Tame Impala"
},
{
"id": "20643980",
"t": "MK Beats - The Less I Know The Better",
"g": "Tech House",
"bpm": 126,
"key": "Fmin",
"cam": "4A",
"len": "2:47",
"u": "https://soundeo.com/track/mk-beats-the-less-i-know-the-better-original-mix-20643980.html",
"src": "soundeo",
"grp": "C",
"note": "Tame Impala cover, unverified",
"dl": null,
"set": null,
"artist": "Tame Impala"
},
{
"id": "20643809",
"t": "Francis K - The Less I Know The Better",
"g": "Tech House",
"bpm": 128,
"key": "Dbmin",
"cam": "12A",
"len": "3:00",
"u": "https://soundeo.com/track/francis-k-the-less-i-know-the-better-original-mix-20643809.html",
"src": "soundeo",
"grp": "C",
"note": "Tame Impala cover, unverified",
"dl": null,
"set": null,
"artist": "Tame Impala"
},
{
"id": "20641547",
"t": "Samba De Malandro - The Less I Know The Better",
"g": "Tech House",
"bpm": 128,
"key": "Bbmin",
"cam": "3A",
"len": "3:55",
"u": "https://soundeo.com/track/samba-de-malandro-the-less-i-know-the-better-original-mix-20641547.html",
"src": "soundeo",
"grp": "C",
"note": "Tame Impala cover, unverified",
"dl": null,
"set": null,
"artist": "Tame Impala"
},
{
"id": "18965757",
"t": "KsoFresKo - Here Comes The Sun",
"g": "Tech House",
"bpm": 129,
"key": "Gbmin",
"cam": "11A",
"len": "5:12",
"u": "https://soundeo.com/track/ksofresko-here-comes-the-sun-original-mix-18965757.html",
"src": "soundeo",
"grp": "C",
"note": "Beatles cover, unverified",
"dl": null,
"set": null,
"artist": "The Beatles"
},
{
"id": "17407153",
"t": "Victor Lou - Kanyes (Original Mix)",
"g": "Tech House",
"bpm": null,
"key": "",
"cam": "",
"len": "",
"u": "https://soundeo.com/track/victor-lou-kanyes-original-mix-17407153.html",
"src": "soundeo",
"grp": "C",
"note": "Kanye-themed tech house, unverified",
"dl": true,
"set": null,
"artist": "Kanye West"
},
{
"id": "17108481",
"t": "George Z - I Love Kanye (Extended Mix)",
"g": "Tech House",
"bpm": null,
"key": "",
"cam": "",
"len": "",
"u": "https://soundeo.com/track/george-z-i-love-kanye-extended-mix-17108481.html",
"src": "soundeo",
"grp": "C",
"note": "Kanye \"I Love Kanye\" flip, unverified",
"dl": true,
"set": null,
"artist": "Kanye West"
},
{
"id": "14693839",
"t": "Xeno - Kanye (Original Mix)",
"g": "Tech House",
"bpm": null,
"key": "",
"cam": "",
"len": "",
"u": "https://soundeo.com/track/xeno-kanye-original-mix-14693839.html",
"src": "soundeo",
"grp": "C",
"note": "Kanye-themed tech house, unverified",
"dl": true,
"set": null,
"artist": "Kanye West"
},
{
"id": "17553954",
"t": "Dance Fruits Music, This Is MELON - I Love Kanye (Original Mix)",
"g": "Bass House",
"bpm": null,
"key": "",
"cam": "",
"len": "",
"u": "https://soundeo.com/track/dance-fruits-music-this-is-melon-i-love-kanye-original-mix-17553954.html",
"src": "soundeo",
"grp": "C",
"note": "Kanye cover, unverified",
"dl": true,
"set": null,
"artist": "Kanye West"
},
{
"id": "20627336",
"t": "Samba De Malandro - Innerbloom (Original Mix)",
"g": "Tech House",
"bpm": null,
"key": "",
"cam": "",
"len": "",
"u": "https://soundeo.com/track/samba-de-malandro-innerbloom-original-mix-20627336.html",
"src": "soundeo",
"grp": "C",
"note": "RÜFÜS cover, unverified",
"dl": null,
"set": null,
"artist": "RÜFÜS DU SOL"
},
{
"id": "21583171",
"t": "Red Redmore - Innerbloom (Original Mix)",
"g": "Tech House",
"bpm": null,
"key": "",
"cam": "",
"len": "",
"u": "https://soundeo.com/track/red-redmore-innerbloom-original-mix-21583171.html",
"src": "soundeo",
"grp": "C",
"note": "RÜFÜS cover, unverified",
"dl": null,
"set": null,
"artist": "RÜFÜS DU SOL"
},
{
"id": "8285067",
"t": "Sharam, Kid Cudi - She Came Along (Doorly Remix)",
"g": "Deep House",
"bpm": 68,
"key": "Gbmaj",
"cam": "2B",
"len": "4:53",
"u": "https://soundeo.com/track/sharam-kid-cudi-she-came-along-doorly-remix-8285067.html",
"src": "soundeo",
"grp": "D",
"note": "",
"dl": null,
"set": null,
"artist": "Kid Cudi"
},
{
"id": "9437040",
"t": "GRiZ - Good Times Roll feat. Big Gigantic (Ephwurd Remix)",
"g": "Bass House",
"bpm": 100,
"key": "Ebmin",
"cam": "2A",
"len": "3:20",
"u": "https://soundeo.com/track/griz-good-times-roll-feat-big-gigantic-ephwurd-remix-9437040.html",
"src": "soundeo",
"grp": "D",
"note": "",
"dl": null,
"set": null,
"artist": "GRiZ"
},
{
"id": "19223727",
"t": "Sofi Tukker, Mia Moretti - Throw Some Ass (Mia Moretti Remix)",
"g": "Tech House",
"bpm": 131,
"key": "Ebmin",
"cam": "2A",
"len": "4:03",
"u": "https://soundeo.com/track/sofi-tukker-mia-moretti-throw-some-ass-mia-moretti-remix-19223727.html",
"src": "soundeo",
"grp": "D",
"note": "",
"dl": null,
"set": null,
"artist": "Sofi Tukker"
},
{
"id": "17812920",
"t": "CloZee, ROZET - Courage (Eyezic Remix)",
"g": "Bass House",
"bpm": 132,
"key": "Dmin",
"cam": "7A",
"len": "4:07",
"u": "https://soundeo.com/track/clozee-rozet-courage-eyezic-remix-17812920.html",
"src": "soundeo",
"grp": "D",
"note": "",
"dl": null,
"set": null,
"artist": "CloZee"
},
{
"id": "22944519",
"t": "Phantomax - Dog Days Are Over",
"g": "Tech House",
"bpm": 132,
"key": "Ebmaj",
"cam": "5B",
"len": "4:29",
"u": "https://soundeo.com/track/phantomax-dog-days-are-over-original-mix-22944519.html",
"src": "soundeo",
"grp": "D",
"note": "Florence cover, unverified",
"dl": null,
"set": null,
"artist": "Florence + The Machine"
},
{
"id": "12945279",
"t": "Flume, Vera Blue - Rushing Back (MJ Cole Remix)",
"g": "UK Garage / Bassline",
"bpm": 133,
"key": "Fmaj",
"cam": "7B",
"len": "4:44",
"u": "https://soundeo.com/track/flume-vera-blue-rushing-back-mj-cole-remix-12945279.html",
"src": "soundeo",
"grp": "D",
"note": "",
"dl": null,
"set": null,
"artist": "Flume"
},
{
"id": "15993068",
"t": "Flume, Oklou - Highest Building (Prospa Remix)",
"g": "UK Garage / Bassline",
"bpm": 135,
"key": "Abmaj",
"cam": "4B",
"len": "4:21",
"u": "https://soundeo.com/track/flume-oklou-highest-building-prospa-remix-15993068.html",
"src": "soundeo",
"grp": "D",
"note": "",
"dl": null,
"set": null,
"artist": "Flume"
},
{
"id": "21712742",
"t": "Röyksopp, Kid Cudi - Everywhere I Go (Marlon Hoffstadt Extended Remix)",
"g": "Dance / Pop",
"bpm": 144,
"key": "Bmin",
"cam": "10A",
"len": "4:56",
"u": "https://soundeo.com/track/royksopp-kid-cudi-bnyx-everywhere-i-go-remind-me-marlon-hoffstadt-extended-remix-21712742.html",
"src": "soundeo",
"grp": "D",
"note": "",
"dl": null,
"set": null,
"artist": "Kid Cudi"
}
];
